### ISSUE TITLE
Unable to find PSSH in mpd

### ISSUE THREAD

**Issue by ETBMina** [medvm/widevine_keys#10]
I got the error Unable to find PSSH in mpd.

mpd url: [https://cdxaws-ak.akamaized.net/out/v1/991106feb38743fa9930904065586e65/469c706849ff410385e5d65308566647/5e2a57fc0380466b9864849ce3f168ea/manifest.mpd?aws.manifestfilter=video_height:144-1080](url)

**Comment by arbarbosa1979** [comment]
Download the MPD file and search for --> `cenc:pssh` there you will find the pssh.

```AAADBHBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAuTkAgAAAQABANoCPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBlAFgAWABIAFIAcQBjAGoAdgAwAEcAVABDAEQAQQBlAEMAdABmADYATgBRAD0APQA8AC8ASwBJAEQAPgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAGQAcgBtAC4AYwBsAG8AdQBkAC4AaQBuAHMAeQBzAHYAdAAuAGMAbwBtAC8AYQBjAHEAdQBpAHIAZQAtAGwAaQBjAGUAbgBzAGUALwBwAGwAYQB5AHIAZQBhAGQAeQA8AC8ATABBAF8AVQBSAEwAPgA8AEQAUwBfAEkARAA+AGUAZgBBAEUAbQBrAEMAWQBoAGsASwByAGsAdQBaAGIANABJAGgAZgBsAFEAPQA9ADwALwBEAFMAXwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AFAAVABaAGkAOQBBAGUASABTAEIAYwA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==
```

**Comment by ETBMina** [comment]
@arbarbosa1979  thanks for your help.

**Comment by ETBMina** [comment]
I tried another site which cannot find PSSH tag in it.
mpd url: [https://akm.cdn.intigral-ott.net/Titles/M0012244/M0012244.ism/manifest.mpd](url)

**Comment by mzikagate** [comment]
> 

generate pssh from KID . its easy سهل جدا

**Comment by ETBMina** [comment]
@mzikagate how?

**Comment by zxx511** [comment]
Send license link like this
https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=
and mpd link To extract the encryption key

**Comment by mzikagate** [comment]
> @mzikagate how?

just generate it there is many tools doing it free

**Comment by kfriddy** [comment]
> > @mzikagate how?
> 
> just generate it there is many tools doing it free

Could you refer to one then? I got a similar issue

**Comment by arbarbosa1979** [comment]
> @mzikagate how?

It is written on the homepage how to do this, there it says to access this address --> [https://tools.axinom.com/generators/PsshBox](https://tools.axinom.com/generators/PsshBox)

Enter these values into the online tool:

**System ID**
EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED

**Version**
0

**Data** ==> **Widevine PSSH Data** ==> **Key** ==> **IDs** ==> KID from MPD

**Protection Scheme** .... Keep blank
**Crypto Period Index** .... Keep blank
**Crypto Period Duration (seconds)** .... Keep blank
**Show not recommended and deprecated fields**. .... Do not touch

_Click Generate_
