### ISSUE TITLE
Add [okko] support

### ISSUE THREAD

**Issue by ST02-droid** [medvm/widevine_keys#11]
Input MPD URL: https://msk-cdp25.playfamily.ru/data/cid/270886532-1639247632-oq164-LMcrgS_x7AghuslQ/storage106/clr/m/sp/73a54bfc-2d55-4755-a5b9-195cd4e9537e/output.ism/Manifest.mpd

License URL: https://drm.playfamily.ru/widevine/cenc/ZHBtbLOZoWsAaEKcn-6QtOvfrb0/getlicense

![image](https://user-images.githubusercontent.com/77666552/145680257-2a412a81-aab4-4973-839a-0583190ff1f7.png)
![image](https://user-images.githubusercontent.com/77666552/145680260-17c532fc-2f39-48a0-b389-9a6cfe71eeab.png)

![image](https://user-images.githubusercontent.com/77666552/145680201-6fde1d83-da87-426f-b75f-109e7354ba7b.png)

**Comment by medvm** [comment]
Видимо, тут тоже в заголовках запроса передается licenseRequest. Скиньте вывод команды "копировать как curl", попробуем разобраться

**Comment by PuMa2006** [comment]
> Видимо, тут тоже в заголовках запроса передается licenseRequest. Скиньте вывод команды "копировать как curl", попробуем разобраться

тут та же история, что допустим, с Peacock, похоже

https://msk-cdp12.playfamily.ru/data/cid/da0270a9e407-1639275928-V8S6OkpjEeZhxdf49bdUTQ/storage112/clr/m/shpq/8d02fe6b-a117-4862-847b-469da058b2c2/output.ism/Manifest.mpd

https://ghostbin.com/mfpXG

лицензия в base64, не бинарная

**Comment by medvm** [comment]
этот запрос каким-то непонятным образом дробится на части, потому что ни один из блоков сам по себе запросом являться не может

**Comment by medvm** [comment]
вот лучше бы он лицензию возвращал бинарную, а запросы в json base64 принимал

**Comment by ST02-droid** [comment]
Мне выдаёт два файла getlicense. 

Первый выглядит так: https://controlc.com/773a2023

![image](https://user-images.githubusercontent.com/77666552/145689025-eb3b5a02-df78-433a-a2bd-03cd8a9a6abb.png)

Второй так: https://controlc.com/17565b18

![image](https://user-images.githubusercontent.com/77666552/145689053-56a12c29-cd5a-4771-8500-4e946876ddb5.png)

**Comment by medvm** [comment]
Вместо чисто бинарных данных почему-то все вперемешку, байты, utf-8 символы, может быть, зашифровано чем-нибудь?

**Comment by ST02-droid** [comment]
> Вместо чисто бинарных данных почему-то все вперемешку, байты, utf-8 символы, может быть, зашифровано чем-нибудь?

Скорее всего. В самом начала переменной data есть не закодированные строки 
![image](https://user-images.githubusercontent.com/77666552/145701948-5a8a4ec5-cf25-4486-a510-f1d37fdf1b93.png)

**Comment by Dadapetia** [comment]
> Вместо чисто бинарных данных почему-то все вперемешку, байты, utf-8 символы, может быть, зашифровано чем-нибудь?

Добрый день. Тоже пытался с помощью getlicense и инструкции какого то автора, не получалось. Очень жду пока кто то сможет это решить...

**Comment by ST02-droid** [comment]
![image](https://user-images.githubusercontent.com/77666552/145703470-a1b1078f-dd34-4720-9e22-96fcc3ad603c.png)

**Comment by medvm** [comment]
> ![image](https://user-images.githubusercontent.com/77666552/145703470-a1b1078f-dd34-4720-9e22-96fcc3ad603c.png)

тут у вас на скриншоте весь запрос выглядит цельным, можете прям из этой вкладки payload скопировать?
Может быть, он именно при копировании в виде curl-команды дробится...

**Comment by PuMa2006** [comment]
> > ![image](https://user-images.githubusercontent.com/77666552/145703470-a1b1078f-dd34-4720-9e22-96fcc3ad603c.png)
> 
> тут у вас на скриншоте весь запрос выглядит цельным, можете прям из этой вкладки payload скопировать? Может быть, он именно при копировании в виде curl-команды дробится...

https://ghostbin.com/qvBhh

**Comment by medvm** [comment]
У okko licenseID одноразовый, поэтому процесс усложняется, так как перед процессом получения лицензии надо еще запрос на новый licenseID сгенерировать

**Comment by medvm** [comment]
[Разные licendeId по одному sessionID ](https://user-images.githubusercontent.com/43696206/145745019-12c5d046-602e-4fc2-9092-17faa2530507.png)

**Comment by ST02-droid** [comment]
Почему-то с этого дня выдаёт вот это
![image](https://user-images.githubusercontent.com/77666552/145753772-99af2683-4c35-45d0-ac23-53cd335f7159.png)

**Comment by medvm** [comment]
все необходимые пакеты установили? Какая версия python? Я тестировал только на 3,8 и 3,10

**Comment by ST02-droid** [comment]
> все необходимые пакеты установили? Какая версия python? Я тестировал только на 3,8 и 3,10

Да. 3.8. Вчера ещё работало, а щас выдаёт почему-то это. Пробовал на предыдущих версиях программы (без сегодняшнего обновления), тоже самое.

**Comment by medvm** [comment]
попробуйте `py l3.py`

**Comment by ST02-droid** [comment]
Сделал новую машину, ошибка исчезла. Только я не совсем понял, как всё таки получить ключ? 
Это я скопировал cURL 1?elements 
![image](https://user-images.githubusercontent.com/77666552/145781395-7621bea7-d2fe-486a-a87f-3ce68cc693a3.png)

**Comment by Dadapetia** [comment]
> попробуйте `py l3.py`

Привет. Получилось сделать абсолютно все, и очень жду пока добавите "скрипт для поддержки этой платформы", но хотелось бы и сейчас попробовать скачать. Я делаю вот [так](https://imgur.com/a/dTSV8B1), а дальше что? Что брать из Curl Converter, или туда вообще не надо? Я не понимаю где эту новую лицензию найти. Обьясните пожалуйста, если будет время)

**Comment by medvm** [comment]
Эту курл команду от 1?elements нужно выполнить в терминале, в ее выводе будет новый licenseId. Если нет курла в компе, скачайте сначала.

**Comment by PuMa2006** [comment]
Я смотрю это фишка у многих такая, rakuten так же генерирует новые лицензии/плейлисты

**Comment by medvm** [comment]
> Я смотрю это фишка у многих такая, rakuten так же генерирует новые лицензии/плейлисты

Это довольно удобно в плане проектирования высоконагруженной системы, поэтому логично

**Comment by stgmt** [comment]
> 

callId это licenseId? не пойму где в коде подставить новый id

**Comment by stgmt** [comment]
> > попробуйте `py l3.py`
> 
> Привет. Получилось сделать абсолютно все, и очень жду пока добавите "скрипт для поддержки этой платформы", но хотелось бы и сейчас попробовать скачать. Я делаю вот [так](https://imgur.com/a/dTSV8B1), а дальше что? Что брать из Curl Converter, или туда вообще не надо? Я не понимаю где эту новую лицензию найти. Обьясните пожалуйста, если будет время)

получилось?
