### ISSUE TITLE
Add [sokmil] support

### ISSUE THREAD

**Issue by jerryandtom007** [medvm/widevine_keys#12]
Hello,
I’m not sure what data you need. If needed, I can send you sokmil’s account. This is an adult website.

MPD : https://idc104.candl.jp/watch/?a=c2LsAlPLnq31XHDCHmI7s1-beZV.LcFGar0zaZDoq0E&h=104&f=ing0342_00_2m.vismv&style.mpd
License : https://license.candl.jp/sokmil/widevine/
Pssh : AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISEB8tbK4Y1U3wpJ/wf7eklJ8=
![000333](https://user-images.githubusercontent.com/82229999/145689115-7e5c12c2-484d-425f-8dde-379e58c4ebba.jpg)
![11996600](https://user-images.githubusercontent.com/82229999/145689117-780b00c5-a576-4dd7-99ab-bbca36d41db6.jpg)
![990088](https://user-images.githubusercontent.com/82229999/145689118-aae164cc-57e6-4262-9a53-1d3bbbe21ae4.jpg)
`{"status":"OK","status_message":"","license":"CAISogIKOAoQ5hyBygBtzixiPbUsxM32EhIQ5hyBygBtzixiPbUsxM32EhoAIAEoADj9ogVA/aIFSP/t040GEhAIARABGAAg/aIFKP2iBWABGmYSEHRzhgNRLWoakHInQ2LBr+0aUO+Xsly0YsF1TR1O5RO7NLgLn5v0Rk12w/j9qbdQbPmRY7rt4CiTMKT6rSB1USMURi08zrxH08Cf1WdDxLsp8t0RDdSH/6OFVeC1v1OgytTiIAEaYgoQHy1srhjVTfCkn/B/t6SUnxIQ21pZZHj79qKLDTlibr8nshogkxPW9IY7Pxj/oh+BZd3uAJ7TUmUy9DPIysDDegURRgAgAigBQhIKEGtjMTYAAAAAXOUZI4AAAAhiAkhEIP/t040GOABQBRog6UOSomcEXb/h/1d4M67fWpjskrQgYackEKdo8Z4fW9MigAE/Msy4YWGYiFeTXLmc7di9hWYnDpg6pTyJJN2lPDmtgFoNB+WRfPTmmxLE7qcD/tEb6A3K95t8a2VMCPVDHF+g4wIILqa0crNCCbxziX9g4ybi/xibJZNknq1bFSYxIi4eKq9Ki0eMVYsTAw3pOewo8ytp9KY01RPPd3OBzqWChDoyCjAxNi41LjAgQnVpbHQgb24gTm92IDMgMjAyMSAyMTo0MTowMSAoMTYzNjAwMDgzNilAAUqwAQAAAAIAAACwAAUAEFzlGSPwVC9xAAAAUAAAABAAAABiAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAFRfQAAAAAAAVF9AAAAAAAAAAAAAAABAAAAuAAAABAAAADKAAAAEAAAANwAAAAQAAAAAAAAAAAAAAEEAAAAEIs87E+RLDbJ3f4D2g+005VCBUfgzm9kJoC0oJ8zlJShWAE=","license_metadata":{"content_id":"ZXlKaGMzTmxkRWxrSWpvaU1XWXlaRFpqWVdVeE9HUTFOR1JtTUdFME9XWm1NRGRtWWpkaE5EazBPV1lpZlE9PQ==","license_type":"STREAMING","request_type":"NEW"},"supported_tracks":[{"type":"HD","key_id":"Hy1srhjVTfCkn/B/t6SUnw=="}],"make":"Google","model":"ChromeCDM-Win-x64-7","security_level":3,"internal_status":0,"session_state":{"license_id":{"request_id":"5hyBygBtzixiPbUsxM32Eg==","session_id":"5hyBygBtzixiPbUsxM32Eg==","purchase_id":"","type":"STREAMING","version":0,"original_rental_duration_seconds":86397,"original_playback_duration_seconds":86397,"original_start_time_seconds":1639249663},"signing_key":"+vc7ir7rWH1ItVig9lfY9a92SQ7TcV68O2XLu4LaSsANrIebaSMldljwPlGSZLcQokhol4NZuDbMKO/5ag6NuQ==","keybox_system_id":21889,"license_counter":0},"drm_cert_serial_number":"NDY4NWI0OTk3YjI3MmNjNmFkNDUyMGZjYmZiMDNjMGE=","device_whitelist_state":"DEVICE_NOT_WHITELISTED","message_type":"LICENSE","platform":"windows","device_state":"RELEASED","pssh_data":{"key_id":["Hy1srhjVTfCkn/B/t6SUnw=="],"content_id":"ZXlKaGMzTmxkRWxrSWpvaU1XWXlaRFpqWVdVeE9HUTFOR1JtTUdFME9XWm1NRGRtWWpkaE5EazBPV1lpZlE9PQ=="},"client_max_hdcp_version":"HDCP_V1","client_info":[{"name":"architecture_name","value":"x86-64"},{"name":"company_name","value":"Google"},{"name":"model_name","value":"ChromeCDM"},{"name":"platform_name","value":"Windows"},{"name":"widevine_cdm_version","value":"4.10.2391.0"}],"platform_verification_status":"PLATFORM_SECURE_STORAGE_SOFTWARE_VERIFIED","content_owner":"castlabs","content_provider":"castlabs","system_id":21889,"oem_crypto_api_version":16,"resource_rating_tier":0,"service_version_info":{"license_sdk_version":"16.5.0 Built on Nov 3 2021 21:41:01 (1636000836)","license_service_version":"widevine_license_wls_20211103_212427-RC00"},"soc":"x64","client_capabilities":{"session_token":true,"video_resolution_constraints":true,"supported_key_type":[]}}`

**Comment by medvm** [comment]
type method:POST in network filter and take screenshot again

**Comment by jerryandtom007** [comment]
> type method:POST in network filter and take screenshot again

Did I do something wrong? Blank?
![000](https://user-images.githubusercontent.com/82229999/145691023-0b3cd596-5474-4876-a19a-1ef3613e4c33.jpg)

**Comment by jerryandtom007** [comment]
![1](https://user-images.githubusercontent.com/82229999/145691402-39f5f3d5-641b-48c5-8c4e-eb98b56fb996.jpg)

**Comment by medvm** [comment]
"method:POST" paste whole

**Comment by jerryandtom007** [comment]
![01](https://user-images.githubusercontent.com/82229999/145691530-5f40f5b8-1474-4a4a-90c0-b7dc2c775211.jpg)
![02](https://user-images.githubusercontent.com/82229999/145691532-2df18c73-520d-4198-83a4-2d8173a13cfa.jpg)

**Comment by jerryandtom007** [comment]
`{"status":"OK","status_message":"","license":"CAISogIKOAoQF+Fpz/x6hZOVlJtmh86UxxIQF+Fpz/x6hZOVlJtmh86UxxoAIAEoADj+ogVA/qIFSIKf1I0GEhAIARABGAAg/qIFKP6iBWABGmYSEKCb2zMeOL4ArdjnFzm2ug4aUCcYLDWHeJNOEHkcEUDCVIZC3RV6AX/I/8k33idn6avXb1aExF5bmXF1JWS4FN8CqJomQZRkBX/LuXMpCTIo/m/and8ZYlojEqacBU7gpbZMIAEaYgoQHy1srhjVTfCkn/B/t6SUnxIQUuVqCpNFbM9Bzu/HEKJb+BogOrnzLKMtsvCAqve4ASHAEgyhJkdlKFis1KvalI2P1D0gAigBQhIKEGtjMTYAAAAAMNokY4AAAAhiAkhEIIKf1I0GOABQBRoghNNlDbg2G8gwYKZBc2SX1Omq/r7ZrCyuiHAXurwSfQ8igAGUiGrUCs7GrpgsGaLTgbhaH8Hvda1qE4ewoEFBKh/+NX9EQ0W6sku0/SIfxB/O0nkUF7HD7jKNcImsZQ7gKxYenHuH6DNEMpzaaUkrMQPI2TEdQIm056v/YgkyxnOHDldSrnF3IkPlOUNkBHtvigPBRYcWItLD8pRAsU+731K04DoyCjAxNi41LjAgQnVpbHQgb24gTm92IDMgMjAyMSAyMTo0MTowMSAoMTYzNjAwMDgzNilAAUqwAQAAAAIAAACwAAUAEDDaJGNew0svAAAAUAAAABAAAABiAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAFRfgAAAAAAAVF+AAAAAAAAAAAAAAABAAAAuAAAABAAAADKAAAAEAAAANwAAAAQAAAAAAAAAAAAAAEEAAAAECaOvFMzSC4Ud6FWAyO3Oqbbr4dSuH9oeerALGHrgLGcWAE=","license_metadata":{"content_id":"ZXlKaGMzTmxkRWxrSWpvaU1XWXlaRFpqWVdVeE9HUTFOR1JtTUdFME9XWm1NRGRtWWpkaE5EazBPV1lpZlE9PQ==","license_type":"STREAMING","request_type":"NEW"},"supported_tracks":[{"type":"HD","key_id":"Hy1srhjVTfCkn/B/t6SUnw=="}],"make":"Google","model":"ChromeCDM-Win-x64-7","security_level":3,"internal_status":0,"session_state":{"license_id":{"request_id":"F+Fpz/x6hZOVlJtmh86Uxw==","session_id":"F+Fpz/x6hZOVlJtmh86Uxw==","purchase_id":"","type":"STREAMING","version":0,"original_rental_duration_seconds":86398,"original_playback_duration_seconds":86398,"original_start_time_seconds":1639255938},"signing_key":"KXXSexk2jAq5a81rf3pF+bH4rjq39Uh+G5ZFAJyDZ9oGeNd0d9IohH3XTA58lGPYe2Jcpp3W7H1gqTjqVsZ2AA==","keybox_system_id":21889,"license_counter":0},"drm_cert_serial_number":"NDY4NWI0OTk3YjI3MmNjNmFkNDUyMGZjYmZiMDNjMGE=","device_whitelist_state":"DEVICE_NOT_WHITELISTED","message_type":"LICENSE","platform":"windows","device_state":"RELEASED","pssh_data":{"key_id":["Hy1srhjVTfCkn/B/t6SUnw=="],"content_id":"ZXlKaGMzTmxkRWxrSWpvaU1XWXlaRFpqWVdVeE9HUTFOR1JtTUdFME9XWm1NRGRtWWpkaE5EazBPV1lpZlE9PQ=="},"client_max_hdcp_version":"HDCP_V1","client_info":[{"name":"architecture_name","value":"x86-64"},{"name":"company_name","value":"Google"},{"name":"model_name","value":"ChromeCDM"},{"name":"platform_name","value":"Windows"},{"name":"widevine_cdm_version","value":"4.10.2391.0"}],"platform_verification_status":"PLATFORM_SECURE_STORAGE_SOFTWARE_VERIFIED","content_owner":"castlabs","content_provider":"castlabs","system_id":21889,"oem_crypto_api_version":16,"resource_rating_tier":0,"service_version_info":{"license_sdk_version":"16.5.0 Built on Nov 3 2021 21:41:01 (1636000836)","license_service_version":"widevine_license_wls_20211103_212427-RC00"},"soc":"x64","client_capabilities":{"session_token":true,"video_resolution_constraints":true,"supported_key_type":[]}}`

**Comment by medvm** [comment]
so many additional parameters...

**Comment by jerryandtom007** [comment]
> so many additional parameters...

It looks like a lot of work, it’s not necessary. It’s great that you can add support when you have time. It doesn't matter. LOL

**Comment by medvm** [comment]
These kinds of sites are not a priority, you know. Maybe one day...
