### ISSUE TITLE
l3.py doesnt finish

### ISSUE THREAD

**Issue by kfriddy** [medvm/widevine_keys#13]
I'm no expert in this so I may make a beginners mistake. I tried your project on channel 4 and get the main script doesnt finish. After entering the license URL it waits forever - interrupting at some point results in the following traceback.

![Screenshot from 2021-12-11 20-28-45](https://user-images.githubusercontent.com/95981178/145689150-d6afba37-d8a4-4a13-9330-1c4178dc51dd.png)

I'm unsure about the URLs are correct and the chosen header is the right one. From DevTools I got this for the header and license URL:

![Screenshot from 2021-12-11 20-25-54](https://user-images.githubusercontent.com/95981178/145689182-45120c1c-3d7f-4df5-a6f2-e2a02641b2e1.png)

and this for the MPD URL:

![Screenshot from 2021-12-11 20-26-15](https://user-images.githubusercontent.com/95981178/145689208-b114fcae-1a9f-4cdd-9666-52b664a46858.png)

I hope someone knows what the issue could be.

**Comment by kfriddy** [comment]
I just waited for even longer now and got the following tracebacks

![Screenshot from 2021-12-11 20-32-09](https://user-images.githubusercontent.com/95981178/145689242-e9c7e485-ef96-4647-91b6-03d230985029.png)

**Comment by medvm** [comment]
I don't know how to fix this kind of problem...
try to ping both domains

**Comment by kfriddy** [comment]
Turned out to work now (pssh issue) - using a different URL helped

**Comment by Lusephur** [comment]
@kfriddy what info did you obtain to get Channel4 working? mpd and license url obviously are a given, but what else did you use to get things working?

**Comment by kfriddy** [comment]
> @kfriddy what info did you obtain to get Channel4 working? mpd and license url obviously are a given, but what else did you use to get things working?

I just made the error from the beginning work. The issue is the payload that are some hashes - it doesnt work so far

**Comment by Lusephur** [comment]
Trying to feel around the page setup for the required info is a tad frustrating. I'm not sure what it is that C4 are doing. But then again, I'm sure that's the point of it all from their perspective.

**Comment by kfriddy** [comment]
> Trying to feel around the page setup for the required info is a tad frustrating. I'm not sure what it is that C4 are doing. But then again, I'm sure that's the point of it all from their perspective.

Yeah, some of the jumble seems to be fixed and some seems to depend on the show. Just giving the payload as its in the cUrl doesnt work, so some session stuff needs to be included

**Comment by Lusephur** [comment]
And if you notice the readme on the front page, this script no longer works. Will shifting around the C4 webpage structure be of any help, it's hard to say at present.
