### ISSUE TITLE
python version?!

### ISSUE THREAD

**Issue by hossamnoaman153** [medvm/widevine_keys#14]
Hello,

Can you mention in requirements txt file which python version needed?!

`python l3.py
  File "l3.py", line 33
    print(f'{chr(10)}PSSH obtained.\n{pssh}')
                                           ^
SyntaxError: invalid syntax`

Thanks

**Comment by medvm** [comment]
3.8.3 or above

**Comment by hossamnoaman153** [comment]
> 3.8.3 or above
python 3.8.10 here 

/usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
Traceback (most recent call last):
  File "/usr/bin/py", line 167, in <module>
    result = eval(args.expression)
  File "<string>", line 1, in <module>
    l3.py
NameError: name 'l3' is not defined

**Comment by medvm** [comment]
try 
`
py -m pip install --upgrade pip
pip install -r requirements.txt
py l3.py
`

**Comment by hossamnoaman153** [comment]
> 

same problem
it's conflicting with python 3.8.10

**Comment by medvm** [comment]
I just checked it, it works great on versions 3.8 and 3.10.

**Comment by hossamnoaman153** [comment]
solved
system problem
