### ISSUE TITLE
Add  support

### ISSUE THREAD

**Issue by oOBigManOo** [medvm/widevine_keys#15]
`https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEuNjM5MjYwNjk4RTksImRybVRva2VuSW5mbyI6eyJleHAiOiIyMDIxLTEyLTExVDIyOjExOjM4LjAwMDE4NyIsImtpZCI6WyIqIl0sInAiOnsicGVycyI6ZmFsc2UsImVkIjoiMjAyMS0xMi0xMVQyMjoxMTozOC4wMDAxODciLCJleGMiOnsiRmFpcnBsYXlSZW50YWxEdXJhdGlvblNlY29uZHMiOjg2MDAwLCJGYWlycGxheUxlYXNlRHVyYXRpb25TZWNvbmRzIjo4NjAwMH19fX0.pm6Epyx3EodJ0wOGNzVFvoyNx8XTytW8wET83Qah6L0`

it's headers :-
`POST /acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEuNjM5MjYwNjk4RTksImRybVRva2VuSW5mbyI6eyJleHAiOiIyMDIxLTEyLTExVDIyOjExOjM4LjAwMDE4NyIsImtpZCI6WyIqIl0sInAiOnsicGVycyI6ZmFsc2UsImVkIjoiMjAyMS0xMi0xMVQyMjoxMTozOC4wMDAxODciLCJleGMiOnsiRmFpcnBsYXlSZW50YWxEdXJhdGlvblNlY29uZHMiOjg2MDAwLCJGYWlycGxheUxlYXNlRHVyYXRpb25TZWNvbmRzIjo4NjAwMH19fX0.pm6Epyx3EodJ0wOGNzVFvoyNx8XTytW8wET83Qah6L0 HTTP/1.1
Host: drm.cloud.insysvt.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://shahid.mbc.net/
Origin: https://shahid.mbc.net
Content-Length: 1714
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site`

mpd url :-
`https://cdxaws-ak.akamaized.net/out/v1/ebbafa7f0d1944d78648ba373ecda6fa/c96d37fedb44465f8a19c65563004303/2702b4dd304c43e88bcfa4f04f464736/manifest.mpd?aws.manifestfilter=video_height:144-1080`

**Comment by oOBigManOo** [comment]
I gave it pssh manually but got `license response status: <Response [500]>`

**Comment by medvm** [comment]
what is "copy as curl" output?

**Comment by oOBigManOo** [comment]
> what is "copy as curl" output?

`curl 'https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEuNjM5MjYyMjczRTksImRybVRva2VuSW5mbyI6eyJleHAiOiIyMDIxLTEyLTExVDIyOjM3OjUzLjAwMDQ1NCIsImtpZCI6WyIqIl0sInAiOnsicGVycyI6ZmFsc2UsImVkIjoiMjAyMS0xMi0xMVQyMjozNzo1My4wMDA0NTQiLCJleGMiOnsiRmFpcnBsYXlSZW50YWxEdXJhdGlvblNlY29uZHMiOjg2MDAwLCJGYWlycGxheUxlYXNlRHVyYXRpb25TZWNvbmRzIjo4NjAwMH19fX0.Cn9r3dqOy5DERUoFS_XO6W6zlekp1_ZgDoTMWuqyR0U' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://shahid.mbc.net/' -H 'Origin: https://shahid.mbc.net' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'TE: trailers' --data-raw $'\x08\x01\x12\x94\x0c\n\xa0\x0b\x08\x01\x12\x84\n\n\xc4\x02\x08\x02\x12\x111\xe7\x07\xe8\x9e\x9f(\x1c)\xeb\xd7z\xef\xf0\xd9t\n\x18\x84\x9b\xeb\x88\x06"\x8c\x010\x81\x89\x02\x81\x81\x00\xc8\x00(\xede\x19\x1b\xf4\x0f\xb2}Si\xcd\x9d5\0414\xaaD\xfc\xc7b~}\xa5\x9b\xe7KQ\xe9:P\x90\xdc\xaf\xc4\x1e\xa7ME\xadK\xc6\xf1\xf4\x07_\xa1A\xac(?;\xf6p\xf9B\x9b[VU\xed\xd2\x82\xd7\x7fmU\x08\xf8I#\xc4\xe7\xb1Z\xf4\xb1\xa4>p\xcc\xd4\x89\xba0\x07j3\x06\x9f\x0fi\x9eg(\xe3h\x89\xdd\x99\x14M\x05)2\x97\xbdxK\x1d\xdb\x0b\x94u\\GQtA\x9d\xa6G\xc1S\x7f\x07\x02\x03\x01\x00\x01(\xfc\xaa\x01H\x01Z\x91\x01\n\x8c\x010\x81\x89\x02\x81\x81\x00\xa6t\x01\xc0\xe1\x08"\xf8j(X\xe1\xae\xb3\xb7\x81\x02\x84\x9c\xfb\xe4\xe2\xff\xaez\x1cl\x9es;\x0f\x17\xe3\xec\x1b\xc6N\x09\x1c5\'\x0e\x1f\xce\xad*\xe8\xd7\xb9\xa4\xa0ws\xdf\x18@\x99\041W\\z\xa1\xeb\xfa\x17y\xee\xa2Nxu\xb5i9\xb4&j\x0c\x8d\xcd\xba\xb2\xadP\x87\xca\x00\xb0\xef\xf2H\x88\x8d\xb5\xff\x00\x02/\xeb\xeb\xd8\xac\xfb\xabN\xc6\xb2C\xa6\x9f~%\xdc9\x1cx\xa9\xc5\xe9\xfc\x00\xf3\xc4,\x87?o\x87\x02\x03\x01\x00\x01\x10\x01\x12\x80\x02\x94>\x14\xa5a\x08[\x1b\x0e\xb32\xf8\xaf\xcc \x07|\x11\xe5\x15\xed\xd9d\xf1\xaeH\xb2\xeblo\xb5\xc0:\x04\xd0\x01y\x0c,\xbc`\xfd\x1d\xa5\x15cI\xd8{\xcb\x04F\x1c\xdb|\x8b<\xbb_\x89\xaf\xec\xd1x\xb9Rm\nN\xdf\xda\xea\xdf\xaah\xca0\x8c\xdc\041\xa3\x0e\xae\xae6r:\x92a\xeb\x0f\xedn@\x01\x84-\xaf\xcc\xd0xc\x05\xbc\xe1h\x1f\xe7H>\x9a7xa\xa1\xb2=\xef\x16\xb0\x0f\x03aQ\xeb2gd-^\x03\xb1>\n\x9c\xb4\xffA?*\x89\x89\xf1\xfc\xf3\xb2#\x0b:k\x08,\x18b2\xd9\xd1\xdb\xda\xeeS\xd5\xe9\x9d\x1b\xdc\xe9\x08\x13c\xc0,\xef\xbe\x1c_\xc4\xe3\x8a?:\xe5\xfe\xf2XB\xe1\x00RAr\xab\x90\xdc\xa6JTS\x11N\xb3\xcb,\xb5\x1eq\r\xc9r&l\x90}\x0e\x846%\xb7\x96\x1b\xc6\xcb\xebE\x1b\x0c\xde]?\xbc\xe9e4\xf1\xf8\xe8F?\xa8L\xc4\xaeZ\n\xfd\xb7\xda\x93\x83\x8b\xcc\x14j\xab\x8fr\x1a\xb7\x05\n\xb1\x02\x08\x01\x12\x10R\xd7\xbc\xd1\x98PSF\xbd<\xdcJ\x93\xe4\xe2\xae\x18\x8d\xdb\x80\x82\x06"\x8e\x020\x82\x01\n\x02\x82\x01\x01\x00\x9bW$g\xb3v\xe0\xc6\x06,\xb6$\x1e")\xf1\xe3\x12q6.\xd2\xb9\xd4i{\xac}\xdfP\x18:\x12\x14(\xe95M~v\x17b{\xc9H\041]\\ \xa7#\\\xeb\xdf\xcf\x15\xb2\xe4z\x06\xba\x10\x01&1\x92\xc0\x82\n\xbb\xf1\\l\x9b\xd4zT\x0e\x9b>|&\x9b\x08\x06\x93\xb9\xa1o\xcd}\x94\xf3qO\x1e\x94IiK8\\[Ef\x99\xf5\xa6\xf6\xb8+]\xfa\xdf\x18\xb9\x14\xfei\x00\xa9\xbd\xe1\xf2$\xe0\xb7\x8c|M]\xea\xb2\xc5m\xc2a\xde\x98\xa8\x9e\xb9s\x1d\x05\'e\x97f\xb3uM\xc8\xa3Tg\xf7F\xfa\x1b1\xa1\x0f\xe0y]\xbc\xe0\x92K\x16\x9ak\xd6^\xd7\xbc\x15j%(/g\xc0SU\x8c\x8c\x97\x82\x8aF4\x920\xab(~\xc2\041\xec\x19\xed\xa7\xb6\x11\xef\xcb\x0b\x8fCI\x1e&\xed\x00^\x04\xc9U\xd0Jsu\x89\xd4a\x13?\x9eW7}{}\xa4[\xd0\x97\x14\xb3\xe9D$\xc8\xf5\x172\x88b\x0f:\xe8\x01\xc6\xd1\x02\x03\x01\x00\x01(\xfc\xaa\x01H\x01\x12\x80\x03\xa1`\x98)`8\x9b\xcc70b\xbe\xf7\x98\x13>\xe0\xac\xb2\xcc^\xbb\x1f\x11t9\xb5\x1b/5\x8c\x81\xb1#b\xb7\xc6TMz\xa8\x10\xd5\xf4\x9b\x90\xa2\xfdy%\xd2\x94\xd6\xd0\x89\xcb\x92\x1cl\x8aI\x80\x9b\xa5\xceMu\xe2\xf7X\xf6\xb5~4\x9f\xc3*\xa2\xfeE\r\xcfH\x04\x93\xc5\xbc+\xe3\xa3;\x08\x7fy\x8d\xf6\x94\xb0\x8c\x8a]\x81\xd9*\x81\xebF^\x93\xea\x9f\xb4\x19\x9d\xa8\xce\x88\xe3\x87Bc\xf3\xb1\x02a\x92\xc1\xd1E\x9a\\\x0e1\x94"\xb9\xbc6\xfb\x8cbE\xde\x90\xea\xdczR\xdf\xe6\xad\xd3\xfb\xc8:\xb0V\xcbPL\xae\nQ\xa7\xf2\xa97\x84\x01\x9aOH\r\x9cd\x96\xf9\x8b\x12@\x8d\x8aSPi\x93\xa5zi5\x9aH\xaa\x94\xe2\xf6\xaa\xcb\xe2\xafM\xf6\xfb\x1d\x8e\xa6\xc5\x82Q\xfe\xe3\xec\xb7\xe85\xee3X\xeb\xafv~A\x96\xa2\xf2\x80\xec\xbc\x19C\x14\x91n\x85\x16\x89\r,\xbe\xd5\x09\xc9\x8d\x05_\xf5+Y^qO\xc3f\x9d\n\xf1\xe9\x82\xc0V~\xb5\xff\x05\x08\x10O\x0f\xec\xdd:3L2[E7\x11\xd9\xd7\x95\xd7\xad\x83\xaaF\'\xdb\xe5\xf2\xc5\xf5\xf5E\xee<\x86\xdf\xb7\xfd\xcd\xdd\xdf\x07\xce\xd6\x0bD\xb8\xcf9\xf3\x93z\xa6\x80\xfb\041\xd560\xd4\xa7\xbf\xa3\x02\'~\x938\xf1S\xe2\x85G)M&\x82@N\x9d#T\xeco\xc8\xa9\xefWR\xb1P\x18\xaf\xcd`NZ\xc1\x8d`\xd30\xb1\x9dL\x1de\xae\xb9\x10\x00\xbe\x0f\x1c\x93I\xacV\xde\xe4D\x1a\x1b\n\x11architecture_name\x12\x06x86-64\x1a\x16\n\x0ccompany_name\x12\x06Google\x1a\x17\n\nmodel_name\x12\x09ChromeCDM\x1a\x16\n\rplatform_name\x12\x05Linux\x1a#\n\x14widevine_cdm_version\x12\x0b4.10.2391.02\n\x08\x00\x10\x00\x18\x01 \x00(\x10\x12_\n]\nG\x08\x01\x12\x10\x97I\x88\x84\xec`MQ\xaf\x09cq\xed\xab9\x87\x1a\x05insys"$97498884-ec60-4d51-af09-6371edab3987*\x02SD2\x00\x10\x01\x1a\x10\xaf4\xd2\x9c\x194g\x0e\xbf\xb4\xdb\xa4pR\xdc\xc6\x18\x01 \x9a\xce\xd4\x8d\x060\x158\xea\xc0\xb3\xd0\x08\x1a\x80\x01-\x0ct\x15\x10\xb7\xcc\xf8\x1b\x9a\xc7Qq\xb1\x93\r\x10e}ReHj\xd9\x0b&\x80\xc7{L\xe4q(e\xb1\x8a%\x19K\x04\x9a\xc1\x9d\xbf\xeeMj\xda<\xee\xdf\xba\xc1\xd6<\x82f\xf5p7\xa9\xd7o\x02\xe4\x06)\xf3\xce\x9b\xfd\xa0s\x96\x8e\xf4y}%\x15\x9dw;\x17d\xe0zZ\x8e\xf7\x9a??\xe9\x86\xf3\xd2\x9c\xad\x9c\xb5\xf64\x9b\xebm;\x8e\x7f\x98\x14\xe8 \xb2\x97\x9a\x06\x88\xf7\xd7&\xa7\x86m\x88\xc2\x0b\xd8J\x14\x00\x00\x00\x01\x00\x00\x00\x14\x00\x05\x00\x10\x8a\x0c\xe0j\xed\x89\x17\x86'`

**Comment by medvm** [comment]
ok, paste pssh you found here (for test)

**Comment by oOBigManOo** [comment]
> ok, paste pssh you found here (for test)

AAAAZ3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAEcIARIQl0mIhOxgTVGvCWNx7as5hxoFaW5zeXMiJDk3NDk4ODg0LWVjNjAtNGQ1MS1hZjA5LTYzNzFlZGFiMzk4NyoCU0QyAA==

**Comment by oOBigManOo** [comment]
After some retries

`license response status: <Response [200]>

Traceback (most recent call last):
  File "l3.py", line 102, in WV_Function
    if widevine_license.content.find('{'):
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "l3.py", line 121, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "l3.py", line 107, in WV_Function
    license_b64 = json.loads(widevine_license.content.decode())[key]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 3: invalid continuation byte
`

**Comment by oOBigManOo** [comment]
license post response 

`CAISrgIKOQoQZNnow/sjhq6rAFF0eaUxbRIQZNnow/sjhq6rAFF0eaUxbRoAIAEoADiAmp4BQID1JEj/7dWNBhIYCAEQABgBIICangEogPUkMID1JDiA54QPGmYSEHuk0OweoCIXeil4jkW63BcaUOwEzr+4f4xPdSFNo1A6YkKa6Z3dV8ipeRnX15g3utpS3cfq3w1K38yrxF0AShcGh022e8Q7FJfeD7OF70/khmZh5UvKVy4HXcjumBKLf6LXIAEaZQoQ2xOLIrF3ToezE1dYWyWoCxIQJMV/rXDamRvPPqJiUIqKuRog7jK7V04RK9gJAQPKpo/BgUq9UeHBvBPPwe9P2VAWYQIgAigBQhIKEGtjMTYACTqAtx9ojYAAAAhiBVNEX0hEIP/t1Y0GOABQABoguNRsEAcCFvZQlVltPqO9lcPAGYKO6VyLsl8wlsZPA4QigAEzkrhRZr6m+eEo5HHrWbZOl3fdwigH0Y5H3tRwkRA5RSOwYg7OqZcCImYV5KgpO21NxQ1WlYcvK8BtBPehX8AJHIEtBNG2fLmMi6FFD0OqoRlx2wG+hCAsOfjSrZGIhMWHvz1ubyFDgA7dxF+QLhbN80lOjnIXjCUKvF4reJDvhzoyCjAxNi41LjAgQnVpbHQgb24gTm92IDMgMjAyMSAyMTo0MTowMSAoMTYzNjAwMDgzNilAAUqwAQAAAAIAAACwAAUAELcfaI1Tu24RAAAAWQAAABAAAABrAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAACeNAAAAAAAACTqAAAAAAAHhM4AAAAABAAAAwQAAABAAAADTAAAAEAAAAOUAAAAQAAAAAAAAAAAAAAENAAAAEPFNdaWcFPi7c5COBU6Hn2z2JOFR8hA8aH+5gy5ypXYvWAE=`
