### ISSUE TITLE
Add [wink] support

### ISSUE THREAD

**Issue by Joker179250** [medvm/widevine_keys#17]
MPD: https://s35761.cdn.ngenix.net/mdrm/hd_2021_korolevskaya_igra__ar6_xTRh8rJezTb_film/9eff5806/manifest.mpd?profile=web_auto
License URL: https://s95951.cdn.ngenix.net/license
PSSH: AAAAYXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAEEIARIQSa2Www42TAW6Xwz5oOEEthoFQ29uYXgiJGEyMmEzYjE5LWQwZjYtNDRjMC05Y2NhLTM4Y2JiOWI1OGU4Nw==
[Screenshot](https://c.radikal.ru/c23/2112/44/413abdf45335.jpg)

**Comment by medvm** [comment]
Скиньте еще вывод команды "копировать как curl"

**Comment by Joker179250** [comment]
import requests

headers = {
    'authority': 's95951.cdn.ngenix.net',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
    'preauthorization': 'eyJleHAiOjE2MzkzNTM5ODI5MjEsImFsZyI6IkhTMjU2Iiwia2lkIjoiNGJhOWRlNWItZGJiMS00Yjk5LWFmZjAtNmYwNDllMGVhM2FhIn0.eyJtb2RlIjoiU1RSRUFNSU5HIiwic2NvcGUiOiJsaWNBdXRoIiwiZXhwIjoxNjM5MzUzOTgyLCJvcGVyYXRvcklkIjoiMzA5NCIsImp0aSI6IjMyMzYxRjNCOThENTg5OUVCQjk5OThFRDk3NjFEQTczIiwiY29udGVudFJlZiI6ImEyMmEzYjE5LWQwZjYtNDRjMC05Y2NhLTM4Y2JiOWI1OGU4NyIsImxpY2Vuc2VEdXJhdGlvbiI6IlBUMjRIIn0.esOWd2pH_zE6We_8dvoxGUfb4BAR-5UbHnfaxc6YJH0',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (Linux armv9; U; ru;) AppleWebKit/537.17 (Arcelik;KP;08.005.03;) CE-HTML/1.0 NETRANGEMMH HbbTV/1.2.1 (MWB;Arcelik_Gen3;RC_V2;Arcelik;KP;KPGRMR.-.-.-.-.V08.005.03;ru-RU;wireless;prod;)',
    'sec-ch-ua-platform': '"Windows"',
    'accept': '*/*',
    'origin': 'https://wink.rt.ru',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://wink.rt.ru/',
    'accept-language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
}

data = {
  '\b\x01\x12\xB3 \x12Y\nW\nA\b\x01\x12\x10I\xAD\x96\xC3\x0E6L\x05\xBA_\f\xF9\xA0\xE1\x04\xB6\x1A\x05Conax"$a22a3b19-d0f6-44c0-9cca-38cbb9b58e87\x10\x01\x1A\x10S\xB1\xD3\xC2$\xA1\xC5@\f\x81)\xCB.\xEB\x8C\xA1\x18\x01 \xC5\x9C\xDA\x8D\x060\x158\xEF\xE0\xB7\xBD\x06B\xC5\x1F\n\tconax.com\x12\x10\x94s\x1B\xCE\x0F\xE3V"\xA8Rs\xD5\x9Ep\x07\xF5\x1A\x90\x1D\x85[\x8A\x8A\x99': '',
  '\x13\xFA\xD2\x8FW{\xDD\x1F\xF9n(\xE4nv`\x88\xA8\xD21\x84WD\x05\xB3\xBC\xCF\x8Ak(\xC2\xB7\xFEV\\\x1C\x9D\x80\xE4a\x9CA;\x9B\xF5\x02\xDFa\xC4*\xD0\xF56\xF5o\xDB1 W\xBA\x9B\x1B\x9479%f\xAB\x8E:\xCAHG\xC0\x07A@\x11]WwJ\xB6\r\x1078\xC3\xA1\xB1\xDA\x14\xFE@\'\x85q\xFC\xC3\xAD\xBF\xBB\xC0]\xB1\x03$\xF7\xCD\xF84Q\x96"C\x03\xC8\xF9F\xD1\xB2fi\x8A\x95\xDF\xE9\xFB\xA0\f\x9D\x1B\x9D\x16v\x89W\xFA.,M\xCC\xE7\ft\x1C]Zd\xCC\x06\xBBf\xE0\x16we\xC9\x18P\x83\xAF\x9E_\xE4\x84\xC1\xE8': '',
  '\xC7\xAA\x1E;\xFF\x1C/\x9A\xDF\r\x9A\x0F\xC3\xE8\x84*\x17\xA8w\x90\xF2\x06L\x12\x03\xA0\xB7\x9Fk\x12\x94K\x87j[\xCE\xCC\xF8\x8D\xDB\xCC\xD5\xF0?\x92\x87\xAD\x8E\xFA\x87zkH\f\xB3?\x1D\xF4\xCE\x12\x9C@\x7F\xE3J\x18\x86\xE7\xD5\xB6G\x848t`\xEB\x19\xAD\xADjz\x1E7\xCBjC\x9AF\xCE\xA9\xD3Q\x8A\x13\xDF\x8F\x01\xF3,8\xE1\x15\xD2\xB7\x81\x97\xE4\x95\x02\xB7\xE6\\\xA4\\G49\xE7\x9D|\xD7_}BA\xA41aH\xC5#X\x8A\xF7VS\\\xA1\xB8\xE2\x8E\x19\x9DI\xD4\xE4j\xC6\xA3\x1Bg\x91_\0x\x03\xA0\n\t\xC4\x89.k\xB7\xB5\xFBt\xD5\x95*\xF6\xA0\xFA\xCB\xA0\xF9\x1Ev\xA3\xC1\0z9\xF5\xD4_\xD8,b7t\xB45\xBA2T\xE2Z%\x04\xEE\xDF\xEEq\x96\xB8\xF0\xEA\f\x18V\x85}N\x1Fi\xED\xBA\xA9\x91\x0BK\xD3}-\xD5\xE2\xEB\xA8\xD8\xA3\xCD|-5\xD3\xA1\xAA\x96 \xAE\x89v\x0F\xF1\xED \xA7\x06\xB8\xD2\xC7%\x8A\xE5\xA7\x07Z-@\x9A9\t\xF2o\xD0m': '\x9E[\x7F|c\x82\x97\xDB<\xC5\0\xADnR\x90\xBF\xEA\x9D\x1B\xB8H\xA9\xF08i\xCA^\x9Fm\xE4\x83\x1C]\xA3t\x01 \x8A@\xC8\x89\xA1l[\xA4\x1B\xF5\x1E\x11\xAF\xE6\x0F\xBF\xC9\x81\xD1\xA6T\xCC\x97\x95\x18\xAB#\x91lM\x96\x93}%\xAFG\x04W{\xCC\xEDL"HM\x8Br\xF2T\xCBY\xFF\xABA\xF9Ct`\x0B\x9C"9\xF0\x89\x18\xEA\x8F\x90=\xF6\'\xD3\x82A`\xC1\xB8\xCA\xFFy\x1A\x86U\xBF\xEB\xFC\x9FM\x936\xDFH\x98\x7F\xE29*/U#S\xF8\x9D\x8E\xC2\x07\xBC\t-\x98]\x8E\xE1\xEC\t1\xE7\xD9(\x82\x87\xC9\n\xEE\xB8\x06r\x91',
  '0\xE2\xBEx\xC6\xF6\x8Fq\xFD\xF50\xDAi\x07~\x7F\xAD)Wp\x19\xFA\x9B\f\xDF\x8EU\x15\xD5\xA9\xF7\x88\x88\x94\xF3\x8FW\xE5\xB1\x83jb~Vf\x94\xB0\xA3\xB7\x02\xE8vj\xC7r}T\x15\xD2\xB9J 8\xF8\xC8\x85\x13\xF7\x96\x05P\x9C\xC1\x80u\x96LP{\x96`\x8A\xC5ho\xB1\x14x\xBE\xB0\xE0\x1Cn_\xCC\x97\xF5\x92F?\xDB\x8E\xB9\x87@}L\x7F\xC2\xD92\xE1\':to\xC5\x88\0\x94\x9A': '',
  '\xE5\xA8]\x03\x98\x9E\xCA\xAA\xC7[B\x9A\xB4\x91\xD5 \xC2Bt. \xB8\xC9\x82Z\x8B\x84b\xC6^6\x02\xF4\xBD\xFA\xCFp\xBC\xB2%\x06\xC4\x05\x98e\xAAA\xD8g\xBB\x872\x94\x96,\xF42\xD1\xBF\x9F\xE4\xC2\xA1p\f\xBA\xB6\t\xBB<\x9A\xFF\x8E\x8B\xC5\xA5\xC9{\xC6\xCA\xDB11S\x17\xCA\x847\xB7m5': '\x8Ch\xDF,\xB5X_\xD6\xF88\xE1\xD7)\x97\xCD\xE5\xF3\x1A\xA9\x13K\xF7.\x12\xA7o\x8BK\x91\xD3\xEB\xEAeau\xF4L\x8A\xF4\x91\x0F\x16s5\x9813p)\x14|"0<=\xEA\x94\xD7\x91l\xFBPY\xF5\xE03U\x88\x9B\xBA\x81V\xBF\xED\x87\xCB\r\xC2:\xEC4$m\xC1\x8C\x82\x1A\x17\xE8\x94$\xC342v\xBEt\xF9\x98\x8D.\tkPq\x80\xCBj\x19\x8Fo~e\nP\xD4\xF5\xFC\x97\xA5\x8AZ{\xC5\x8B\x06W\xA7\x8A P\xB5>M\xFA\x11\xF8\x0F<7a\x9F\xFD\x86U\xE0\xC4T\xD2;\f!!',
  '\xDBO\'C}\x13[\xDD\xB9\x16\xC9\xDE\xFD\xBD\xFEc\xE6\x86$\x85a\xA8\x057^\xB7/J\xF0\xAF\xF6\x99\xC5\x150Q\xB8\xACW3:\x8D\xA9\xFB3': '\xF7\xC36\xCDK\xB4(\xAAE4?8\xFA\x02eT\xFA\xC9}e5O\xEEqs\xCE1\x88\x165\xC9o\xF3\xBD\xA0\x8BT(kVL\x8BPg\xF6\xE4 \x18MY\x8A4\x8D\t\xA0\x0F\x04\x83[\x14\xD8\x92\x91\xDA\xF6\xF3U\xDC\x91c\xC5\x92\xFD%\fg\xA9\xBC\xDC\xE3\xD9\x01\xF9\xFE\x894\xB0\xA5w\xFC\xC7j\x9F\x9B\xFA\x12kY\xAA\xFC\xC6\xB1\x89\x9D4\xBC\xEAQ\x1D\xDC.S\x15\xF5t2\x9E\x9DCc\xF2U^\xF2\x87\xCE\xED%\xF3\xD1 a\xCE\xA6\x90H\xBB\x9Ck\x9B{yoxO\xC6\xF7\x10u\xE3\xB4\xA3E\xD8\xB4\xC7"<\x8E\n2-xg\r\nj\xB6\x8E\xB5\xBA\xB3\x8D\x85[{\xBD\x1D\xF4t2\xDD"',
  '\xE1mI\xBF\x81\xD9jo\xEE\x17\x12\x17\x9F-\\Fn3\xE1\x89\xFBu\xC2\xBFB\x8F\'\x1F\x1F\x89*\xDD@\xF3$\f\xC0\xF9\xC9\xB4\xC6\xFD\0[\x12\xE1\x18b1)\xB4\x93\xCFF\x92G\xD1\xF4$\xEDp\xDF\x1E\x1B\xCD\xA2Y\0\x0Biq\xE89!\x90f\xCB\xD9\x06A\xEC\xA6\xB4\x8F\\\xC1\x86@/@\xC2\x8B\xC8"\xEA\xBD\xA21\xB4(a8\x85\x8Fk#\x04u\xE3\xCDQh*f\xC8q1\xA1\x18r\xC0\xA8Q#7V \xB0\xF1\x1A\xF5\xB8\xB1\n \x0F\xC9@\x1E\0\x11\xF2\xB3 a\xC2\xB5\xBB\xB0\x9C\xB1\xBF\xE6\'\xFA\xF7\x80DX\xFB\xA0\x1CJx\xF5kTe\xA9\xFA\xBB\x9F\xA1\xC7\x8F\x95\x9B\x9EX\xF3\xC6\xCB\x8C|\xB4\xF1\xB3\xE3\xE2': '',
  '\xE6\xC2\x91\x9A/W\xA1\xC0\xD2\x14c_\xAC\x87\xD5\xB5m\xCF\x11k\xF2\t\xEC\xC4j\xB8\xA0\xCE 1\x87\x95\xF7/\x0F\xDD\x94-\xF3B\xD9\xB2\x84hm\x02\x96\xEC\x15c\xA7n\x82Ln9\xC6\x1E\xE1\x88!\xE3\xC5-\xEFQ\xBE\x0F\xD7\x85\xEB\xBA\xBC\xE5\xA8\xE7(\xE4k\x06\xE5\xA1\x9Caa\xE1\x99J\xD7\x16\xB2\t\x03\xC2\x86\x19C\x9E\\\xD3:\xCD\'PCWU\xC1Y\xB5\x11\x03\x02\xBB0\x7Fr\xD4\xA5\xAE\xC7\x16(\xAF\x1D\xCCy\xD6mi\xFC\x84\x7FL\x03f\xD5\n}B\x97\xCE\x1B\xC9\x10Y/\x17~\x88\xD6cJ\xE8Q\x83\xC7>\x8B\xEA\xFAW\x80\xB2\x8E\xCD\xBD\x98k9kE\x04j\xE7A\xDC\xCB\xE9\x19\xE9q\xF9\x1CX\x10\x921\xF4\xDD\x86\x88,4\xF0$T\xF8\xAA\xCF\xBC4x\xF5:\x19\xE1\xAE\t%\x14\x826\x1B%\xE75e\xC8\xCDC\x161\xB4\x90\xEE\x180\xBCF\xD7]\xFB1\xE2\x81\x1DUE\x0E\x05\xC0\x8Ea?\xD9\xD0\r\x99l{\xC0\xF2\xE6\x87\xA9\xAE\xA6(\b\xFF\x91l\xE6\x82\xD3\xDE\xEB\x1Csp\0\x92\xE7\x02\xC3p\x9D]xDX\x99\x1E \xEBkZT\xE4,Fe#\xC7\xB8\x93\xE4\xEC\xB2\xFB^\xE1Y\xD1\xE9tQ\xE3\r\xDB\x89\xA9\0\xEB\x9A\x9C\x15\x16\xB4\x05\x04%\xDE3\xA3|\xB1\xA5,\xB5\x7F\xBC<\x82\xF1*': '',
  '-/?e)\xC3\x16y\x83\x81\r^\xC4\x03%\x03\x9D\xE28\xCE1\x87\xD1\xFF,\x0FJ\xB1Z\xF4|\xED)\x03\xB9d\xEF?\x02\x16\x97^\xFB\xF3\xDD\xA8^\xB6\xCE\xCF\xB5il4A\xD0\xB4n\xB7\xB9\xD5\xF5T\xAFWB\xEE8\x0F \xFA\x03M\t\xF1^\xB9\xB4\xC5\xFA\x8Ag\xCBR\xD6T\x86\xD8\xEF': '',
  '\xDB]\xE1>QT\x8D\x84no\x97o\xD7\xEA\xED\x15\x9D\xA6\xECQ\xDA\x14\x82m\xEE\x99\xC2\x18\xCB\x05\0\xE1r\xFA\xCF\xE0\xC9\xD3Yt\x10\x9E\xFF~Q\x18\xE3\b\xFD\x15c<\xD9\x89\xC0/\xBC\xD1\xEB\x19iCI\xFA\xC9 \x8CCz|]\xF48<%wMI/\xEB\xA4[\xE7\x91\xCF\xD2M\x11e]qX?;\xBBD\x10\x90\xF1b\xB1\b\xBAO\xBC\xA9\xD8U\x84\xF6(\x93\xC7\xA2\xB9\xBCd\xAB\\': '',
  '\x1CdT\x87\xC8Tf\xF4f\x18H\xE3\x82\x93\n\xF5^\xBF">$\x83\x85?\xC5V]B~\xA7\xA6\xD2\x1B3A\x8D \\\x99\xF8\xE9\xEC.f\x1F\x02{M$FyE\x12\x9B\xE8\nX\xF4\xA5iFa\xF6\x91e\x15n\x81\xEF\xEC\xC42\xAB\xBDx@\xE2]\xD5\xB1\xFC\x94Y\xB4\x9B)[B\xFE5L\x9Aq\x14\x8A$\x11\xFFN\xEB\xD9sj\x81\x07\xD2`\xCE\x15\xBEF\x846_\xC2C\r\xA2\xB2 3\f\x15\x0F!\xD5\xFE(%\xCB\xE6\xA4<s\xB2\xDF;\xB8\xF3\x95\xEB`;\xD6\r\xAD\rT\xE5\xC4\xE2\xCC\xD2\x9B\xE5\xEA\0zj2\x9E\x1A\xFE\xF3\x14s\xB0\x1Ahs\x15\xD3\xC8\xCEn\xC2\xFB]\xED?\x0B\xAD\xFD\x91\x1B\xC6D\xA9\xFC\x1E:b\xF5\xF8\xE04>^\xE7\xCF<\xBA\xFAu!\xDC\x80\x1F\xBF"\x06rq\x19@/s|U\x9DK\x8B\xE6\x17\xBF\xD7\x85\xA6:\x97US\xDD\tW[\xA7\xFF\x11\xBE\xEA\xE8\x8A\x8C\x83\xCF\r\x12\xFE\xA4\x82`\xFB\xD8\xBC': '\x19\x01\xD8h\x83\xAC\x93\xDE\x8F\xFD\xC2\x07\xA9\x93$\x9A\x12o\x1E\xCF\x88\xB4\x8B\xE60\x02)\xC1MY\x8ARz\xAEH8\x0BF7\xB6V\x06\x04\xD9\xC6L\x84\x83\x13fi\x95\xB3\x9Fw\x90\xCC\xE8\x90!#\xD8\x80\xA9Vz\x1DF\x87R\xBF\xC1\0?\r>\xF4\xE6_\x8A\x98r\x9F\x19\xD7\x1Bk\xE7\x06\xE3\xEF\xCBiK\xC1\'L\x97\x14\xF0\xA7\x05\xC1\x9D\xDAZ\x9BRO\xEA\xE8l\x10\x8E\\3\x06#\x05\xEF\xA3\xD6 \xC4\xD2<\xA3xr\xB5kn\xC1\xD7\xC5a=\x9A)ZX\xB4\x89\x12\x04<\xEBoz\x88\xE9xb\xC4\xFF\x8BK\x86>\x99\xA1Q\x1D\x99\x88\xB1\x96\xCD\xE00\x92\xA0\x94I\x16\xF7\x13#n{\xB7\x8C\xF2.\x82l\\\xC7\xDC\th\xC5\x8EG\nd\x1A\xA1O\xEE\x90\xBFjGX\x7F\xBC{\x85[\xB8K|3\xD0\xE6\xE6M\x9F\xB8\x83]K\xA9\x8A\xFCJ\xFAu\xA3\xE5\xC1|\xC6\xD0\xF6\xDER}|(\xC6\xA3\xBF\xA2\x18x\fK\xA3\xBA\xEBb\xCB \xE9\x9Fp|\x04\xEE\x0B\xD5\xC6\xE0\xF6\xDC \x9E"\xBB\xE0%UV_\xF3\xF5\nc\xEAd\x1B\x8A\x8B\x15\x8B\x19\x95].;;\xD4Z{.\x8C\xC8\xFF\x8C\x01\xA3w\xAD\xC5c\xAF8\xD6\x01g\x15\xCD9\xCCG\x1E\xDF\x16c\x1B]\xEF\xF0\xE9\x02\xA1}\xF5\xBF\xC9\x07\xB4GR"\xA0,5\xDF\x9E\xB1\x93\x94\x9FE\xB7=\x887\x87W\xB8\xDF/\x05T\xA1v\xC0\rd%\xF46\'t\xC5\xD6\xA34\x9Dq-\xAD{\x8E\xB5X\x1Cc3:\xD3\x9AA\xA2\xE9w\x81\x19Q\x8F\xA8\xE5\xF2\xEE0\xA6HSS\xC8aK|\xFB\xE2`\xB3\xE3\x97n\x1B\xE08\x9A"?r\xA8Fo\xEC\xDE\x97-7\xBF\\!\x1C)',
  '\x90\xDF\x93\x7F`|\xB3\x185\xE9\x95\x07\xC0\x14vxH\x01\xF7g\xC1\xB7\x88cc\x1Ewm\xCE\xC8\x9FRd[J\x92\x81\xE2e%\xE0\x1AH\x85\xAA\xBAy\xB3$kq\xE2\xB8Fqg\xF0B\xF2\xE8\x93\xC4\x9F\x1E \x1D\xA5/\x85x\xDE\x9C\xE9\xEC_\x89_\x9E\xAA\xAAvO9xbe\xF7w\xFA\xC0\xCF\xB4e_\xB1\xABf\x12\xC2t\x02\xCA\x90$Z\xAA\'\xF3\x83\x84\x0E\xAAmK<\xF5\xCDq\xC8\xFBGm\x96\xE6\n\xFB\xB9\xF6\x8C,>e^\xCC6 \xC2\x8Fj;\n\xCF\x16Dx\xA1\x98\x9C\xD4\x1Cf\x92r\x82!dC\xAB\xD1t\xAA\xEF;\xF2\0E]p\x90\x04\xE1\x89LI\xA5\xD6\x8B\xDD\xAC\xA2\xEF\xE37\xD68d\x13s\x12\x8B\x0B\xE9O\x14\x84$\x86\x10\xB4KM>zQ\xFB\\p<(\x94`\x87GD]\x97\rKim[\xF8\x7F\xDAL\x1A\xC4\xC5\x0Bz\xAE\x01\x94j\xF6]\t\xD6\xBE\xF2\xCF\x89\f\xE7\xA2': '',
  '\xDC\xDEb\xA9K\xFC\x11\xD5@\x01\x826\x19\x87c1u\xD1\x84\xF7\x89\xEC\xD5\xA6\x13\xE9\x81G}\x04[\xBF\x98.\x16\xDB\xF5\x05\x19|B-?\xE1\xFD\xFD\x17soe\x91A\xE8\xCE\xE1 \x1D\x7F\x01}\xC5\xC1\xA2{\x14J\x1D\xBD\'b\x85\xA69\x0F^g\x95\xB8\xDC\xB6i\xE9\xDAu~\t\xF5\x15I\x1F\r\x86\xC9U\xE2\xD8\x98\xDB,\x05\xDE\xDEF\x0F\x91\xEF\x8A<\xB5f\xEE5\x12QF\f\x8D9\xEC\xA8\xAE\xF9:L\xDC\x12\x18O\n\xE2\xCD\\B\xC7\xE2EQ\xCC\xB44S\xD7O\x8DN\xED\xA8\x0E\xBD"D\xE9gJ\xDC\x03\x17\xB0\xAC#_\xFD\xF3\xD4?\xC9j\xB3\xB5\xEEH\xD7\xF1\xC53\xC3i\xBB.\xE4\x85\x01\x17\xF23\xB0u\xCC\xBA v\x1AP\xAB\xD76)5\xB7\x1BG*_\x13\xD6B?\x98Dl\xF4b\xC3\x87\xA0>\x1Ep\r\xCE\x94\t\x9B\xD2\xE8\xB5\xF2\x06\xBA5\xDB\xBC%h\xF9 #\xF1E\x02"\xCC{[\xFFPtC\xD6\xF1m\n\xEA\xD6)\xF2g\xC3 \xFB\xD3\xF1\x85d\xE0iC\xF5<M\'\xCB\xCAqb\x1D\xBA\xF6\x0E\f\n\xB4i\x06s\xB9\xEA0\xBD\xCA\xDF\xB6TF\x0By\xF3\xB2E;\xFDp\xF9\xB3\xBDV\xAB/;\x03\x05\x7FO[\xBA\xFE\xA2\xBE\x8F\x17\xF7\x06': '\x19\x8D\xD6\x9E\x12\x9Dx\xE0h \xF3\x0FP^t\x8F$@\x0E\xF5\xBD1!`\x99\xEF3^\xAC`\xF9a\b\xE2\xBD7C\xEAv\x83\xA7\x9F\x07\xF7\xA3\xBB\x01_b\xBA\xB2\x97!5\'C\x03U\xB2\x14\x9D.\xC9\x04\xF2\xAE\xDFw\x11\xB7X\xCFJ\xB7\x87\x82:^\x8Bq;4,\xC5]\xEB]I\xF1K\x14U0[\xFA\x17\t\x05f\x03vg\xD41\xD0\xF4\xE7p\x86\xAC\xD0\xC3Xr2\xED|,\xDD\xD700\xB7CY\xD7;\xB6\xF0\x1D(ye\x8DF\xBB/d;\'r8\xAD[\xDA\x8A4\xAEZ\xE3\xA7\x82L\xD8\xCEU\0\x12\xE2\xEBK\x97\xE71\x84h6\xAEZ>\x89\xE4;\xA6>\xCC\x1C,C\x8D\xAAM\x94\x8E/\x9C\xB3\x89(\x1AZF\xACD\xB5\xEB\xAE\xD1aPW\x1FZZ{Q\x01\xA3\x1E\xB5\xDF\x91\xBA8Z\xD3\x1F\xEA\xCA\x18\nS\x14\x1F\xCE[Oz\xF2u\x83\xE1T\xA1\x92g\xDD\xB7\xA9\xB4\xD6\x17\x0B\xA6f\xFC\xD5\xEF\xDD\xDC\xA1\xDA\xD4\x10\xA6\xF9k\x99\t\x8B6s\x0B\x0E\xF7\x11\x91y\xB6*1HvNU\xC2\xB7g\xD6\xEB`\xCDW\xFA\x98\xD6\x1D\0\xCB\x8D\xF4\xC2\xB8\xFA\xF4BA\xE19\xDA~5K\x95\xC3oq|\x89\xED=\x7F9|\xD1\xFD\xAC\x01\x13\xD7\xC9\x99*\xE6PK\x8DD\xAFRs\xB3\xDD\x03\x9Dab\x89\xB7q\xEF\xDE\x90\xC0hA\x11\xD9/\x83\xC7\xCFOt\xC1\x8E\x14;\x18\xC7f{L\xE0\x9F\xDE\x07\xF1\xCD\f`\x89\x83rvv\xEE7.c\xE3t\xC7\x15\r\0\xD2e\xF89vvuN\x0E\n\xC2\x15\xDDR^\xA1\x8E\xF3^d{Bz\xA1$\xBD\xB2\x81_9\xDF\x0BS\xCDl!S\xCB\xA4\xF2\xFAi\xF8F\xA2C\x8C\xA91 \x1F~\xD9\x94\xE9\xA3\xAAg]\xF1b\xD5\x8A\xDFX\x89<\x06r\x9D\xF9|n\xF8\xFF\xB7Kb\x0E\xDD\xB5\x11h\x06\xC7:\x83\x05\x92\xB6\x81\x15\x9C\x9D\xA1\x92\xB0xj\xEBG3\xA8\xAF\x9En\xE3\bX\x13\xEBd\x90\xA9-J\x8C7W\x95J\x81\xFA\xBAg\x03\x8Aa\x8D\xF1\x9D$?\xC4\x94>\x84\xB8"\x10v\xFE5\xC5F\xF7E)\xFEg\xD9"\x84;t\x9E*\x80\x025\xDF%\xBC\x1F]b\xFE\xA4\x14\x94\x82\x05H\xE4\xC3\xD3*\xD8\xD1\x85T\x96KX\x1B\xF3SZ\xB7\xA3>./\xCF\xCEo\x9C\xB3\x89?X\x9C\xB91\xBA\xA7\xCBc\xC3\r"\xB1\xCB\xE3\xD0\xFD\xA5\xCDn\x03\xC2\x82\x1E?QHAO\x0B\xDCh\f:;-\xEA-\xA3\\\xF7\xFB#\b\xC0w\xEA\x92_\x9CG\x8F|\x07\x97^U\x8990\x869\xB2\xDA\xFA\xD9\x95\xB4<\xBEM\xA7}\0U\xDCK\xDF\x91\xB9<{\xD2\xF9~\x97\xAEqdZ\x9E\xB7\xBES\xBC\x8D\xB1\x9F\xC3\x14\x8Dl\x0FEb\xB2\xAC\xBD\xF1\x04\xED\x9B\x16\xFF\x12\x11S\0\xA4\x96\x12\xCD\xFEi\x0BNR@\x19\x84y\xEB7\xFE\x8DeqF\xCC\x92`\xB7X*\xD0\tI@\xA7\x19\xEE\xDDgC\xA9\xF9\xB0\xAB\xCC\xB63\xE8y\x92\xCC\x1A/\x15\xDD"\xD8#\xD7m(\xA21\xFF\xE2f\x8Cx\x19\xCC>\x9F#U\x18g\xAB\xC5\xC9\xE36\xD0\xA5N\xFE\xA1q\x118e\xF0\x9C\x1DV\x01\xDE\xAFLUC.y\x1A\x80\x01(3 \xB0\r\x0B@=]o\xBA\xFBJ\xFC)\x7F\xD31\xA3\xE1\xE9\x10]\xEC\x0E\x85\xC9\xBD\xA8\xA0\xEE\xF1sv\xACS\x9B\x8D\xDB\xC0\\\x1F\xC6{.7Dy\xFC\xA8 \xB5\x98\xC3l\x9Dt\x85\x15!\x0En\xB0S\xF3\x9B\x811O\xD2\xA7u\x0B\xF4\x07\x0F)\xCB\x92k\xAC[*k-\xF8\xF6D\x90q\xFF(\xE4a7\xA0s\f\xB6\xEA\xE4w\xAFE\xE7\x8C\xA3\xFD\f\x0E\xFE\x93\x11\xA7\xB6q\x91\'\xA98\'\x068\x01\xD86A4J\x14\0\0\0\x01\0\0\0\x14\0\x05\0\x10g\xAD\xF0oN\x8F\x84H'
}

response = requests.post('https://s95951.cdn.ngenix.net/license', headers=headers, data=data)

**Comment by Joker179250** [comment]
https://pastebin.com/3w6Fv1E9

**Comment by medvm** [comment]
Попробуйте со всеми нужными куками и авторизацией в заголовках, у меня [UNGRANTED_REQUEST](https://user-images.githubusercontent.com/43696206/145736002-f43c7ede-7906-4e30-8253-ac7971f4b9c9.png). Как видите, на четвертом запросе, который вообще писался под другой сервис, почему-то выдается кривой кусок лицензии, который невозможно расшифровать, не сходятся контрольные суммы

**Comment by Joker179250** [comment]
Проверил. У меня та ошибка выдаётся что и была ранее

**Comment by medvm** [comment]
Если ошибка про module headers - обновите файл headers.py. Токен там нужен для поддержки работы с другими ресурсами, его значение для вашего конкретного случая не важно, он просто должен быть.

**Comment by medvm** [comment]
[Работает](https://user-images.githubusercontent.com/43696206/145810538-308e1f2a-7418-4399-b667-fc9c76760fe5.png) по аналогии с окко.

**Comment by Joker179250** [comment]
А как получить releasePid? Что нужно ввести?

**Comment by Joker179250** [comment]
Скиньте пожалуйста пример headers.py

**Comment by medvm** [comment]
Поле preauthorization в заголовке генерируется динамически, вам нужно его сгенерировать заранее курлом, а потом уже отправлять запрос лицензии с новым значением preauthorization в заголовках. Запрос, возвращающий preauthorization можно найти поиском в network

**Comment by Joker179250** [comment]
Посмотрите пожалуйста, что тут ещё нужно добавить? Сейчас пишет: unable to parse license - check protobufs
https://pastebin.com/z8LJiVFP

**Comment by medvm** [comment]
> Посмотрите пожалуйста, что тут ещё нужно добавить? Сейчас пишет: unable to parse license - check protobufs https://pastebin.com/z8LJiVFP

Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it.

**Comment by Joker179250** [comment]
https://disk.yandex.ru/d/RB0oexyR70q7Jg

**Comment by Joker179250** [comment]
Попробовал другой пример. Всё равно выскакивает это:

Input MPD URL: https://s35761.cdn.ngenix.net/mdrm/hd_2019_Vivarium__ar2_mkurazhbambey_x2gm11KECDO_film/c3464edd/manifest.mpd?profile=web_auto
License URL: https://s95951.cdn.ngenix.net/license

PSSH obtained.
AAAAYXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAEEIARIQPmrCA+0MR/y5SvtwQjUUZRoFQ29uYXgiJDcyZTJiYWY0LWI4NzktNGY2YS04ZTk5LTc3YTc5Yzg4Y2E5Mg==

license response status: <Response [200]>

unable to parse license - check protobufs

**Comment by kotuk** [comment]
А получилось добавить Wink?
А то у меня так и не получилось получить ключик
