### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'

### ISSUE THREAD

**Issue by geovane-gomes** [medvm/widevine_keys#19]
hello, any ideas on how i can solve this problem?
Python version =3.10
S.O = windows 10

_py l3.py
Traceback (most recent call last):
  File "D:\temp\BaixarVideosCopyright\widevine_keys-main\l3.py", line 11, in <module>
    from cdm import cdm, deviceconfig
  File "D:\temp\BaixarVideosCopyright\widevine_keys-main\cdm\cdm.py", line 10, in <module>
    from cdm.formats import wv_proto2_pb2 as wv_proto2
  File "D:\temp\BaixarVideosCopyright\widevine_keys-main\cdm\formats\wv_proto2_pb2.py", line 20, in <module>
    **_LICENSETYPE = DESCRIPTOR.enum_types_by_name['LicenseType']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'**_

**Comment by medvm** [comment]
`pip install -r requirements.txt `?

**Comment by geovane-gomes** [comment]
thank you for answering

but yes, everything installed correctly

**Comment by geovane-gomes** [comment]
Hi, i created a clean virtual machine windows 10 with python 3.10  and the original error doesn't happen anymore , thanks.

now look at this one, I think the way discovery plus takes the data to respond with the license is a little different


![image](https://user-images.githubusercontent.com/23656357/145808033-247be420-81fb-4b90-8720-28b9a5b4d867.png)
license url: https://discovery-us.conax.cloud/widevine/license


![image](https://user-images.githubusercontent.com/23656357/145808296-205404b5-5c8e-4013-99de-7816035070bc.png)
https://dplus-br-prod-vod.akamaized.net/ea72/094a/2631/5cd2edfd-8c05-419a-96ab-eb118ce7cecd/fmp4-playready-widevine/hdntl=exp=1639410243~acl=/ea72/094a/2631/5cd2edfd-8c05-419a-96ab-eb118ce7cecd/fmp4-playready-widevine/*~data=hdntl~hmac=4b57418710570c300586492995ae360ea7f68d2e37c0d791a5df7bddfc72a532/master.mpd

headers.py:
`import requests

headers = {
    'authority': 'discovery-us.conax.cloud',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
    'preauthorization': 'eyJleHAiOjE2MzkzOTU5MDMzMDcsImFsZyI6IkhTMjU2Iiwia2lkIjoiYzlmNzQ5YjEtYzAxMS00NGZhLTg1ZTktNjlkZmVkNWVmYjg4In0.eyJtb2RlIjoiU1RSRUFNSU5HIiwidXJpUHJvZmlsZUlkIjoiRlJFRV9VU0FHRSIsInNjb3BlIjoibGljQXV0aCIsImV4cCI6MTYzOTM5NTkwMywib3BlcmF0b3JJZCI6IjMwOTUiLCJqdGkiOiIxMjM2QzIwMkZFRTM0NzM4OEFENTIzNTA5QzkwREI4NSIsImNvbnRlbnRSZWYiOiJhODlmMzg5ZS1jNmM0LTMwYmUtMjU0OS1iYTg3NWEzMWViNGYiLCJsaWNlbnNlRHVyYXRpb24iOiJQVDI0SCJ9.wLLqMRkdBnpDox0DEZbn_h0tyzLsy_pt6tKsfVKmDlQ',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
    'sec-ch-ua-platform': '"Windows"',
    'accept': '*/*',
    'origin': 'https://www.discoveryplus.com',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://www.discoveryplus.com/',
    'accept-language': 'pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7',
}

data = {
  '\b\x01\x12\xE3\x1F\x12Y\nW\nA\b\x01\x12\x10\xD04@\xCD\x9B\xD7I\x01\x88\xD3x\xB7\xEC4.\xB7\x1A\x05Conax"$000003e9-c6c4-30be-2549-ba875a31eb4f\x10\x01\x1A\x10i\xAD\xFE\xA6B\xEAV\x10\x94j\xE8\xC7\xCB\x16\x8BI\x18\x01 \x93\xE4\xDC\x8D\x060\x158\xBD\x8A\x90\x94\x04B\xF5\x1E\n\tconax.com\x12\x10\x94s\x1B\xCE\x0F\xE3V"\xA8Rs\xD5\x9Ep\x07\xF5\x1A\xC0\x1Cl7\xAD\x7F|\xD26\x1F;\x18-\xAB\x9D\x12\x9E4V\x8AI\xF4\xAD(\xE3\\I;\x8AM\x14\x1D)s*\xDC\x9Am\x17 \x8A\x8E\x1C\x8F\xA5S\r\xC1\x91 \xE7\xDA\xE0 \xD2\xAC': '\xE9\x88\xF2 ;\xBA\xC0\xC1\xF3\xEB1\xC7\x9FMk\x90\xC2\xD1\xE9]\x93\xFC\x9F\f\xBDsh\x1E\xE7\xD0\xBF@4Zv\x96\x8C\x13\x8Af\xDF*\x89]\xBD \x86\x99,\xC3\xCB\xE16TO\xDAM\x12\xD5G\x92\xD1\x1C\f\xB3\x85\x15smq9\x02\xF01\xE1\xA8\xDA\xB4\x16\x86f\0M\x04\xAF\xA7X\xB9\xDA7\xBF\xEFE]\x17\x82\xDF\xD9;\x83\x03?b\x99\x0F\xC4\x06\xDF\xAD\x81u\xB4\xE9\xB0\x82\x9Ef\xAA\x8C\x8C\x9E]\x92\xD3\xE8\'\x8F\xA6\xF4\x85\xEE\xB3I\x9Eu)R\xD6\0T\0Kf\x1B\xDC\xE1\xFD\x17\xA4z5\xA1\xD4\x8C\xDE\x92\xFD\xD49\x04\b\xB8-7\x93\xD7b|\x8B\xFC\xAB\xC2\xE6\xF3\xEB \x07p\x8C\xF8h\x0F\xBCC\xB7F\xA8 \x19`:B\x0F\x84\xB6\xD9"\x1D\xC4\x9A\xC6l\xB5\xC4vI\x0Fz\x1E\xB0]\f\xB8y\x80f\r\xCE\xD7Bwg\x17',
  ',': '',
  '\x1E\xD1\xF3\x94S\x80JzD\xDD\xF8\xD0O\xFF\x81\n\xDA\xB0\xF2Q\xEA\xA4\xFC"\x9F\x93Nh\xED': '\xA2)\xB8\xAE\x8Clp\xED\xED\x0B\x1B\xD50Sbab2\xBC$uw\x0F\xD4t\xA12\x85m\x19y\x174l\xEAaR=\xC3\xD4\xC2 Q-;K\xB3{\xC9\xA4\x04h\x0E\n\xDD\x1F\xC3\x90\x0F3\xA7\xED0\x1C\x802\xED\x86\xBF\xAB4\xB8 #{\x91pG\x7F\xE7yX~\x8C\x13\xFD]\x86\xB35\xDD\'\xAD\xCBb_I6C)\x85\xB0\xA5m\xAC\x99\xB3\x94MQ\x14C\xBF\xC3z\x1CY\xA3\xC2 Y\x8B\x02\xC2\x98\\|S\xE4\x9C\xD9w)\x89\xEF\xFA\xB6\xDA\x7FR\r\x03\x14\x18e;t\x1C@\x94\xBB\xBD\xC4eW\xF9\x8F\x05x)\x05\xCB)\xD5\x88\xA6\x86\x88,9D\xD1"\x9D\xC0]*6\xD4_\x89#<Q>\x9D\x9CEr?\xCF\xE3\x1D\xCA\xB2\x11\xB5\x0B\x7F\x05J\0\x95\x93\x86\x86\xF6-#\xF9\xCEY\xFFXL\x97z9\xF4se\x13\x8E\xA0\xB2Bk\xA8\x0E$\xD8\x1D\xC7\x80\x93\x0E\x8B\xDD\xBF@\x18T\x96\xBD\x07\xC5$\xFD\x9B\xB83w3\xFD\x8C\0rt\x13\xB4\x97\x94\xB5O\xFAX*\0\xD3\xAET\x19\x13\x95\x8D\x11Z\xC9\xED\t\x06V\x82\xC6\x13P<\xF7\0\xFB',
  '"\x1A\xEE\xB7Zinr\x1F#Dx\x8BM\xAB\xF7\xA4GI\xE8\xFCR2\n\xBE\xC6\x1D\xFBA\x17\xDC\xD7\xFD\xED ?wg u\x13@\xFF%\xE2\xE8\x03\xD7\x86{\xF9\xFC\x17V\x93\xAB)\xE1\xA4\x91\xC25\x95L\xDB\x8A`\xC7x\xE9\x1CO\xC4\xBEq\x9B9{\x96\xE6\xD4\xD7\x91\xD2\x0B[\xB3I\x85\xB6CFl\xC3@.\x167\x7F\x01\x93\xFD~\xED\xCB\x8A\x97\xD6\xDD/\x01\xF0\x15h\xD2\xA0\x92\x9A\xE1\xD9\x91Q\x95\0\xBA \x19\xEB]o\xC7S<\x96\xC3\xFDu\x83_\x11\xC0iv\x1F\x0143!|A\xA6tw\xCF\xAB\x8E2z\x90\xD7S\x9F\xECGfq\\\xF1(\xA0\xFC\xC6\xCCN\x10\xA0\xEF': '',
  '\xFC\xB9V\f7w\x97\xD9h/C\xB1uA\x06\x8A\x19)Y\xCB\'\xFB>\xCB\x1F\xA2\x01\xD7\xCBk\xF6yfG\xD1d\xAC\xC20\xE3\xE0\x7F\xC3\x91\xA9_\x865m|O\x9E\x81z\x18]\xF5\b\xD6\xDE\x1C\x14\'\xC8\xF8%\b\xC4\x11ivk': '',
  '\x82\xB3z\x86k\xCC\x16\xC6*\xBB\x7F\x80C\xC4~\xE7\x11\x02\xF6b\x8D{<\xEF\xE9bS\xA3\x9F|C<Z\x81\xA45fzn\n\x9Dj\\\x15\x0B,\xD8 \x10.wB\xEC\xBFy\xFF\xD6\xFC\xCA\x0B\t\x81\xEC?\xEC\xE7\x13\xB2\x95\xB6\xEB\xA8\xB3\x19@z\x163K\x05\x87\x9F\xEE\x9Fq\xFB;O7\b\x81\x7Fb\xBA\x89\xA0\x03)b\xA4\xE9\'\xEA~\xC0<t2(\xCA\xA1\x1A\x03\xF1\xE3\xFDq\xE42V\xD3\xF7\xD5\x05\xBF\xDA\0\xFCh\xE6u(4n\xD4\x94\x9AfQT\xCD\x934P\xE2m\xE6xP\x9C\xC7Y\x93ht\x82N\r\xAC\x91xe*\xD5\xDA{U\x12\xFC\xCBmv\xC2\b<(\xEE\xF4\xC8\xAC\xE6\xB0nf\xEEh2\xCF\xD9\x8A6\x9C\xDE\xF6\xFD!\xAE\xB2\xD9j\xE5K\x04"\f;': '\xEF\xEF\xE4\xC3z Q\xB6\x8B\xCF\xFF\xFC\xEBE\x01^\xFF\xA4\xDF\x17\xF2\xA3 \xF4x\xE3\x90(\'8\xFD\xF5\t\x1F\x8C<\xC8c\xBA\xFB\xBFHX\xD6*uq\x11g\x9B\x1E#\x13W\xE2\xC7\x944\x93;\xCA\xB1x\x7FtU\xB9\xAA\x84k\x89\xE7\x87\xE5\xAF\xA6z\x81\xDA<\xCAgr\xDFC\xA9\n\x17\xA7\xE2\xDD\xE6\xD0\r)\x02,\x0E\x84:\xCD7\xF3l\x03\xCAX\xB4\x07k\xC8<\x87n\x0F\xBD\x81.\xE3\xD1q\x04\xB6P\x81X\xF0\xB66\xB8\xB1\xA2)\xD6%n\x88\xD7\0\xB6H%2\x1E\x95\xC5J\xFE\x17\x10\xEB\xEE\xBBq\x9Ax\x93\t\x0B\xDC\x9F:}\xB8\xB6)9p\x1E\x86.N\x81\x80\xEB\x9F,\x1D(\x04:Q\x85\x072\xF5\x90Y\xFA1f\xFE\xD9\x15\x0E \x83\xB8\x97i\x9E>\x0Eq\xE4rD\xDB4\x04\xF3X\x93\x85_E\xDE\xA5\xEB\xA1\xD0\xCD(l\x91\xF7\x7F0\xFEsIP)\xA1\x92\xBBOb<$\xBE\xB9\x88;\x93r\xBB\x85\xB8\x85\xE9\x86}\xEA\x14\xFA\xFC\xD5f\xDD\x19t \xFB \xAA\xD26g\xD9\x11\xD3k\x10\x07\x9E@1\x1A\xDC5O\x87\f\xB4\xF9\x17\xC2\x02\xF7\xCFD`]\n\xBCx|w\x9Dk\x14\x05>U;\x19\bS\xEC$}y\xC0\n,,L\xC4\x979^\xAE\xE9\xFE\xE4\x19\x02\x0BN1?\xD2\xAA\x9E.\x1A=3Y \xF9\x06\x13x\b]\xC5\x1D=\x81.\x0F\xE7c\x86\xCD\xD3\x7Fva F\xDC_\xD1u\x96\xC0\x13,\x12\xBB#\xE6A|\xEE?\xA71o\xC3lKx\x8B\t\xA9o\x14\x82}c\xF3\xE6\x18\\\x9F\xC7}\xB27\xE6\xF8\x83Z\xED\xE9E\xFA\x8D R\xD0(\x95\x84\xE4n\xD9\xF1/{\xB2b\t:\xB7\xF6\xB4\xB2A6\x8B\x88\xF4%\xF0\n\xE9e\f@\x1F\xFC\xB2\x03\x92\xF9!c\xCAs\xBE\x93\xE9,\x1D\xAD\xB1p\xCE\xE1\xC9\x95\xC0\x07\x95Z\xC1\xBD`\x15\xA1\xE5\xB5*\xE5W\xE4F\r\x84N-0\x84\x1AT\xF9!\xA9\xEF\x05P\x93\xB7\xC6\x90\xD6p\xB3U\xD8\x13\xDA\x1FOe\xCD\xCE\x851\xAEh\xD1\x07\x8D\xB9s7\xDE\x06\x9F\xFD\x1A\x05\xF4\xD4\x8E\xB2h]\xA6wQg\xBC\xD5\xCB\x06m\x02\xF6\xB8n\xBB\xA1W\xA4\x80\xBC\be\xF35(\xE8\t\x88\x89\x12w\x8E\xD1\x84\xB2\xC9\b7,\xEDR\x94\xB1aQ\n\xA6\xC4<\xBD\xEDo\xE6c\xE6,j\xF1\xF3\x1E\xF2\x8B\x1AxM\xE5\x8Ds\xFE\x04\xFA\xDDQ<[\xC1A\x06\xC4\xC3\xA5\xC7\xDE\xE1\x88\xC1M\x03\x89G\xBB\0\xE3R\fe\xFF2\xFB"m\xA7ua8\xC0\x85L\xE9\x818$G\xEC"_yBS2\0]\x99\x9BW\x88\xE2\xB1M\xDCd{H\x96\xF4\x13\xDAs\x1A\x97\x809\xB8% \x98\xB3Ep\xF0\xA0\xC7\xB7\x99x^\x9B\x95\xB5\xC7\xA6N\xE4(\x99\xF0\x7F\x05\xA8\xF1\x91\x07c\x18V\xD8\xD9<5\x1C\\\x85\xA2\xE5\x94\x82\xB2U\xAB\xBE\xD9\\\xAD\x83\'\xF0Z\x9B\xFA\x10,\x9E\xD8\xC3\x11n\xF2HJW)\xCC\xD39\x18`#\x84\x99\xAC\xFD\x7Fs\xB6X6\x82\x1B\xCF\xAA4\xBB\xF5\x1B\xAE\x98\xCE\x91\xC0\xE6O\x7F\xA8H\xD6\xB3\xE0\xBDFf\xCA\x031wL)e\x90\\\xC3e\xF9\x18%|\x89\xE6A\xAC\x8BL\xF7\xE9\x1E5$\xD4\n\xD2\xDBoG\xB7\x95q\x16\x86\x1F\xDF\xA8',
  '\x0F\x9C\xCF\xD2\xFFfN\x9F': 'h\xC7\xD9\x9CWJ\x11\x15\xA7g\x15\xB2d6\xDD@\xBEK\xB7p$\xD0\x86H~\xE0\xC7\x84L\xED\x1BT\xE0\x1A\xC3e8\x99\xF9\xE6vR\xBF\xB2y\x83\xBF\x1B3\x0F\x18\x9F \xCF\x8E\xBE\xE6\x8D\xD3\x86R\x1E\x8A\x95U"\xAD\xED\x1D\xC0ZF\x8C\x8E\x9E "\xE1\xDB\xBC\xFAO6\xFD\xC7f\x8A\xF6\xFE\xBC\xCF`\xFB%~\xCD\xFD\xD4L<\x95AV?P\x19Fp\x1A\x17\x02\x06\x04iz\xAA\x0B\xAD\xB7X\x84\x826\x1E<\x04 #}\xF0\xB5\xDC\x92]\xDB-\x82,\x1B\x82\x04\x95\xDE\x8A\x13x\xB4\x1C\xD2\xDD\x9FA\xB0\x92\xEE\xF0c\xA1=/\x9C\x83[\xF13\xC7\xA4<\xCF\x16/c0O\x84I\x07\xA4\xAF/\x04\x0Eq\x96\xF0\tD)\xCD\x8D\xBAC1\xDE\xDD\x88\xA476\x91\x99\x9C\xCD\x0F\xDE\x05\x02Gc?)A\xF85\xCC*\x8C\xA4m\x96\xC0\xCF\xD31\xAD\xCB\x8E\x99\x17\r\x83\x03\xA9W?\x96\xED\x90q]\x06Bh\x12\xD5\x9A\x9B.x\xE9\xEA`\xFE\x8E\xF2\xB0\x80\xCC\xE3W\xB1\x01\x03\xDD\xA2(\x96i\xD5n\xB0\x8Fi\xC8\xD5\\btZ\xFF\xEB=\xCC\x13\x9E;#Qn\xD3\x01\x83\xC9\xAD\xBAJ\xD2\xFC\x83\x9FO-\x9B\x85\x80\x15\xAA\xB5\xC4<\xC0\xF1\xF4R\xCF\x89\xF1\xC1\x19r\x96U7\xDA\xAF\xC5\xD9\xDC\xA1\xA3n \xF7\tF\xDE:\x16\x07\x91f\xC9bBe\xB9\xD3Vp\xCC\xDF\xED\x9FE\xB8%\xBF\xD9\xBDD6b\xB1\xDEq\xA8\x90\x0E\x91\xC7\xDEl\xD4\x189\xD7R,>E\x95q\x82\x83O\x02\x99v\xDD\x11\x90$i\x10\x1D\xB0\x82\x15\x8B,\x0B\xCD\0\x10\xF17\x94\xD0~zRDO1\x1D_\xDC\xA4\x84H\xDC\xDE{\x9B\xD4!d\xC99\xE9\x9F\xFD\xB1\x18k\xCBYB\x04\xF3\xB8\xB9\xAA~(l\xF8j\xCC\x85c\xEC\xC5\xE0\xDD!\x88$m\x90\xA1\xC1\xEB;\xC7< R\x84\x8AH \xD9\xF5Z\xC1\xAFCG\xAC\x83Q:Mk\x06\xAA\xEE\xB8\x1F=\x8B\x12\xE6w\x1DT\xB8S\xD9\xD4\xCC\xFB\x16l\xFFK\x13J|\n\xA2\xB9\x04\xA9\xC9\xBDU0\x9C\xDD\x91\x92\xB2%\x95D\xE4\xBE\xBA\xE1\xA6\xB6K6\x9C`\xFA\xD0\x9E\x9A\xF1\xEC0\xEA\x0B\x90\xB8>i\xAF\xC9\xBB\xE9\x1E\xFEn\x94\x1A\xA1\x17\x8C}\xF4\xF6\xBC\xF6\x93 \xBC\xC3\xA3\x85\x9B\xB4/?\xE7\x18\x91\xF1"\0\x0EY \xBA\xEEz\0XPG\x03F\xBB\x93u\xA3\x13\x1F\xB3\xCC\x84!\xD6\f\x8E?\xEF\xAEwr\x18k\xF1\xA4\x07\x95\x89\xC9\xE5\xF9\xA7\xB4e\xEC\xF9\x9AE\x8C%p\xA5`\xAE0\x8AL\xE0$I"\xBB!\xCA85\xCCB\x9A\xC5e\xBA\xF8<\x1F3n.)\x97)\x07\xAE=\xBD\xC2Q\xCF\xE1\x9A9\x88\xE1\xE520\x8Fp@1\x12:\x1E\xC3y\tN\xCE\xF1\xA8\xB8\xD0\xD9\x87\xA1\xA2\x1D\xB5\xD4\'\xCF\x85\x12O\xCA\x93\xEF',
  '\xF9;\xBB\f\xE1\xFB\x05y8\xDE\xA34\x9D\x14$\xFD,L\x90\xA6\'K\xB7\x1C\xF0\xF7-\xD6K<\xB5\xC95\xE4\x15\xB5D\xBDG-.\xD1\x95\xA2\xEC\xA6\xBA\xA4J\x8A\xB2\x8CT\x0B\xAC\xFD\x05\x91l\x19\xBE\x96l{\xAA\x82T;\x0B,\x06\x8F5JF\x88\x14\\\xC0\xFA?\xEE\xED"T\x84]\xA1P\xE3\xF1\x96\xAA\xB9\x1E\x89\xB1\xF4\xCDP\xC9\xF5^\xF2,\xDC\xD2\xC4\x0B|\x0F\x95\x918?\x03\xA4\xD7\x04w': '',
  '\xA5;\xA2\x81[\x11\xD9g@gT\x8F7\xDDS\xBA\xA4\x94\x0059\xE5Q\x8D\x98\xF0r_M\x84\x9A\xBE!\xD4\xFF\xB9\xCCx\xF3\x05gU\xED\xD4z': '',
  '\x91\xCD-\x94\xAEV\xCD/\nv\xD6\xC2\xF3\xC0\x91#7\xC44\x80\xAF\xDAdS\xB2\xE7\x13 \xAEc\xAB~\x87\x8C\n-\xAF<\xE5  \x1Dv\xE62:\xAA\xDA\xE2\xF21$\x87\xC8u\xDA\xD1\x97\xCA\xEE2\xEE\x8B#\xFB\xBF\xAB\xFAt%\x0F\xA5\x0B\x98\bG_;\xD5r\xEA\xE9\xD6\xE4\xEC\xC3\xF1d\x8E\xCB\t\xA6': '\xAC\xA7\xF6a5\0\xF2\xC5\x1B\x11\x95\x15v\xFB\xD4W\x11 <\x8F\xEF\xCE\xB0\xA0\f\xFA \xD3\x82\xCB~\xB6H\xA8\xAAe\'O\xA92\xE6W\xE5\xED \xBB\x92v\x01x\x7F\xF6\xCASt\xAB',
  'j\x92a\t\xDE\x004\xB1\xD7t\xDB\xE6\x9C\xAE\xC6A\x16\x88\xABj. \xCAn\xAD\xDB\xB8\x05\t\xB9**\xE8#\xBF\xACdB?\x8D\x18\xD4\x83\xA8v,\x98$F\x1Ac\xD3\xA0\xEF@\x809\xBCq\xBB\xC7UW\b\xCD\xE9\x83\x04\xE8.\x07\'J)S\xCC\'\\\xB9\xA6\x1CfvH\xFD@\xEA\xAA*\xB9': '',
  '\xFF`\xC0oc\xF7\xE28qj(\xD9\x05\xF1\xD8\xDC\xEBd\xEA \x16\xF8f\x89\x11\x14\\^|o\x1C\xDD\x05\x11\x9B\xBB\x01\xE3\xAAg\x818\xC7?\x7F\xC0\x97\xD4\xBC_\x98\xCB\xD0\x1D\x89\xE3x\x8B\xAA^F\x138\xE2"\xC6\x91\x83\x90\x19\xB4a\xBF\xEEf\xD9E\xDD\x93D\xC4\xFC\x85\xAF\xAD\x07\xB5#\xCFx\x9DG\xE3\xEC\x9A\xDE\xFAY\xBB': '\xF1\xBA\xFC\xE43\xB3\xDA\x9D\xA7a\x8Fi[4\x1F\xAAAM\xDC8Fm\xF6\x10\x87\x8D\xF2\xE7h\xCC\x9E\t\xEB\x06\x1D\x11`\x1A\xF3\xB86\xFD\xCF\x1C\xE3\xE3\x9B@{9^\xE4\x8F\x127]l\xB3\xAC(\xF0\x1B|\xA2,\xD9\xF7\xAF\x15c\x10\xEE,\xF8C',
  'Cj\x14\xE11\x0F\x14': '"*SpQ$\x8E,\xB4\xDD\xE1/\x80\xEFT\x8D\x1F"\xF0\x88\xB2%\xE2\xC1kR\xC3\xDE=rE\xD4l\x1D{\xDA\xE9\x0E\x84K\xE0\xE3@\x9C\f\x92B\0E\x9F\xA1U\xF5\xCBl\xEB\xC3}\x8B\xF9\xFCvk%\xB5\xD5\xB7\xDB\xB2D\x12l\x8Dp\x8B\xAD\x0E\x18M\xFDj\x91?\xDB\n\xA7F\x04;\xFDV\xF0\x8FqR1\xE6\xD0\xAE\xE2,\xB8\x16o\xCF\xDBB\xAB_t\xA8_p\x94\x9C\x82X\x1D\xFD\xBF\x06\x16\xE6F\x1E\x9B\xBFn',
  '?eK\xD0\xC2\x9C)\xAF\xDE\x9A\t\xF0\xB3y\xBB L\x1A\x02\xBD\xF3:\x8A\x83\xE5\xFC\xAF\xFB \xFB9.\x80\\V\xD4y\x8AP-W`\xA8\t\xC8\x1D\xE8\x0Bd\x17\xF75\xD5\xD14a\x8B\xF0\xB0\x9A\xFB\x9C\x18\x88k/\x8A\xC7\xFC\xA8\xFA\f\xE1\xF4\xCD\x87\t\xEFL\x15\xD4l.\xD4\xEA\0\xB2\x01\xEAmY\xE22;\xDA\xC1E7\xC6\xEDbz\xB8\xD9j\xE20\xA1\xE2\x80\xB0,C\xCE \xFD/^\xD1Y\xDAv\xC3\xC1\xD7A\xEB\x90g\xE0\x1A\xCE\x9F\xE92\xED\x12{.\xA8o\xA0b\x7F/\x91(\xAE\x14m\x95\x1A\x1Fg\x1D\n\xD5\xFD\xCDa\xE2\x96\xF7`v\xA4M0a\x03\x81o`jTA\xF9\xCE\x19\x85\x03<OP\xB1\x9F9|\xE2\xE6\\\xA8\xC3\x10F\xCFb\xA9\xE9)\xF02\xE5\xE7\xD1\x16\x8Bz\nf\xD2\xB3m\xD1\x0FV\x9E\xD0V\xE9u\xFB\xEF\x95\x82gn\xF98\x92Z\xE5\x0BN\0\xA9\t\xAF\xAC\f{\xDF\x82^\x18R\xDCJOd\xA5\x94\r\x9D': '',
  '\xCA\x0F\x14\xBC\xF9\b\xF2\xA7\x1D\x94\xA5\x1E\x0F\xA8\\\xCF|j\xD4\x17\r\xEC\x94\x16\x02\x9F\xAD>#\x90A\xDD\x18\xC3\xF8\x81\xD7?1\x8A\x92\x9CtI\x8D\xCF!\x85\xE8\xAEP\xC0an\x9D\xC8\x152\xA9o\xAE\0\xE2- \xA7d\x85\x8F"\x10\xA6k\fa\x9B': '=\xBE\xE4`r\xE0\x14\xC2\xF9\xB8*\x80\x02\x9F\xC2D6\x90\x8F\xD1Z8?\x86\xDAwwu~\xDBGL\xF1\xC8\x020\x8ESI\xE4H"\xBE\xAC\xD3P\xD0Oq\x93!H\xE8\t\x04\x17\x81\x83\xDEqm\x11\xEA1\xBDiJ\x84\xA2\xC5\xEF\xC1\x14\xD7\xDB\x94\xDD\x12F\xCE\x9C\xA6\xB0\xAF\xD2,\xB62y\x01\x1F\xBAM\x1F/\xE9\xB4\x1F \x83\xE4\x99\xBB`\xCE\xF4\xC7\xA3\xF9\'}\xF1MKVd%\x94\xECb\xDBY \xA6\xF3w\xA8cpXg\x88D\xBA\xC4Kx \xD1uIB\x96H~\x10\xF1\xA7\x89\xC7\x90\xE9\r\x90\xF1\x98\x87s\xD0D\xF678\xD7\xB9v\x1Cx#\x82G\xBD\x95%\x8DJ\x9AL7\x18p5"\xE1\xF8\xA2\x83R\x81\x8B\xC2l\xE7\xD4\x15\f\xB1\x90f\xE5\xAD\b\x9A\x80$\x14\xAD\x1E\'U\x98\xDC\xD66!,\x04\xB1\xE95\x1D~\xFB\xEE\xD5D\xE2\x016I',
  '\xF2\xE4\xCDJ\xF1{\xE6XV\\\xC9\xFD\x9E\x14\x0F\xEA"\x8F\xA4\xF3\xF3\xFD9#\xC9\xCF]\xC5Of\x18\x96\x96\xA77\xF4$\xB5\x1A\x80\x01O`\r\xF5K\xB8\x18\x0E\x81\xB6\x19\xE4Z\x9C\x7F#\xD7\xF1wJ\x02\x8BlG\x97B\x189\x8D\x0E\xCFnp\xCA3rb\xD5\xFC\xBA\xCC5^5\xFDt': '',
  'N\r\x19\xE8\xD3G\xD6\xECV\xDFn"\xE3\xF4\x8E\xC2DQP\x19\xEEV\xDE,\x7FQ\x93\x0Ee\xEE\xD75\f\xAD\xA6H\x1B q\xC1)dR\x89\xA8\xBFZ\x9F\xB1\xEF6\xEDb\x10z\xC9\0>aT\xF2\xA3\x9B\xC3\x19\x19\xED\xAAf\xC4\x16k\xA2\xD3\xF3e\xA1\0\xD1\x83J\x14\0\0\0\x01\0\0\0\x14\0\x05\0\x10B\x84\x05': '\xEF\xEB\x04%'
}

response = requests.post('https://discovery-us.conax.cloud/widevine/license', headers=headers, data=data)`

![image](https://user-images.githubusercontent.com/23656357/145808629-b147ca31-f137-43b5-b584-5e435a74224c.png)

if you are interested in testing discovery+ brazil
I have a courtesy link from a Brazilian telephone operator. with accounts that work until 01 May 2022

https://auth.discoveryplus.com/br/redeem?flow=redeem

use this redeem code: **CLARO2021**

**Comment by medvm** [comment]
update your headers.py file then read readme
