### ISSUE TITLE
Get key error: AttributeError: module 'headers' has no attribute 'token'

### ISSUE THREAD

**Issue by davidjames146** [medvm/widevine_keys#20]
Hello,

I got error when request key of VieOn website (streaming service in Vietnam). (AttributeError: module 'headers' has no attribute 'token')

I use Python 3.9.9

Here is my infomation:

MPDLink: https://sgn-vnpt-001-livecdn-vthn-vnd.vieon.vn/64a746395b9fd585e07e33064f9da7fd/1639407409828/qnet_vod/storage02/hbo/the_conjuring_2/dash/master.mpd
License URL: https://drmtoday.vieon.vn/license-proxy-widevine/cenc/
PSSH: AAAAgXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAGEIARIQ6dQrLZC5Pou06R0azvvENhoIY2FzdGxhYnMiOGV5SmhjM05sZEVsa0lqb2lNREl3TlRNMFRERWlMQ0oyWVhKcFlXNTBTV1FpT2lKMmIyUWlmUT09MgdkZWZhdWx0
Headers:
import requests

headers = {
    'authority': 'drmtoday.vieon.vn',
    'sec-ch-ua': '"Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36',
    'x-dt-custom-data': 'eyJ1c2VySWQiOiIxMi1hZmRjM2Y5Zjc0OTM4YWE4M2JlMmEzMGE4YzA2MGY3NyIsInNlc3Npb25JZCI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUp2Y0dWeVlYUnZjbDlwWkNJNk1USXNJbk5sYzNOcGIyNUpaQ0k2SW1GbVpHTXpaamxtTFRjME9UTXRPR0ZoT0MwelltVXlMV0V6TUdFNFl6QTJNR1kzTnpFMk16a3pNakV3TURraUxDSjBhVzFsYzNSaGJYQWlPakUyTXprek1qRXdNRGtzSW5WelpYSkpaQ0k2SWpFeUxXRm1aR016WmpsbU56UTVNemhoWVRnelltVXlZVE13WVRoak1EWXdaamMzSW4wLmk5dzdYZlZZYWVwTmQyU2t4YWZhRVZRSXJSOXcxbHBxRXJ5WEFldTJjaU0iLCJtZXJjaGFudCI6InFuZXQifQ==',
    'sec-ch-ua-platform': '"Windows"',
    'accept': '*/*',
    'origin': 'https://vieon.vn',
    'sec-fetch-site': 'same-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://vieon.vn/',
    'accept-language': 'en-US,en;q=0.9,vi;q=0.8',
}

data = {
  '\b\x01\x12\x8E \x12y\nw\na\b\x01\x12\x10\xE9\xD4 -\x90\xB9>\x8B\xB4\xE9\x1D\x1A\xCE\xFB\xC46\x1A\bcastlabs"8eyJhc3NldElkIjoiMDIwNTM0TDEiLCJ2YXJpYW50SWQiOiJ2b2QifQ': '=2\x07default\x10\x01\x1A\x109\xC5\r',
  '\f\x813|\xB9O[L\xD0\xD1\xCE\xDA\x18\x01 \x99\x9B\xD8\x8D\x060\x158\xED\x9F\xA3\xFE\nB\x80\x1F\n\x14license.widevine.com\x12\x10\x17\x05\xB9\x17\xCC\x12\x04\x86\x8B\x063:/w*\x8C\x1A\xC0\x1C\xA1m\xB0\xFA\xAE.\x0FY\xAA\x01f \xEC\xFB\x16\xCD\x1Eu\xB7\xE7wS\xAFk\xC5[\r\nh\xA1\xBB\xA4\xF7T\xED?\xD3)P\xB1~\xEE\xD1\xAF\x7FI\nw\x8A\xEFO\xF8\xE4w\xA9\xF2z\xE8F\xFAzd\xDB\xB4\xBF;\x82~\x07\xA1\xA7\xD9%U\x9C\xFE\xE55\xAD\x95T!\x86\\\xCA1u\xF1\x81F\xD2<\xE2\xC3\x87\xFCUu\x8Cw\xBDz\x8EF\x98\x0B\xA3Q^\xE8\x15\xC7Y\x81Dy\xDAX>\x89\'E\xF2\xFDG\x9Ar}\x07\xB8\xFE\xAF\xF4\xD1\xF1\xC15\x07{\xA5n\x8E\x81\x12\x80qYN\x106\xCALs': '',
  '\x9E7\xE9l\xEB\x070\x15\xEB\xB5\xB9\xEA\xF4\xA8jO?\xD7\x93\xD00\xFF\r\xC5Y\xF7\xA9\xFE\xB7\xE8hys\xEE\xD9\xE9\xEF3\xFFEV\xEB:bF\xBA\tb\xF0\x05Z\xB3c\x18\xF5\xC1\xA5\xEC\xB7\xF2?4\xCD4O%\x05\x04\':\xF5\xEB\xD95\xD9r*\x03v\xD9\xF6!\xF6\x05\xF6\xF6\xF1\xF2\xC9\xD6\xEB\x8AK^kQ\x87\xEEZ\x1Dl.\x11\x02\xF1\xD6I\x0F\x1A\r Kr\x8F6\xA6\x93\xC3\xD2\xCB,\x9BP^\x8B\x93\x05\xE0)UqZ48\xDA\xB2H\xE3\x95\xD9\xEEL\x8D/\x8B$\x0B\x94\xA7\xFF\xC2Y\x8A\x952\x07H\xC8$\xB0{\xCF\x9D\r\xD7]Q\xDA\x8E\xE2\xD4\xB5\xB5\xA9:\x0F\xBB6^:\xA0\xB5\x07M\xC0\x1DV`\xAD\xF2\x81\x82\x18_Xf\x1A\xC9\xC71\xE2$\x80@\xB9\x9F>\xB1\xDA\0\xBB\x9F\xC0q\xB8\x199\xFD\xF4\x9B\xB8\x86\f\x8By\xC6\xDDa\xF2n\x88pH\x91]y\xB2}\x8B\xFEu\x1F\xE93\x82\x8D\'o\xBE\xF7h\xD2\xD6EEF\xF2\0\xAE\xA6\xC4-\xD9\xD9\x99\x8F\xCF\xEB/,\xA0!z': '',
  'o': '',
  '\b\xCC\xA6\xD5\x91\xAB9E\x06\x1C,\x1B\x11W\xF8\x10\x87\f\xE9v\x99\xD6\xE9\x8F\x12JOE4\xDF\xB9\xFD8\xB93\x7F\x9E\xB6^\'%\xF5U\xEF\xBD\xC4z.A\x9Ewpzo,\x15\b\xA4e \xE8\xA2;\xA4\xE1\x8F\xDF\xD2\xC0?\xFA\xE9l\xF5hm\xE0\xA6\x82 \xFCnMM\xBB\x86@Hr\x18\x13%]\x8D9n\xD5\xB1\xBA \x98\x1Dj\xD57s\x98\xD9\x9C\xF4\x98\xEFX\x1B\xA2.i\x10M\x02,\xE85<:)\xB1\b\xC8\xEB\x13\xC1\x89HK\x16\xE935\x9Eg\xDC\x9A\xED\x8D\x85\x1ER\0|Az\xC2\xE4e\x89\x12\xFDf\xEA\x10^D/*\xE6:N\xF8\x98\x18\r\x03q\x89\xADm[\x14|\t\xB4\xB1\x83H6\xD1\x1B\xEA\xE5\x15\xF0\x9A\xBF\xD3\x97\xC8\xC4{8;\xC4[t\xB5a\xD5\xA7!\xB4Yt\t\xEC\x87/yq\x1B\x81\xEF\x15\xB6\xAB4mA\xF1dS\xC1\xFA\xC3\x90\x970x\xE5\xAF{\x0E\0\x8B\xF0\xB3\x14\x0BM\x12\x1F\xD9\x07.\xCA->\xE9U\x8B\x93{\xFA\x9Eh\xE1\xAD\xCB7\b\x1A\xE8\xE3\xA2f\x1B\x90\xBE\xFD\xA9\x96\xBAyh\xBC\xB8\xAD\x04\x01\x06\xBB`\x8F\xBB\x03\xC3\xD9\n!\x15\xF4\x10\x16|C\xF5;\xC6.\xF1\x8Ak\xF2\x0E\x89u\x8C\x17\xA0\xCBb\xE4\xDEA\xFAd\xA0ig\xD8\xF74\xCF^\xB6\xE8\xB5*\x12\x8F\xC0\xD6\x95\xB7\0Xh\x9F\x1F\xB6o\xFA\xCEU\xDB\xDE\xC1\xAF\xE9\xA2\x8C4\xD9\xE5\xA2r\x98\xFDt\xB2\xD8\x046\xCF_\x8Eg\xAB\x93\x94\x8E>"\xB2@\xC5PM\xD4\x80,\xAE\xB5\xF98\xE8P\x05\xAE\x01{\xF8d\x89\xDF\xBD\rW\x82\x03n\x1B\x11\xB0<\xCC\x1E\r\xA8_\xF5\x0F\x84\xB089\xD0\xFD)\xD1\x12c\xEF\x9A \x0B\x81G\xE9j\xC6\x07\xC2\xCE\x98r': '\xFB\'Np\x0B\xFC\xE9P\x99\x94\xDC\xDB\xEF-\'\xCB\xA7\x95l\x8D[\xCA\x8C\xF8\xA6\xA5\xC9_\x82\xC6\xCC Y\xA0\x95\x9CdE8\x7F\xCD\x05\xA1RVn\x93\x13\xE0)9\xF5`\xB8\xA8\xF4]\\\xAC\xC7\xB1\xBB\xACa2\x14\xD3\xD7G\xBF\xBB!Le\x9D\xCE@>i\xFB$\x98\xB9\xC8LG\xE7{\xE0@N\x18\xCCrt \x10\b\xF6[\x85\xAE\xAFR\xE0\r\x84\x1F\xC2n\xAA\xC20\xA5\x9A7\x06r\xB6Li\xBC\xE6p\xF1\x8E\x91\xEFJ\x17\xA8',
  'M\xFA\xC7\xD0U\x03': '',
  '\xFC\xA2]@J\xD5\xF7\xE5\x14\xD7\xE2\xCF3U\xBA\xD2\x13<\xA8\xFC\x01\x8C\x15\xD6\xE1\xC2\xF0\xF7sG\xE19_\xF7c\b\xC7\x07\xCAF\x14\x9DHr\xB33h\x14\xA1v\xF0\xEE\xB6\x17yX#\xD8`_\xDB_\x86\x0B\bO\xA4\xDC\x1D\xB6\xF4\x85\x9B\x99~\x17\xC9y\xB9\xE4[@\xBB"\x16\x90\x93I\xCF\xE6-\x8E|M\xAB_FBk\xEAa`\xF0\xB2\xD5\x17\xD68U\xEB\xFCq\xE5V@\0c\xFC\xF8]1\xBBR\xBF\t$\xF2\xCDR\x91f\x1C\xC7\xCC6\xB2\x89\x82z#\x022[\x99\x07\xFB\xD6\xBA\xABB\xD5\xA6\xD6 \xEB\x87wsO\x92^\xDAs|\x19rTX\xB6\x0F\x85\xBF\x04\xF1\x94f\xDB3\xB8\x83\x95\x8E\x8A\x9D\xE7\f\xDB\xEA\x94\x8Fu\xEBk\xA5\x86-\x91\xAC\xF5E\x0Ex\xE4V': '',
  '\xAE\xD19\xA5\x9F\xCA\xAD?B`\x17\xF2\x0B\x15\x1E\xA3\xDE\xD3q\t\xA5\xF8\xC0\x1C\xF2\xCA\xDE\xC4\xA9\x86\xD9M\xFA': '\xF8\xD8\xC6p\xC5i\xBA\xC9\xE4l\xEDn\xB6Y1\xBD\bZ\xF4o\x17\x86\x07\xBE\x0E\x8E\xB7-\xE6\xCD`Q\x05%\xB3L\x7FL\x85\x0Bt\x9A~\x11H\xC7\x84\xC8\f\xFF\x1Aw\xC7\xBE\xB4\xF8\x05K\xE9\x9E\x99\x8A\x0By\xF6l\xC7#\xB8.y"v\xD8\xD0\xD20\xC7q\xCC\x0B\x03\x99\xCC\x04j\xA9tx(\xE5\x9E\xC4Fs\xB0\x9B\xFD\b5\x04\x1DQ ',
  'Y2\x96\xF0\xBB\xC94\x17#"\xBE,\x83\xCB': '\f\xFF\xBD\xCD\x07uA1|\xF0\xE5\xDF6\x10Z{0\xC0.g8G\x05\xB8\xBC\x8F@\xD2\xE5\xD0~\xB2\xA2{\x1A\x1Fr\xF0\xC9\n\xD0\xB5\xCFVR\xD6\0j\x8C\xC1{\xE0\xD4\xCD?\x92\x99\xD3\xA5\x8C\xEB;\x94\xC7u\xCF#\x0F\xB6\x94\xBC\x9B8q\xD7\x962\xB1r^<\xAB\x98\xF3\xA5\xDF\x19,\x0F\x8E\x05\xC9\xC6\xBB\x1A\xA9!\xB9\xDC\xCB\xEE\xD0\xC14Oxe X\xA6(\xA1s\x99\xAC=es\xBBLKh\nq\xCE]$*g\xF6Q\x9D?\xCD\n\x11\x1D 7\xA7\xD8\x12]\xA7\x9E:\xAFR\xF1d\xC2\x0E\fl8\'ag=$\xB3\x15\x83\xBA\xC3\xE46\xA4\x1A;\xE2\xF0',
  'c\r\xBEGv\xEB^\xA8\xB7HW\xE5\x93\x1B\x9E\xA5,T\xB3\x9E!\xF4\xF2c7\f\x12\x9Ew\x8Bx\x85e\x10\0\x8B\xEB\x8E\xB1e\x05\xAA\xFAo\xA2\xDDm\x16\xEF\x8C\x02\x01_s\'\xC6\xDE(\x07n_\xA4>"a\xC6\xABW\x83\x18\x04dx_\x87\xAF\xF0? \xF2<\0 \xA1\xBD\xACN\xB9\x99P\bl\x0B/\xC9\x93A6$\xC7\xA4/\x97g3v\x06M\x9F/\r\xCD\xC1\x12Ru\xD5\x06l-\xC1\xBD*\x8A\x92\xE5\x02': '',
  '\xDC :\xCE\xD1\x0E,\xC5\xBA!j ^\xE4\xDE\xA6\xC9\xAD?\xCB\xDB\x82\x8E! \xC71S\xBDG\0\x01\x85\x162\xFC\xD7$iN\x07\xF5\xCF\xEA; \x93v\xAB\x97\xA0>\xCA\nh\xCD\x99\xA3\xA3\xD0\x15\x05\xFF?\xCC\f\xD4\xB0C\r\xF2\xAA\xEA\xE4f\xB2\xE2\xE1\xE9\x14\x8C\xEF9g\'\xDC\xF8\xDET\x01I\xFC\xFC\xD6A \xF8\xA3\x15\x89\x07\\^\xC2\xCE\x19\x05zo\x97\xA4\nO\xAA\xB6q!\x8F\xF6\x87AVJ\xBE\xFE\xF2c\xD8uW/\x93xu\xB7"z\xB2Z6\x85\xA0\xB4\xBB\xC3\x99\xA3uv\x9D\xE7t\xA19Q\xF0\xAD\xC6\x0ES\x99>*\xED)\x17\x13m\x95\x15\0\xD6\x9Cr\x191\x05\xDA\t\xD4,v^q~\xB2\x90\xA5\x96{sn\xB3\xB1\\\xBCQ6\x99\xB4\x8E\xCDG\x8B\xAB.\xD6\xBFO4\x1Fy\xB5\xF9\xF35\xA6V\xC1\x8B\\\x83Y\\\xF5K\xA6\x11H': '@\xB2r\xA3)\x07\x02\xEA\xF4\xA1\x1FrZ\xC53\x07\f\xA3w\x93\xFD\xB9\xFE#A\x1F\xBB\xEE\xF9\x9C/R\x1E\t\xDEa\xB7)\xD5\x88\xC8\xEF1\x98\xAB\x95\xE8\xCC\x83M\x12\xDB\xAD\xE2\xDC\xB4\x9Bz\x8F\xF3\xCF\xF3d\x14q\x1A\xDCIq\f\x12\x95r\xE8\xCCI(\xB9\\\x94\xA8\x8C\xC6\\\xC0\xECLnt(t Q\x92[\0\xA6\x89n\xBCR\xC0[l(I\xD9\x80\xDDOH9^\xC6\xBE\x94b\x9D\xA8\x99\xA7[\xEF\xA5\xD7^no\x11~\xE6\xA6\xBEJm\xCFe\f\xD4\x1D\xE5\xF0\xBA\x0B<0\xAE \x9E\x95\x0B;\x82\xC8\x022C\x94\xF6ym\x8DA\xD3`\x9C\xAC\xBE\xF2\xA5OKN\xB2`:(\xB6\xF7\xEC\x87<J\xC3\x96\xDD\x96\xF2D?\xCC[U\xF6\xC6"\x05AY\xF4k\xCF]*\xE3\xE3\xBEn\xC1\x84\x86C\xEA[=\x1D\x992\xE0\xD8c\xF0\xF6\x1C\xAA\x8E\x19\xA4\x15\xA2\0\xB1\x88\xFCs\xC1^\xF5,f\xBC\xEC\xF4]\xAE\x17\xF6\xEA\xD4\x01Dl,H\xBA\xF4\x84Tc\x19\xBC]\xF6f\xDB)/4k\n\x13b\xE4I7\xFBD|7\xB6rJ~a\xAE9\x88Ht\x99~\xA8\xDD\xE45\xC7p\x1E\x9A\xD8\xBFUkN\x9B=\xCE\xEF\x91\x19Zi;\xE31\xC4\xA38\x12E\xA35\r\x8A2\x07\x0B\xE9\x86J\xE96\xA30\xAE\x81:\x14f\x85\xB1\xC7\xAE8\xF9,\xEEwg\r\x1E:X\xF9\0r\x8F\x90~\x9Ax7\xF4$\xE5\x02\xBE\xD6Y4\xE8\xF4$\x17s\xEBi\xADh\x06\xC8skt\xAA\xE9\x14\x9D%z\xA8\r|\xE4T\xBB\xAB\x8Bo\xDC/\xEBZ=\x9A\x1C\x144p=\x84\xB6',
  '\xF2\xC3\xDB\xD5\x8CTB\x8C:\xD6\xD3\xA0$\'\xAE\xB1\xF3\x05\x80~\xC5\xAB\x93e\x81C\xF3U\xD5\x9D\xCE\xF7\t\rY@\xEB\x03\xCA\x85\xE5\t2\xBD\xA89CbU\xB1\x9D\xF66_[\xE7\\\x81h\x7F2\xB31\x18\xE2M\xCC\xA0\x9Bh\xA0\x82Y_\x1D\xBD\xAC/\xF5\xE9\xBE\xAAw\xAF\xD6\xDA\x07O\xBC^\xAD\xAB\xF6$\xDEu\xECK\xBFm\xD4>\xD8pG\x0F\xAC\rH%\x88:\x9D\x10\xB7{\x8D\x84\x14-\xD2\xA5\xD80\x80r\x84\xC0\xEA\xDB\xCC\xD8\xA3C\x96\x16\xC4\xE8\x07\x81W\xDA-DYxG"F\xC0\xFE\xD6\xE9,\x95\xA7-\x80)\xB2\xE9\x0FO\xB7:-\x1D\xBAd\0\xDC}J?Q\xE1\xD7\x92~/f\xCE\xF4 ': '',
  ';\x0E|X\x13\x9E\x11\xD1M\xB5\xC6\xFA\xD1l\x95\xA2\x95\xB3\xEC\\ \x90\x8AW\xC9\x80\x1E\xE9\xDC\x8D\x80y\xEC\x91\xA2\x83#\xD2\xA8\xEC\x10\xE2wJ\xAAW\x04\xFD\f\xD3\xEA\x9AE\x9A*\x84\xF3\x7F\x05\xB3\x8D\x82\xF1l\xC9\xB8\xE5\x8A\xD6W.\xC6Da\x1D\xBB",\xCA\x82#\x1D\x9E\b\x06\xEF\xACqr\xF8I\xFC\xFBz\xB5pj\xF2P \xC0\xD3\xD2\r\x1E\x068\xA6\x8Bm\x07a\xFB\xEAK\xD6\x8C': '<\xC2\x9A\xDB\xE8\x87$\x1CR\x83\xE6n/\x19\xD8\xCA\xCC\xA9(\x03\xB6kv-e3\x9F\x9A\x8Ey\xA9\xF8\xA8#N\x8Eu\x01$\xAD\x85\x96\x1E\xBA\x83$\x10*\'\x1A\xB4\x1B\xDB\xF3G\x911J#G\x13\xE4\xEBa\xD9`\x180\xF8\xEF\xED\xEA]\xAA\xFAMy\x1C<\xF5\xDA*\\\xF39(\xD4\xB4\f\xA6`\xA8\b\xCC\xFFb>\x9F\xC6\xCC\xD8\x05\xED\x84t\x7Fy\x8A\xCE\xD6\x99f,Y$\xE3`\x03\xE0\x0E*\x8Dk\xEF/\x19\xE0V\xA5\x17\xA9\xCC\xB4\x80\rx\xC6\x1E\x1BUl\x01IuI0"\xA9\xF0\x9Eum\xB0\xCF\xA5\x02\xFA\xEE!\x0BN\x1194\xB7\xD2\b\t\xABi\xFF\x8B\xBD\xAD\xEF<-\xFB\b\xA7\x87\xB8\'\xAC\xA8\xB3\x1E\xF7\xD2\xCC\xB4\xB8\tkX\xE6sH\xBF\xE9\x90\x1B\xD9\xDB\x86D\x89q\xC4rD5n\xE6\xB2\xD6G\\\x18,\xCBo\xC9.z\xD4Q\xA4\x1B\x1C\b\x12\xBF\bJ?\x7FX\xD5\xFFf\xF2\xB4z\xD2\x07\xCD\x8B?\xD7\xC3A$4\xA5\xC6\x18\xD0\xB5[\x82\x95]G\x98\x12\xDF\xF4J\xCC}s\xB4\x96(\xB8/R|oU\x04Fz\x7FN(\xB9\x04"\xD9#\x92\xB4~u]\xDFz\xE6\f\x89j\xA1>\xCC\x7F4\x7F\xA8TH\x1E.=\xD4\xF1uSI\xA37C\xA5\xA8\xD1*\xF6\xE0\xCE\x180C~iJ\xEA\xFC\x8A\xA3\xA5.\x13\xD1\xD8\xAE\xE7G\xE1\xAB\xB0)\xA2\x89E\x8Ak\x90f2\x80\x9D\x8B\x98IY\xA1\x17\xA0\x93v\xDF<(\x07U\xCF\x18\xD5x\x80\x85\xE8{\xBC\xFC\x1E\xB6\x97L\xC9\xA2\xC4\x15\x87\xE0\xEA\0\x1A\xED\xAFrw\xE2\x05\xF5f\x07Y\xE7E\x96\xC5\x86}C\xF9\xDC\x82\x8A\xC6{Y>\xFCP\x1F\xC32:\xB7\xAC=\xD7\xA5\xD3\xEF\xD5%\xAE\xDB\xC0\xFC\x04\xD7\xA6jw\\y\x924\xDEgwG\xD5\x0B"\x1B\x81K\x96\xC9\xF5\x96-\xF6\x1C\xEE\xCD8"\xC8!\x94U5\f\xBF\xBCr\xFF\x8C\xB1\xDD\xC0\xE2Tr4\t \xBF\xD7\xE0\xA1\x9B\x1Ez\xFA\x85\x8A\xE1\xA2\xA5\xE0\xA3LP\xE2\0H \xA8?J\x13fG\xB9\xA9\xC2\xDE@\x8E\x07\xBD\xB9\xD3\xB6\x90\xB3l\xA6\xDD3\xA6\xE1F\xB1\x05f`\xCF\xBEp\xB3JM3\x80\xA0\xDD%\xCCy8\xA2lW\x81\xFBH\xDE)f\xCF\xC2\x90\x8FE9\x81Y[\xF4\xC3\x98\xA4\xB5\x05jZ\xC8\xC0\x003\xAE\x82\xB5S\x01\x8D\xD0\x0B]U\xED\xE22\xC4\xA2l\xE0\x18)@\xF5\x8FH-L\x9C\'\xBC ^\x96\x0EU$\x06\xA6@\xD0\x0BA\x1Ex9T`h\x93\x10j\xA5\xAF\x15\xB4\xFBy\xC8\xC4\xFE\xB9OU\xD3\xC3\xE6\xF5\x92\x84\x01\x10\x9D\x9E\x9D\x98\x81x\x1B\x85\xE5\xFF\xA3\xD3\x13\xA7C\x89k7\xB9\xBEH\xECV \xFC\xFB\xCC6U\x92\x1AF3S\xFF\xE9\r!\x13\xAFYs\x8F\xD9\xA7\x92\xF0\xB5v\xD4f\xECA\xF6\x96\x80zn\xD7w\xD1\xD1?~\xFCw\xA3,\xED\xB1C<\xEC\xFE\x06\x17z\'t\xEB\xE0\x83\x9C',
  '\f@\x9B\xDAE\xE4\x01\x9C\x10\xE5\x13#\xFD\xDDf\x10\xDE\xEA9\xC4y\xD6\x8A\x8F\x15\n3\xF1\xE1\nT\xE7\xBE\x18\xFE\xACU\x1F\0xV\xCB\xEF\x15I\xCB\x02\xE4\xE7#[\x17d\xC9\xE7\x0B\x1D\xFF/\xB6Z\x1F\x97\n\x99\xC3!e\x8F\xD1\x0E\xD2\xB2l\x10?\xFC\xBE\xC3\xE8\xAD\xE1mZ\x91\x83\x1E\x82Cz\x1B5*xk\xEA\xE8z\x9F\xC3\x18\rD\x06\xE7\x16\xA1N\xBD]B\xEE1\xC8t\x9B\xEF\xC8Q\xBA\t\xE9D\xE7\xDF\xF5\x9E\xE5\xF3y\xCC\xCAN\x9E\x1Bx\xCF\xF5\x0B\xEFm\xB3': '',
  '\x85\x1C\xDB?,\xA4F#\x9E`[F\xE3\xDB\xBC\xAA\xAB\x99\xCD\x8E\xD7Q;\x84{\xF5\xE0\xB7\x98\xE3\x91\f\x8F5\xF9\xF2\xF2K!\x87h#\x16\xF1\0{\xA7\xCE4zJ\xB3v\x9Ehlv\x9B\xDE\x0E\xB31[\xCF\x86Qy\xDA': '',
  'L@J|x\xED\x15\x1A\xCC\xC4\xB3.~q\xA4>\xFD\x99.?\xAF\x9B\xF2@T\xA8\xF5m\xA5\',\xD5\x842C\xC2-\xB7\x99\xB0N\xC1\xEB\x97\xDA\x9B?\xD4y\x86D\x96\xBE\xFC\x0BB\xB9\x12 \x87\xEBl\x1AZ6\xE3/7\x80\x80\xF0\xDCG\x93"\x10I\x076\xDA\x9B\xA4\x19h,w\xBA\f\xC3\xC9\x1Fp*\x80\x02)\xA0\xB6H\xAE\xA5\x92\0\xC50Xr\xABt\x1F?\x1F\xAB)\xAC\x96I\xD9B\x9A?t\x7F\x86\'dKC\xEDn\x9EJ3Bt\x1C;\xA0XQ\n/\xE3\x034\xD2\xC5\x85\xF2\xBAF\xD4"\xF19\x9D9\x95\ro\x85(\xCCy\x82\xC5\xD2\xC8\x9F\xEB\x9A{\xF2\xFF3|\xF7\xF3\xE15\xEE-\x8AlL@\f\f\xB9\xD8\xA8\x83\x03\x12MWx\x19\x81D\xF6\xDE\xB6Ev\xE2\xE1\x03y\xC4*\x90?\x0F\xD5\xC6\xEF\x1C\x96\xE8\x9C\xE5w,u2\r"\xA2\x16N\xB8\xFFtM\'DY\x8C\xD9\x9C?e\xA2YW\x93\xEA\xF5%\xD2\x87\xF0\x99\x05\xA6B#) Z\xA8\xF9\xC2\xC0\x05\xF4\xDC\x90B\x17\xF7\xFDDd\xD2\x1D\\\xD6\xFC\xE1bA\x98\xDD\xFD\xC4P\xB7TTg\x14\xC1~1S\xDD\xAE\x02\xE2\x1B\xB0w\x9FC\x07\xC5\x84\xE8#\xD8[\x19{\x12\x82\x9D\xA6\xFD\xDF\x88o\x96\xFD\x98\x1D)\xFC\xFA\xF7\xCE\xC0_\x80m\x8F*S\xE0\xCF\f\xE3\xDC,A\x97qi\xA4\xC3\x1A\x80\x01%\x9C\x90\xCB\x97\xE8\x97OTF\xA4\xED1w\xC7Dr{\x15(\xA9b\x1F\xE1\'L\xE8\x8D\xD1\0<\xB4\x93w\x9B\x1F\x99?\xA7\xEB\x91\xF8\xD8\x13F\xE5\x9D\x02A\xC8\xFE{p~\x1F\x81\xFA\xF1\xFC\x84\xC5\x186\xA5L4h\x9C\xA4|w\xF0w!\xF2\xF9': '\xBE#zb=\xEB_v\xBBYro3\x16E\x99d=\x91\t\xB4\x84F\nj\xA1\x85\x19\xEDT\x93r\x1A\xC5\\\xBB\xE3*E\xA8\xFBw\xE1B%k\xBE\r\0_\x10J\x14\0\0\0\x01\0\0\0\x14\0\x05\0\x10\xAF\xC8\xCF\xED#P/'
}

response = requests.post('https://drmtoday.vieon.vn/license-proxy-widevine/cenc/', headers=headers, data=data)

Can you help me this error

![Untitled](https://user-images.githubusercontent.com/86090065/145717837-cd8b4b0b-6db8-4624-823c-60fb6fa7c0c3.png)

Thanks!

**Comment by medvm** [comment]
update file headers.py

**Comment by davidjames146** [comment]
Hi, thanks for reply,

I already added headers.py with site i want to download.

Vào Th 2, 13 thg 12, 2021 lúc 10:28 Mikhail ***@***.***> đã
viết:

**Comment by medvm** [comment]
I meant download new file from repository. [Works for me](https://user-images.githubusercontent.com/43696206/145748900-8ac96aa9-263d-40ee-8cee-9979c11c6165.png)
