### ISSUE TITLE
l3.py

### ISSUE THREAD

**Issue by larsk2** [medvm/widevine_keys#22]
Thanks for your work.

Few questions since I'm not expert here.

What is 'token' ? Is that the cookie?
Where do I find 'priovider' and where do I find 'releasePid' ?

also, i get this error message:

license response status: <Response [200]>

Traceback (most recent call last):
  File "C:\l3.py", line 102, in WV_Function
    if widevine_license.content.find('{'):
TypeError: argument should be integer or bytes-like object, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\l3.py", line 121, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "C:\l3.py", line 107, in WV_Function
    license_b64 = json.loads(widevine_license.content.decode())[key]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 3: invalid start byte

**Comment by medvm** [comment]
Whether or not you need to fill out the fields you describe depends on your site. For testing purposes, I need to reproduce the error you are getting. Send your inputs and output of the "copy as curl" command here

**Comment by larsk2** [comment]
Copy the POST licence as cmd curl and post it here you mean?

**Comment by medvm** [comment]
that was fixed, but readme
