### ISSUE TITLE
sometimes working? sometimes not working!

### ISSUE THREAD

**Issue by catiscatcat** [medvm/widevine_keys#23]
### [coupang.com](https://www.coupangplay.com/)

![1](https://user-images.githubusercontent.com/67657593/145769990-0dc6d577-288e-48c3-8707-8d6a30ee5f10.png)
**python 3.10**

![2](https://user-images.githubusercontent.com/67657593/145769995-740b5c5f-cf02-427b-aaef-7799f1d940ea.png)
**already done**

![3](https://user-images.githubusercontent.com/67657593/145769996-b37a48c4-3944-4bad-8f92-19a1e9627fc9.png)

![33](https://user-images.githubusercontent.com/67657593/145770003-faa52996-c6ff-4989-9f35-0f2937324f91.png)

![4](https://user-images.githubusercontent.com/67657593/145769998-f3388afc-bad3-4c31-b2c3-ae46bbb31acc.png)

![5](https://user-images.githubusercontent.com/67657593/145769999-e3ebdf6d-4726-4bf3-a8ab-a2af5f552178.png)

![6](https://user-images.githubusercontent.com/67657593/145770001-d6dda6f4-d728-48b0-95e9-dae7f7b4e4be.png)

What's wrong?
am i some mistake?

**Comment by catiscatcat** [comment]
![11](https://user-images.githubusercontent.com/67657593/145780590-810f4e9a-49f1-4c0f-9701-7702c9b3524d.png)
working on python 3.8
and
Error msg

**Comment by catiscatcat** [comment]
I've tried several times.
Sometimes it works and sometimes it doesn't.
I don't know why.

**Comment by medvm** [comment]
apparently, the license parameter in the license_url is generated dynamicly, later I will add support for your service
