### ISSUE TITLE
Where to find provider and releasePid?

### ISSUE THREAD

**Issue by Martin-40** [medvm/widevine_keys#24]
Where do I find the values of "provider" and "releasePid" when I check in Chrome F12 Network? The site I want to download from is [https://www.cmore.se](https://www.cmore.se)

I also wonder, the value that should be entered at "token", is that the same value as in "x-dt-auth-token"?

**Comment by deepblue2000** [comment]
yeas what is the release pid ?`

and token is for me: 'x-auth-token': 

so I have to edit this line... but releasePID is nowhere

**Comment by medvm** [comment]
This is just additional data for some VODs. You can leave it as it is, it doesn't really matter.

**Comment by medvm** [comment]
I'll add support for cmore.se later (maybe at xmas)
