### ISSUE TITLE
need support please

### ISSUE THREAD

**Issue by hmnytv** [medvm/widevine_keys#25]
I need help with something

**Comment by hmnytv** [comment]
Input MPD URL: https://mbc-aws-ksa.mncdn.com/out/v1/c1391fc8b00e46bd87af6337d29199ca/c96d37fedb44465f8a19c65563004303/2702b4dd304c43e88bcfa4f04f464736/manifest.mpd?aws.manifestfilter=video_height:144-1080
License URL: https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEuNjM5NDQzNzI0RTksImRybVRva2VuSW5mbyI6eyJleHAiOiIyMDIxLTEyLTE0VDAxOjAyOjA0LjAwMDY3MyIsImtpZCI6WyIqIl0sInAiOnsicGVycyI6ZmFsc2UsImVkIjoiMjAyMS0xMi0xNFQwMTowMjowNC4wMDA2NzMiLCJleGMiOnsiRmFpcnBsYXlSZW50YWxEdXJhdGlvblNlY29uZHMiOjg2MDAwLCJGYWlycGxheUxlYXNlRHVyYXRpb25TZWNvbmRzIjo4NjAwMH19fX0.HJN5ZSQlapN7LVTYzZPTHaDgGJRSuQYkbKkRx4FY0zM
Unable to find PSSH in mpd. Edit getPSSH.py or enter PSSH manually: AAAAZ3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAEcIARIQtPV33gqpQJqUloRUb15aeBoFaW5zeXMiJGI0ZjU3N2RlLTBhYTktNDA5YS05NDk2LTg0NTQ2ZjVlNWE3OCoCU0QyAA==

PSSH obtained.
AAAAZ3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAEcIARIQtPV33gqpQJqUloRUb15aeBoFaW5zeXMiJGI0ZjU3N2RlLTBhYTktNDA5YS05NDk2LTg0NTQ2ZjVlNWE3OCoCU0QyAA==
Traceback (most recent call last):
  File "D:\widevine\widevine_keys-main\widevine_keys-main\l3.py", line 130, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "D:\widevine\widevine_keys-main\widevine_keys-main\l3.py", line 52, in WV_Function
    data=f'token={headers.token}&provider={headers.provider}&payload={str(request, "utf-8" )}'
AttributeError: module 'headers' has no attribute 'token'

**Comment by hmnytv** [comment]
curl 'https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEuNjM5NDQzNzI0RTksImRybVRva2VuSW5mbyI6eyJleHAiOiIyMDIxLTEyLTE0VDAxOjAyOjA0LjAwMDY3MyIsImtpZCI6WyIqIl0sInAiOnsicGVycyI6ZmFsc2UsImVkIjoiMjAyMS0xMi0xNFQwMTowMjowNC4wMDA2NzMiLCJleGMiOnsiRmFpcnBsYXlSZW50YWxEdXJhdGlvblNlY29uZHMiOjg2MDAwLCJGYWlycGxheUxlYXNlRHVyYXRpb25TZWNvbmRzIjo4NjAwMH19fX0.HJN5ZSQlapN7LVTYzZPTHaDgGJRSuQYkbKkRx4FY0zM' \
  -H 'authority: drm.cloud.insysvt.com' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Microsoft Edge";v="96"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'accept: */*' \
  -H 'origin: https://shahid.mbc.net' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://shahid.mbc.net/' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-raw $'\u0008\u0004' \
  --compressed

**Comment by hmnytv** [comment]
import requests

headers = {
    'authority': 'drm.cloud.insysvt.com',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Microsoft Edge";v="96"',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43',
    'sec-ch-ua-platform': '"Windows"',
    'accept': '*/*',
    'origin': 'https://shahid.mbc.net',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://shahid.mbc.net/',
    'accept-language': 'en-US,en;q=0.9',
}

params = (
    ('BrandGuid', '2be49af0-6fbd-4511-8e11-3d6523185bb4'),
    ('UserToken', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEuNjM5NDQzNzI0RTksImRybVRva2VuSW5mbyI6eyJleHAiOiIyMDIxLTEyLTE0VDAxOjAyOjA0LjAwMDY3MyIsImtpZCI6WyIqIl0sInAiOnsicGVycyI6ZmFsc2UsImVkIjoiMjAyMS0xMi0xNFQwMTowMjowNC4wMDA2NzMiLCJleGMiOnsiRmFpcnBsYXlSZW50YWxEdXJhdGlvblNlY29uZHMiOjg2MDAwLCJGYWlycGxheUxlYXNlRHVyYXRpb25TZWNvbmRzIjo4NjAwMH19fX0.HJN5ZSQlapN7LVTYzZPTHaDgGJRSuQYkbKkRx4FY0zM'),
)

data = {
  '\b\x01\x12\xD4\x1F\x12_\n]\nG\b\x01\x12\x10\xB4\xF5w\xDE\n\xA9@\x9A\x94\x96\x84To^Zx\x1A\x05insys"$b4f577de-0aa9-409a-9496-84546f5e5a78*\x02SD2\0\x10\x01\x1A\x10l\xDE\\1\xCF\0X\x0E~v\xF1\xA1\x1B\xA6\x8EP\x18\x01 \xE2\xD7\xDF\x8D\x060\x158\xB3\x93\x98\xAC\x0FB\xE0\x1E\n\x14license.widevine.com\x12\x10\x17\x05\xB9\x17\xCC\x12\x04\x86\x8B\x063:/w*\x8C\x1A\xA0\x1C\xF7\xE8\xC4\xB0#\r\xB4\xA2O\xBA\xA0\xE8\x90#\x85\xE5\xD9v\x84Sw\x17kVr\xF2\x9B\x0E\x19\xF2\x93\'x\xAD': '',
  '\xD7D(\xE9\xF7\xD1G\0\x15\xB1b\x8A\xC6\xACyz\x9CjtQ\xF5U"\xC8}`\xAF/\xC5T\x9D\xE2\xE0D*\xAAX\xCA)[W\xEA[uZ~ Ie4M\x1B\xCD\xE4\b\xCE\xB2\x02\xE3\xFC\xA3\x16\x0E`\xB3\xCC\xF8VU\xE1\xAE3\xF9\xEE\xC1\x8C\x84\xFE\x87\xB3\xC4\x93x \x9D!\xB7\xAD\xD9~Z\xAC\x0BED\xC0F[tZA\xF59\x01\xE601\xC7\xB1\xC1#\x05(\x05#\xFA\xFB\xA3\xEA\xEB\xEF\xA1\x03z\xD0CR\x87\xEC/\x91\xF6\xF8\xEB%\xE5t\x07\x9FB\x0E\xAEOif[\xFD\x02\x91I\xF3\xF5\x8E\x88\x90\x85r:\xCDE\xCE\x9E,\xB2\x83%\xC2\xB9\xF6\x0F,\xC9v\xE3y\xD3\xDF\x01tu\x85\xBA\xE7\x88w9\xD6\xE7#\x96$[\xAB\xFB\xFC\x93\x82\x84\x8F {\x9B\x07\xC0\x81\x1AB\xA0\xB6\x87\xFCH\f\x06\x86\x90\xDB\xAA3\xF2\xDC\nG\xE4\xC4 \xAB\xB2-r\xF1\xEF\xEE\xA4\xB4\x86;I\x88j\xA5\xFEj\xE5\xEE\xFEf\x7Fv\x04\x82\xCCahl\xAC\xD9o-\xDCz\t': '\xDB\xA42\x96\x16\x0Bg\x15\xA1\n\xAE@P\r$[\x99Mu\x12Z9\x86`\xAD\xEB\xE3\0\x07\xC5\xC3\xE5\xBA\xD4\xF1\xE6il\x0B \0\x7F\x0F\xEA\x9A\xF9\xEB\x9F\xAA9m\xFF\xC3\x05 \x97\x07\x88\xFD\xBC\x97\xBB\x96.\xAA\x14\x9D~\xC4\x1EG',
  '\xE5\xDF\xBD\x9CyA\xA5F\x81\xC9.Q\x92\xD9I\x01p\x8E9\xC06\x19\xE9g1\x1DM>\xA7g\xF3B\xB2\xE7\x8C\x1A\xAB\b\xB0\x91 \x04\xF5\xC0P\x0B\xE5\x14\xB0_~`qmg\x923:Uj\x06\xD1\xD3!#Q\xF2\xE7\xB6\x99\x0BC\\\xAC\xF5\x12\xBFwZ2)wZ\xC8\xFB\x9F\xCE\x11ZK\0\x8B\xBA\\7\b%e\xF9J\xF2o%y9\x189\x80\xA4v\xA9\xFDa\x82\x1F7\xFC\xAD\x19q\xB3"\x16\x1AXjA.P\x05\xAA6 k\xA0\xE8\xF1"\xB4\x06\x1F\x8Fg\x97N\xAFBn\xD0.\x06\x92\xD2\xAFO<\xA8\x0B^Yw\xF3\xB0v;\xADsi\xE3\x96\x90h\xA4\r\xD2:7\xC4\x0E\xADc\xE2W\xEE3\x83\xD0\xD3\x9A\x9C-?{\xC0\x07\x9B\x07\xA5D\xF5\xCD\xE0\xF1Y\x9F\x9E\x89\xD4\xD8\xC3,.\x16\xD7\xDF.\xD2\xFC^mq\x18\xD8\x07y\xFA\x89\xFB\xC2\x07\xFD\xD8A\xAE/3\xE54\xB6\xF2\x02\xDD\xD6\x87\xE5\x1C\x95\xD7\xD3\xE0R\xB4\x9Dr\xCB\xB1\x10\xC6dN|\xCCB\xB6-\x11\nQ\x80\xB9\xE9@o\xEA<0\x90\xA7v\xF0\xF6\x95\x0ES\x88KV7\xC4\x97\x01\xAC\xE7_\x16\xA6DU\x9A\x94p\xFC\xA28\x82\x9E\xD3FQ\xF1\x80\xD7\xB3Gf\x90R\x19Qa\x0F\xCB\x1C6\x16O\xDF\xD5\xD5U\xED\x10\x9C\xAF\xC8\xFE\x16\xEC[9W\x0Ed8v\x84\x9D44m\x89\xDD\xF2\xA8\xE2|\x86\x8A\xD9\x12\x07\xCEvG\xE1\xEC\xA9\x0FA\xCB\xA9bV\0\x97v\xC2\x1B\xBC%\x02lf\x81x\x98\xB6~<J\r%\xDB:\x88\x84l\xD8\x1B\0z\x84\xD7N\x1B\xDF\xAD\0E4\xA7\x9By\xD0\x80N\xED \x86\xAD\x9By\x10\xBFXr\x85\xE6\'\xC3\xC2\x1D\x14\x8E\xCE\x10$~\x91\x85\x1C\xE1S\xF9\xAD\xD7\xB0FC\xEE\xEF\x93\xDB\xC2\x04\bdT4>\xB6\xAFc\xD6\x0F\xC1\xF3>F\xFC81\xAB,[e\x05\xBF\xCAF(}\xBDJQ\xB0\x0F\xC0\x8D\x87\xF3\x8D\xF6\xFB\xC4\xBD\\\xB3g\x0B\xA2\x17\xF9\x84\x9E\x1B\xE1\x1D\x04\x7FC\x99z\xD96\xEBb\x94\xD7\xC2\x98e\xA2\x01\xE1r\xBC\x01q\xF9-\xF6\x1A\x9B\xCA\xCF^\x0B\xD5\x83\x95\x19p\xC5U\xA0x\x07\r\x9F\x0B@^\xF5\xE56%\xD7\xD5\xFB\0zBm\xC7\x01*\f\xAAZ\x92#.)l\x1A\n\xFD\xBF\xB4O\xC3[\x8Fb\x14\x88\xB2\x9FsU\x1Bn3\xAF\x89?$\xFD\x96\xA2\xB3\xA6YH\x16\x8C\xFC\xF1<\xD7\x99\xFF\xA4\x8D\x0F\xF8\xAC\x1A\xB7|##\x1B 8p\x99\xB0\x0BQ\x18\\\xF7/\xA2\xDCz\x18\x86\x99m\xA1iJm\x8D\x17\xE5J\xD4\xE9\xA8\x92\x91\xBA\xAC\xE9[\xD1\x161\x0B\x84!d>\xBA\xE6\x1C': '',
  '-8\xA3\x85\xF3\xC8Y\xBF"E\\\x1Ba6\xEE\xE3\x95\r;O?\x9Ejg\xD0\xB4p\xF5%*\xB9\xA1\x81\x1A7\x98\xE4b\xC6u': '',
  'G\x1E\x82a\x80': '',
  '\xEBm\f\xC5\xC6\xA2\xAEc\x8B:\x97\xD1\xE2q\xE0\xDC\xAB\xE6\xA2x\xBAu\x16\x04^\xB7\xE6$2\xD6\xF8m\xD0\xB5\xFD@\x18\x18\xE94\xB8\xE0\xE6f$\xC6\xBE{-x7I~O\xC7\xCC\xE54\xFD\xB0Q\x1D\x16\x8Ed\xFE_q\xCA\x85\x04_\x81\xB7\xB2v\xCA\x02\x12\xBE>\xCB\x93\x17\xC1\xBE8\xF82\xCC1\x04\x1F\xB8\x13': '',
  '\xB9\xDE\t\xA4\xFF\xC6\n\xBE)\xB0\xB8\xD6\x84\xD2\xDAq\x99\xD8\xFC_*Y\xACm\xA5$%R\xFE\xA4\x8D\x97~7\xB2\xC4\x193\xB1\xC0\bI\xE7O2e\xFC\t>)\xD2\xCB\x1C\xA1\xE4N\xADs\xEF[\t5(r\n\x13\xA3|f\xDF\x95\x03\xE8V\xAD\xB3\x96\xA4e\x87G \xC6\x1C^q\xE7\x03\xAF\xC0<\x92\xD8N\xDD\xFC\xC6\x8F\xDA\xE0k9\x8C\xFFIWP\xB1\xCB\x1E.\\3\x87\\t\x10\x9C\xF4\xF6\xB3\\"u\xDD>\x13\xA5\xD4h<B@\xD1jA\xC8\xA9f\x14\x10\x9C\xC0/\xEB\xB1\xB2\x92\fj\x05\xE2.2 \x12\xBC\xAF)\xFC<J OPe\xF4\xA5\xFA\x06\xF3\x13\x15s\x04\xF1\xA9#\xD9\xCA\x94;\xBD\xF5\x1A@@Q\xED9$\\\xED': 'x\xAD\x06\xF2\xDE\xBF\x0F\x92\x94\xC2q\xFA\xF5\xA5J\b;kv \x8D\x9D\x1DH]\xB3\x8A\0\xD1M\x03V\xA3\xF1=\xA4\x16\xE6\xA2,\x13\x14\x18a\xBA\xA0\x95\x8E%@`\xFAB/K\xEC\n\x0E\xA7\xD2\x8As\xA0La\x01\xAB\xAF\0e\xC6uk\xB0\xD2\xCE1\xE6G--\r$!{\xA6\x9F\xB0\xC2rF\xD7\x0E\xFB\xD3"\x8C)\xD2\xC6\x99.\xDCZw\xBC\x89S\xAF\xB9\xF5\xD3\x91\xA0\xB4\xD9\xC40M\xD2(\xB5\xC7{\xF1_\xA0Wb\xA1\x86\x91"@S}\xD5\xCF\xCEk\xE8\x13g\xBB\x9D7\xAC\xF4\xDF`v\xDA\fEo\x98\x10\xD5\xA2\xD4\xE6!\xC8q\xC7\xAC\x0B=l|\xC6\xAC:\xD5\x18q?\xC3W\xC2\x16\xA7\n\xDD\xDE|\x85\xC6\x14\xD7\x8F\x11\xC7\xD3\xFCs\'}\xE6\x96\x10Y:\x14\xC02\xAA\x91A\x7F\xB5\x02A\x8C\xE4 \x17\'\x03\x97w9-\x86\xBD\x1D\x8F\xD58\xEEz!\xFC6\x011\x07\x06\x85\r\xE3\x96\x1B>E\xBC8\xD3\x8Fmv1f^\x90\x9F\x07\x1Er\xDE\x1B\x94\xF5f7\x8D\xE1\xBA_l\x1D\x81\xC7\\\x96c\xE5\x13N:4\x16\xFA(\x8F3\xD5\x90\x17\x8C\xF6\xAE\0\x95]\xE2\x02\x87\x07{[\xDE*<\xD2\xA9\xD1/\xF9\r\x91vS\xC7\xF4\xC2\x8E\xEF\xA7\0\x7F\xA6\x88e\x9D\x9Dj\x80\xCF\x8B\x13\x17W0\x18U\xA6\xF1t\xD1\xAF\x85J\xD8\x8FW\xF3U\x94\xA6\xBF],\xA3\x85\xB35\xBC(\xAA\x87\xC46',
  '\x1C\xB1`D\x17\xE2Zf@\x959\x04[\xFA-V\xDC\t\xB7\xC0\xF0\xECQ\xF2\xF3': '',
  '\xD1C\x93\x10\xCC7\x8C\xCF\xAE}\xA9\x89)>9\xFEC\x95\xE80\xB0 \xC4z\xA9\x04\xB0\xB0p\xA7\xA7\x17 \x15N\xA7\x81\xCDg\xB3\x82.\xF3]\xD3My\x07W-\xBDG\x83\x90}\x1Eb)(\xC2\xB0K\x06*\xA9(1:\xF7\xA9\xD0\xB8\xE6\x84AW\xF3\x8D\x02j\xCA\xEF4/V\xAB\x1E\xC4F\xF1\xD6\x9D)9:\xFB\xEE[\x92\x11\xBC\xF7\xBC\xB3\xB9\xAE\xCFUa*\xAC\xA2\x91\xB2\xD5\xA2_\x9D\x07\xE9,\xDA\xCDSV\x931\x01\xFF\x13ek-\x01\xE2\xB8\n\xE87 4\xB0pj\xB2\xAF\xF9\xB8\fxU\x1F\n7e\x02\x7F\xCA\x90\xF0\xDD\xBD\xBA\xB6^\xBCS\xCA\xCD\xCB\xA8\x92*cD\x02\x17@X\x03\x9C\x9DT \xF9\xE3\xD0\xCE\xA1\x7F2\xC2Q1\xB8d\xECD\x10\xC6\xFE)n\xE2\xD8\x1F\xAF \x94;\r\x13\x06;\x13\xF4J\x04\x1D\xF0\xAF\xE5\xB4\x14\xC5\x96Y\x0E': '\xB6\xE3w\xB8\x01B\xC2\xD6=\x95\x80\xA0B]\xD1\x1C',
  '\x8F\xDD$\x94DG\xFF\xEDn\xEE]< \x17\xC6': 'W\xDFc\xEF\xB0p\xC5L\xD4d\b\xF3 Z\x8D\x16`Lt\xF2\x17\x80}\x9D\x99P\xB81 Ig\x0E\x98\xD9zE\xE3\xEE\xDF\xBFs\xF8\xEA\x83\x16\xAC^\xE0g-4hh\b\x82\xDC\r\xD8":\x84\xD5\xF9J\xBA\xFF\xA5V\xB9\xE37{z3\x9A\xC1;\x92\xCB\xE6\xFF}e\xF9\fb\xC0\x10k\xADo\xF1z\x9FQj\x9A\xE4\xB3|\xD4\x11M\xF2\x99\x02\x02t\xED\x1Cr\x1D\x14\xA0E\x8F\xEDW\x0B\xDD\xB2Rrf\xEC\xE8\xD3\x82\xBD\xD1\x19$\x96\xD6\xDC\xB9\x90\x0F\xF2\xF8\xCE\n\xBC\xEE\xD50\x1B\x81J\x1C\x11\xA1\x07\xF81\xB8eM\x19\xFB\x8A\xF5\x07E\0\xA8\xCD\n\xD0\x1C/\x99jo\x8E@`\xF6\xBBH;\xF5\xADd\x90\x85\x96\xA9~\x94\xC6\xDA\xA9\x04\xC0\xFE\x97\x01x\xCD:78\xFELn2:\x90\xE3\xE1N \x13\xD4\x1FW*\xBD\xEDp\x8F\x0F\xDC\xDEy\x1F^P\xAD#J\xBD\x8A\xF1\x90\x01\xFF\x89',
  '\r\x8AqI\x14\xFD\xC9\xF9\x90\0\xBB\x85\xD6\xE3\x02\x03\xFF\xAC\x84\xCA\xFE\x14F,\xF63Tr51LN\x0B\x032"_y\xC6G-*AM\x8C\x8Co\xE3f\xC1\t\x9Bb4\x98LmE\x83xLL\xBA\xFE*|k\xE5\x8D\xA2B\xC4\x16\x9Ce\x06\xC6\x0E,\xE2\x94\x15\xD8.8zhe7\x991\x1C"\x11\xBB\xB1\xC6\xF5{a\x92T\xFF\xB2\xAE\xDB\x89!\xA3\x97TR\xE9\xB5\xF2\xC4\xB6Rn{\x10\xD3\xBC\xA7\xF3\xD6$\xD6d\xAF\xCAII': '',
  '\xC3l\x12D"4\xE0@M\x81\x87\x128X\x18Y\\d\x8B\x10\xEAP\x9Ae\xDB\f6)\xA0\xFA|\x06\x88\x94.\xD25O(?\rN\x16:B-*\x85\xC2\x818#\xA7\x02\xFA\xCA\xC8\xC158\b,#_\x1E\x8C\x97\xBD\xF5\tJ8\xADEB9d\xC0\x92\xA1\x12\xEEn\xB4\xE5\xC5-|E2\xC9\x9B\xBD\x11\x9F.K\xBB\f\xD6\xA5\xA5\xFB\xFA\xCE\xED~\x189n\xFC\xF7\xA4\x85:\xD9\xD4\x7F\xCC\x81L\xF7\xA1Q\x98\x0Bz\x8CJZy\xED\xD5\x94\xFE\x80\xF7\x18\0\xFB\xDA\x15\xFA\xF1\x8C\x8D\xBD@^X\xE0(\xA8\xC4\x02\xCD\xEF\x0E\x9A\xD8\x93\x18\x17\xCDC\'\xF3\xC4\x9F8\xA1x\x81\xB0B\xC4.\x06\x8F\x96\x89\x97\xDAD\xF2.\xC4\r\xE0u\xD2\x9E \x951n\xD9\xFCu\x89\x1C\xD0\x96,\x8A"\xBDF\xBEg2\x19\xE1\t\xD69F\xE1\xA1\xB1\0\x1C\xB5\xA0\x02Z\xC9\xBB\xAD\xC1\x0F\x8A\xBE\x87f\xF8V\xA2\xCF\xC5\x01\'\xF2\xA0\xD2\x18)\xBD\xEB\xF8\xEDH\xF3\x10\xD4I\xB7\xBC{Yw\\': '',
  'R\xB8OTK68Is|\x88\xC8\xF9c\xEF\xDBK\xAA\x86itQ.\xB0\x16d\xD8r\xA2\xA9\xA2\xA3\xD8\xF36@\xE2\xF49\xDEd54\x9F\xD3\'\x04\xFC\x81\xC2\xE3\xA0|\xFA{\xA0\xC7>\x18\xE3\xE7\x8E\x86\x80/\xF4#oe~\xBEm \xC7\xF5\x8C\xC3\xB8\xE1\xCE\x03l\xB82K\xC3\xDD{\x0E\xF3v\x1D<5\xB7\r}\x83\x8A\x05v\xD1\x0E\xBE\xEE\x124\0\xE8U\xFC3\xE8\0\xE4k\xFF\xC9\x18A\0m\xD7\xC9\xB7\xAAw\xEB!oq/:Us\xF2\xEFf0b\xB8\x11\x0E5\xF3\x8F\x91\xB7\xAB\xF1\xDE\x1A\xE5\x9B$m\xF5) ;I.i\xC3\x19FZxg\xF0\x9B\xD1\x1FA\x1C\xAA\xC6\x80^U': '',
  '\xA2c\xFE\x9D7\xAB\x1E]\x9C\xB6\x8Cz\x17U': 'y\x01\'\x13\x90\x1A`\f|\xDD\x80\x91:\b \xC6\x180\x96%O\xC9\x11mn\xF8n\x04yn\x9Fu\x99\x19H}\x7F\xDAtZ\x94\xCC\xC3\xA1\xBE\xF5f\xFB\x9F\x06I\xC6\xC4U\x8E\x86\xC4\x86M/\xBAiy\xC7,\x01>w\xD2\x89\xA7`Jy\x84\xEBj2vI\x93o\x88}G\x01\x1Fx\x99\x07\xC9\xD3\x83\xC1\xA1B\x82\xA2\x7F\x8BL\xEBw:\x9F\x1B\x92\xAD\x99\xCB\xBD\0\x91\xD8H\xC8\xAF#\xA1\x96Ag\xC8\xC8\x19\x84\x8D\xECc\xF4v\xC2\x93\xA1\xF3\xAA\xBE\xFCUS\x88\x96:\x81\xE3\xBD\x97[\x87\t\xF7\x16<l\xE8\x11\xBD\xA7\xC1\x0Bc9?F\x94\xB0\x05#\xA2\xD9\xFD\\G\xAC\'\xFAx4\xC9\xEF\x17\x8D\x18\xAF)-\x11UJ\x9C\x99\xB2\xB4\x92g\xBDKg\x9B\xAF\x98\xBD\x1F!\xB5\b\x8Bezh\x8D~%\x88\xB6\xA9\x81\xACU\x11\xA2D\xC1\xD3c\xD1\x8C\x961\x92\x88?Z\x8C\x9B\xBE\x14\xB8\x89^\xC3\xD2u]\xF3\x02 \xFC\x14\x9D\x93\fCy\x99\x81\xDB\x86^\xDBR\xCB\xDE\xBF\x04\x16_f\x1D\xEA\xBF\xA8\x0E\xD1\xC9\r1e\x97\x1D\xE2JqV\\Z\xED\x0B-\xA6\x86\x92\x97\xF8mX\x92.\xB08\t\xF9]\x06\xEC\xEFE\xEE\x99\xFF\xA3\xEAsg\xF9\xD6\xD44\x8D\xF5mT\x84\xFB\xB0\xE2v\xC2\x1D\xAD\x98\xC8\xB5j\xEB"M\x97\xC6\xF4\xA3Z"\xAEPo7\xBE:\xDA\x93\xF2x\xDA\x13\x99\xA6 \\\xBC\xAE\x12\x03\xB5p\xDF\x12\xE0\xD39\x04\xAE\xD1c|\xC4\x06\x9EDR|\xC7\x19\fd\xF3\xD07\xBC\xAF\xDB\xB1\xF7\xF9@\xCD?\t\x9D\n\x93\xA4p\xED\x92\xBF\xBAl*r\xDB\xD4\\<\x18\xE0\xFA\xFC\xDE\xA0\xC1\xBDQ\xAAZ\xC3{)\xB4P}n~f\xE5~Y\xBANJ-\x06=SE\xAC\x90\xA6J|\xC0\x1D\xB2\xCC\xEDO\x81<\x1E\x99\xA0\x93\xAF\x1A\xB5W\xEEbD\xA4\xAF\xCE\xA8\xF0\x05\xE5\xE8S/;\xE3\xE2\xCBtl\xB5\xBB@\xAF\xF5\xFE-\xC8\xB4\x16\x13\x1A\xD03\xB9r\'M\xF7Rv\xEE\xFA}\x90\xE4u\x939\xF5\nN\x979\xAD\xD7\xB9N3\x97_7\xE0\xFFAl\x98wW\xBE\xC6G\xA5k(\xD1)\xF1\xFB\xD3?K0r\x94\b\xB2("\x94<\xBB3[\xAD\xB0\xD47\xC5\xC9\x19c\x86\xB8g5iG\xC3\x97\x8E\xE5\x81\x1E\x9FR\xF2\x90\x1C\xB4\x7F\x87m:68\x04\x03\x81\xA1^\x11~n\xAD\xC1\xE0\xAE\xA8?\xEEI\xD6\x11m\xCF\r/[\xAC\x87Qf\x8Ex\x83\xEB\xAF\xE8\xD8\x10\xC7H\xA3\xBC\xBE\xBD\x90\xB4D\xB0\xED\xEAq\xB3\xC1\xED\xD4\x90\xCF\xAFAw\n\xB8K\x06T\xA0eb:\xB59\x8A',
  '\xFF\xBD\xB6hJN\x19\x80\xA3\xEB\xCD\xDBS\xF0u\xD1\xEE\xC4\xF2\xA4\x1C\x85\xA2@\xF7\xC0\xE6,.}\x92\xDE\xE7E5\xA5\f$\xEDe\xEF.5a{k\xE9\xF9z1\xDD!\x94(?`\xA4Kw\x7Fb\x81\x81O "\xDD\x14\xD7\xB0H#\xCA\xB6\x87\x1B$\x9FlL\xCA~*\xDD\xCEB\xF9\xE3-\xF0\x9A\xBF"\x10\x83p~\xCF\xA5\xAAH\xCA\x90\xDB': '\xB3\xE5zl\xDA*\x80\x02T\xD9\xC6\xDE\xC2TJ]\x1F\x15\xB6\x8C\xF1\xF6:\xC2\xCAk\x86 \xBBr$\xE1\x98\xC6\xE3VU\xF6b\x07\xF2U\x05\b.\t`5\0\x9B',
  '\x89\x86\xE1G\x1A\xCF\xEDr\xC2\x91\t #\xA2F\x14\xA7\xB4\xE8y \x0Ft\x1DA\xB8}}\xD3\x9F36\xFE\x19#\xD9~\x1B\x7F\x16\x89V\x18': '',
  '\x82}\xEA\xFB\x18X\xD4\xDA\\_\'\xEC\x07\x04\xC6\xCA\x8E\x98\x84K\xB6\xC5\xE9\x80\t\xDA\xCB\xD2:\xA0\x1Av\x06\xF7!\xC5\xDA)\xF9\x84stD9G5\xF4\xA7P\x10\x84H\xAD\xECQY\xE3\x1A\x95\xE7\xB2\xD5[\xC1S}\xFCH\xB1\x90\xA9\xAA\xAE.\xF9\x9C\x88I\xD9iQ\xEEQC\xF1\x06rE5\x9D\x8BR8\x92\xD0\x93\x1B\x16\x14\xD0\x99\xB1\xA3\xA8\x0F\x8C\xA5\xB3J\xE80sF2\xCD\x9A\x9B\xC0t]@\xC8\xC8\xC5B\xF5;\x14\x96\xE5Q\xB8[\x95\n/\xCA\x8B\xBD\x82\xE7\x01\xB8\x7F"\xE4\xCC\x9D\x95\xE4\x86\xBB\xAC\x15\x80\x909<G\xD5\x81\xC2(:U\x90\xBE\xA9\xBC\x1A\x80\x01VU\x88\x16b\xFA_\xE9\xA4/-\xC6t\xF9\x86Z\xCC@\xFB>\xF4\xEF,\x11\xEC\xF6\x9D\x84\x9E\xEA)\xD9\xB8\xD7\xB6e\x9D\x81\xB66\xFB\n\x86\x82\x07Kb\x95\xE1\x86\xBA\xE8V\xDDV\x1E`\xBC\xF1\xD9h\xEB\xFA\xE9\x07\x11\xA5*\x02\n\xAB\x8DO\xAA\x93{\xBD\xA1\r\xE7\xB2$e\xC1\xB6\xF3V\t\xF1\x81\xAB\x91`\b\n \xD4\x12\xD1n~\xE37\x8F\xE3)\x93\x8E\x96l;1\x10[': '\x93m\xA2\x01\xBB\xD6\xD2p\x93\x90\x13\xE1\x96J\x14\0\0\0\x01\0\0\0\x14\0\x05\0\x10\xF5\x86\t\xB3\x8F]\xA9K'
}

response = requests.post('https://drm.cloud.insysvt.com/acquire-license/widevine', headers=headers, params=params, data=data)

#NB. Original query string below. It seems impossible to parse and
#reproduce query strings 100% accurately so the one below is given
#in case the reproduced version is not "correct".
# response = requests.post('https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEuNjM5NDQzNzI0RTksImRybVRva2VuSW5mbyI6eyJleHAiOiIyMDIxLTEyLTE0VDAxOjAyOjA0LjAwMDY3MyIsImtpZCI6WyIqIl0sInAiOnsicGVycyI6ZmFsc2UsImVkIjoiMjAyMS0xMi0xNFQwMTowMjowNC4wMDA2NzMiLCJleGMiOnsiRmFpcnBsYXlSZW50YWxEdXJhdGlvblNlY29uZHMiOjg2MDAwLCJGYWlycGxheUxlYXNlRHVyYXRpb25TZWNvbmRzIjo4NjAwMH19fX0.HJN5ZSQlapN7LVTYzZPTHaDgGJRSuQYkbKkRx4FY0zM', headers=headers, data=data)

**Comment by medvm** [comment]
ok, I'll add it later
