### ISSUE TITLE
Please Add galaxyplay.vn support

### ISSUE THREAD

**Issue by kendyx1** [medvm/widevine_keys#26]
python l3.py

Input MPD URL: https://a30-fcdn.glxplay.io/25aa1cfb-0565-4509-8226-ff7394e6c620/4e32a7c2-c748-43ff-88a8-dbf0a94b8b10/5/d8dd0528fbe07990e5431f58bdd1325e/h264/manifest.mpd

License URL: https://lic.glxplay.io/license-proxy-widevine/cenc/

Unable to find PSSH in mpd. Edit getPSSH.py or enter PSSH manually: AAAAXHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADwIARIQJe+p+2yBV4ecVjXp9J3jIRoIdXNwLWNlbmMiGEplK3ArMnlCVjRlY1ZqWHA5SjNqSVE9PSoAMgA=

PSSH obtained.
AAAAXHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADwIARIQJe+p+2yBV4ecVjXp9J3jIRoIdXNwLWNlbmMiGEplK3ArMnlCVjRlY1ZqWHA5SjNqSVE9PSoAMgA=

license response status: <Response [400]>
server reports: <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
server did not issue license, make sure you have correctly pasted all the required headers in the headers.py. Also check json/raw params of POST request.

This header: 

> import requests

headers = {
    'authority': 'lic.glxplay.io',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Microsoft Edge";v="96"',
    'dt-custom-data': 'eyJ1c2VySWQiOiIyNWFhMWNmYi0wNTY1LTQ1MDktODIyNi1mZjczOTRlNmM2MjAiLCJzZXNzaW9uSWQiOiJwcm9kdWN0aW9uX2ExMGNiYmNlLWEyZjQtNGEzZC1iZjhhLTgyNjRkNzViYzk3YyIsIm1lcmNoYW50IjoiZmltcGx1cyJ9',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 Edg/96.0.1054.53',
    'sec-ch-ua-platform': '"Windows"',
    'accept': '*/*',
    'origin': 'https://galaxyplay.vn',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://galaxyplay.vn/',
    'accept-language': 'en-US,en;q=0.9',
}

params = (
    ('platform', 'BROWSER'),
    ('type', 'MOVIE'),
)
# params inserted below will be passed to data-raw 

token = 'PFYtFSqWMYIROJYywBp0rbKvpD3z6N6E6UezNrZmCeKHkcJ5BiH4J8qwO0kfWOmrSsyFJMg9OqKKEwvuQiXL4qdDTa6ZYplNV9IQt6eEuveglDxjVlYd0vAecS5TZKn5mIs01YxcYNlTC7tu3BIk63JhMykMWEMmj1oEqaLa7N3ZrfU2VTlEPaWXBQV6PxnFeD022Yi298GOX/lDik7sXt5u4duT0aKIYbz0HPmjoh8b9Uy8bvzJUa0/SlgRcsW8RNTNjRJHM6N7BESCBGFEZcWoSXeDLEblEfRoBKro2iDGB1neLfRdY1fj7tJX1Rn9lj+OJwRTrBV4XoTQFuSsFwvYCeQfkAoRHXnze9njI5pY7sYgIGxuM4Zh3Wqaps6kxdO53QMm0jJ/L41X6r5CikSGKQ3Rcps8eQccZb9svEuyXMof2nm+eYL+AVPPrfmAf/BrmUHfiuF9CmNsF9pI7PjJfLeASmh3KDI/5gUuC4uJB7rjTzHVWNRz8MSvYjJ37/5V9+FTihpu04+0jFZ1AlGRks2dzk2IGvm5WcwUhsW2l/oQXlh7AgsksIl2DT0wH11WeG+h1/ijymMcG9AZzsxtkC53eLJ8bl55/Aag0TJfX4N6KvV7UhglXxkLifb06bLK/wlcGCfb01b4cnngcjPJEMxh2+Q7sJSnbyrtsfodzNah8JXITmx5kTkFFZkdtga1ha9jAb+Z40VMQfbrCLgh0GEe2G3VczcIt8QHAWAeS91TkzLbMRAugbgLvdbI8yQXtM15uo+TXrV4PNFprug33AnvnQu7IpNxlmgPMZhEn4Qqc/V++OFIpz/JYEMnLFvjYcXE2+sPc4uKnoE0xk33+IgZKtWtDhxRg2SJKyKOYxXucXybUuqPP/d+Nq1VNhD84Of+EfVvBjs1u75pNz/kmu5ms9ppRMkafq0/2311hbYi6VXmp6AeJweGJWkGKEFxw7xADuC8iM7xWnXW5aiNvhbsXBOwuTK8b2ioxjrg6OFhiMck+z9M5FHg+ktY7YB8iY+0V6B/Op2cQGtLaZ2E9lsomlQpxL+LiPI7UWEqmALEGH/Pk5tdLnlFRjEk2PPc8YURw+/nkP9tqJ/AXQwaXc9iwC5yxlYPCsp/Tc4='
provider = 'kakaotv'

releasePid = "_qVpiY31v_oU"
# response = requests.post('https://widevine-proxy.ott.yandex.ru/proxy', headers=headers, cookies=cookies, data=data)

# print(f'{chr(10)}widevine_license: {response.content}')
#NB. Original query string below. It seems impossible to parse and
#reproduce query strings 100% accurately so the one below is given
#in case the reproduced version is not "correct".
# response = requests.options('https://api.ott.kinopoisk.ru/v12/license-affected-content-metadata?contentIds=4b63db58ab27e92b90a457e533b00007&serviceId=25', headers=headers)
# dash-cenc/hdr10_uhd_hevc_ec3.mpd
# https://strm.yandex.ru/vh-ottenc-converted/vod-content/4315082489d87677b21f7c83593fcb73/8614535x1631802676x41611665-4e76-41ac-93a7-5070b77b5f3c/dash-cenc/sdr_uhd_hevc_ec3.mpd

# 'GET /certificate HTTP/1.1'

**Comment by bk3a12** [comment]
25efa9fb6c815787 9c5635e9f49de321:7721834ed44cacf33d 5a5504e049477a

**Comment by omarsoftbox** [comment]
any solution with this?

https://d31ib6xnmsvhmh.cloudfront.net/zXUH5MvB_uz9qgVbjki05MB6Q_enc.mpd
https://vdrm.mobiotics.com/prod/proxy/v1/license/widevine
header is 
curl 'https://vdrm.mobiotics.com/prod/proxy/v1/license/widevine' \
  -H 'authority: vdrm.mobiotics.com' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"' \
  -H 'content-type: application/json' \
  -H 'x-session: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJzY3JpYmVyaWQiOiJRaVl5eEFXZ3E0azYiLCJzdWJzY3JpYmVybmFtZSI6Im9tYXIiLCJtb2JpbGVubyI6bnVsbCwiZW1haWwiOiJvbWFyaG91YXJpMjVAZ21haWwuY29tIiwiaG9tZWNvdW50cnkiOiJEWiIsInN1YnNjcmliZXJzdGF0dXMiOiJBQ1RJVkUiLCJmYmlkIjpudWxsLCJhcHBsZWlkIjpudWxsLCJzb2NpYWxwaWMiOm51bGwsInZpc2l0aW5nY291bnRyeSI6IkRaIiwicHJvZmlsZWlkIjoiUWlZeXhBV2dxNGs2IiwiZGV2aWNlaWQiOiI2NjY1MTk0ODIwNzI5Nzg3IiwiZGV2aWNldHlwZSI6IlBDIiwiaXAiOiIxMzAuMTc2LjEwNy4xNDciLCJkZXZpY2VpZGhhc2giOiI4OWUwYTBiN2JjZTFjMTc2ZDY1NjNkOWNhNDhkOWZjOThlMDljMzM1IiwiZGV2aWNlb3MiOiJXSU5ET1dTIiwiaXNzdWVyIjoibm9vcnBsYXkiLCJleHBpcmVzSW4iOjE4MDAwLCJwcm92aWRlcm5hbWUiOiJOb29yUGxheSIsImlhdCI6MTYzOTQ3MTg3MCwiZXhwIjoxNjM5NDg5ODcwLCJpc3MiOiJub29ycGxheSJ9.5rVwMT2rISfN1rcx--rg75TbqGwwGXTBc9MeBRXBu8k' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'accept: */*' \
  -H 'origin: https://www.noorplay.com' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.noorplay.com/' \
  -H 'accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
  --data-raw '{"payload":"CAES6R8SVApSCjwSED2rh/PLp7d/+6mxD2Yr+bASECwctu6KMcPkb6ODCtEUz2ESEJIg2+uLKbeuzebT9ahRBhZI49yVmwYQARoQK7eoRyepRsKul7qrKfRdOBgBIJO24Y0GMBU4vpnJrAFCgB8KFGxpY2Vuc2Uud2lkZXZpbmUuY29tEhAXBbkXzBIEhosGMzovdyqMGsAcn87dLeRp9/62ApQf4V2OVx+zecnwrOhalCE5y77VnJGawk+f/S1cqxz0j25XniuRZcWM4sYXzKMVgW/ehNHqwHIPglaXmfVyaF9MJpaa1JUBISI7GT323udu6q+stjkbZbFpclXiuKtDHFWdjfhzv4scCF/lj5QcBpeVgmsSJ7Ccf7DIVsqCHDflOvrTryPp5aEy2fTqaD4nPsDqDpkCRzS5Y5eTtD2Ty2WYUGNlwbHVL74wOl45Uh5alF9YyGKyVmg3JS/2PJF2IPF4EdD/kiXQF4M+m3ZpXmZjgj29JIOCzCrecBUd1kbYjXC3EHJ7tOadltz9mCbcTLQ/+q1Bq0UAWU6sZKI4lTSTU6nSXlgcAhBou4cPaND+NnWqD5BVTQ+nXpZJuMO4KHWe02D5DQw5llnnPwPLbsMWbk7zltlT70OxLC7aTU5lvP0RAla0aDQfkqOPRmSY/u38q1yUsVNnzzSMbnQLBMXnW6sX1E4OCnX4BBWk8gHUkT9dLCcINXzwG9fu8Y942f7qgjjsbBWUCJJEbMUfGkDDZkjZnnYE72hg1TWXpIwleKzy5ZFUdrQbBS6II23FgERAfVku/8zUleoqOk6SXicNyyq6+lyDWrjI4nD6drA72/eNWqcksMhrz1YnW2OXnH9JiYEAou7u+YGp2gbECDHiNfrlQth5vvds9QdS+ndEDH/J2o5tn1MrgnFW921EQGynUsbVOEzT3nmshAmqRQEoJyONQj2J97i0KWlkCq/jd4Q2A3nEiWtLP7pvZSpfpydbZS0m3nQLO+vCZNbRx2UesR2pyje8rxBbRgxGg2J8CGyDZOIDX2EFuZrdbeCIOHCuSanuJyaFt2CGPr7c+ILjJcdQ8fyEuaCj6P3ajzIMsQuNFOt8RQyxg07jVL8SxfcEPgfNkqmF/qa5ZXBUjYw3VwgXfp+2XedSJr++SlQspyDGS2oFhevmG4jqBB2Me5YQ9EqRPF9DAh2fsfdHoqBMtLFuvMrFXbLB6nNWXYuZhiwb2Yi/pvmJVGiMIJyR4+4eQgDfndkE+olcgqmlEPacUtDBs5r1mEiDc/Fc3r6gKEQI1HWGqonBUc7qOFdBqMyXZTIhClEhNg1eNZ4FEIGPc8ah3tus7wIdoR81TAIEK1fcV1W4G2Im4EDiTF8ggw/sVO8LGX628HWiAGyNfJl7mLA4LDUJ//IlaA0M8ajoUFG+WWHrpYQaVipBdmqrVO/k3KlX1Khk9VBhgeEbOWw6wqRnOQAXCw8kBIP1hSufxcO0Ml+2zdVL3ZpmrlFQovtTERicXjzQiC4uH7y0osTollnITyJ/MazlfLZsiN/SIJH3mFAg6IuW1VGSQJIaUMUbTloKkixZ8ZmTi9XJaarbZ3R9Rn8ABhz2L+J9TAMNbiQjBNGXFmPeKH86TUnY8vnRGgxd0nWFu7WOEvAcA5Da+sbgf1H9I5NL1AOcwDnYhkQ6mTI/Mx6Iubg65Saf8r2hZoolqmlUeK+D4CSW74YJWeX50J5L1SFJ6uKLEBDidm0vGGGcI3XKFUifBL6EUsxWHci9ibU0q/vaI63m25yJBKIYOZkaXAyx28TeZLJmwo6M72ZrD1SCfpdhxYfpjZsF17Jwpru3kWfEDOMaVoGbLvQgrIH6EkX8v/Q0ro7IysHO9ez+IlBDzO/5rXZQtsqyrlCJR32ZjPQlOd0Xq7DhFcp88khdY1hcV82+mxfVb8qkbjZO7aeJYjsHscxMgV0R+u9fHzySTE4W5cnbTfQFIike6uLHbSpIrHMiuFbxtWNVb1jCsFzrWq8qyVs1ig/IuJV6IkCwVCnpgG7repLrMwKKPniHUmloXiQP/7KudKaxZ5Y3NFixGFRzdcR3LSfleWkLfqELDtp6VcokkL2Uq3RoZ2qTNUCx38p1F2BsJgp4smL8BxNFO+4n39PMCdhsXkn5m8hwalro1B4yM+uUa9mfP5lUGBMrlgP1tXtzPfRG0M5PUVZq5H5awRx2x2Jo6fwafhcMtVlGT0GgvWbG+vQupdavoEW+O9XZ/yjZTn06O8OMpXfHVhelc+raoLyDUdFfnWkHc0oR4BgG93P7DlNSDfqsv40Mzvdj+O8tRfzT91nKO7AU+Sz6TVuYtKs9Xxy6l8kGgn8jtIkZUuY3wwER2+wJ+LPWi2o+R0yyRg6wQv+Pf7gv/PeINi7tmZcsium3dOV3pmtMdiEtbR63eR/+TEdZ4PUIoZTk50anzR5RRwV0N/Bjs9E1jBdUO5UEtuGry6a+oLGQT/DJfnsrFd1dkkB/cWt8x0B9YlAjwTDzTvVIMdSi935qNaubGC9xfVAlXMhAi2R/8ukg98HuAWMCAX6IeYJ2hmWLMJdkE3ysUhah3BJtdm/TKDBGeUkviX+vARbXyzQ3mgLrlD09RFnJdCXS65s3MWYywqLJQfpj2jtMJO443aew2FVeDjPNY4XQCXKrtIqNPT49uktP0pg3fOljhDp2ifFEfi1IVPUnF5KqTz7h0v0y/YW1wM+WnGRmKJlq1ktKLoAe6Ee3shqUKCpAjkmCMZKJYsFcsSqw+VaCIJWuanww5/I4N2mMdSPZzsT5u7qt9osyOitRSddiBeake6yUNKeOgbA41t7FpXU+ds7QmiPkM/maXykZRlGGI79J4j57/s20eOOAMW+IpLkwnbknjKGyMSSAijuokqJ4r9A7esw3n6CDCUbt6jATx7e5vS9UrFkuS9LzfxrR/P4ii5iccZItacsxwRfV7m4MkjvW8yyaIVeJ25gvbQP50TYMvRyPrK6k+p5D/OC84uNfY46WYP5UOVvf3+yiyJNWfen1TmX5cP2UIbnv9b1mVxzT5Fn8uZ6TuOY5djde4dbNOHZ26r0MlqsT6truA6CRXhENzl1b1TDvAPHyDs8r6aAzNB7KeLFirV5EsiEkArY4raUla49oLDHJ45DVkeHCJp7m+sKMlThGhC6oVn+KdmNPtuvi5cQR8pQ83DB9yRdL9PEk4XwEyrNO5CJRiQG8D/a9PG0dq4dfe7upz4rqAh+jsECuhVCVs2wH+GzQwtafKmfCyyHx3RAKKMHGfxTYumNeRR5p05DpJZA4hbYfj5lAO+5kLLW/DHUnuGBj5PcoITs2JApQpJgkQ1MyrsB4/8IewbddbT+ytiMDuWXZrJCtZLLmIQc42Z62MztW2SlosM3nmhdSWe8Vlm0fX8aW4vdC593/dw5QvXdQ45/fMI+pk2GAND85YE3q76ntjF1uRLyrPuEeqikjUp8kOlEsjOXazNK4hW5WCnSkA98SmSRj4TL5FBKXYimOsyipP9DIHuXC0I04Qug6f6h/xyqF/4D1vBbm9spElcqZ5QQaIvDACatZ9Mp14uxwhvRx0mtud1IAu7HvM4O5BxbdICBV6vZS8b8m+njoQHaEvDKGMO3oxKwf0j050hmZY9i8b9c4Do8jkV/SAxkH7/Zipnkbw/Z4W06tXyA+T38dARrfugyxnWqdUmBQVHE6gpZhEqJ1tIw3rICxfwaHP/dCYRuRiLI/z/iU40uCsWneeR+U2A/f2LXy4fiH8cfWcnBoevaW1sh/p4DnCcT1guy+oYb8Kam5pza159J159lF0m7VSWU3hWGi3CRdzQlO35GV9KKgkdnOauSaEF7qFsdkbBHl7Lvd/2G0s02uHnONoD9X5YQpBfRiw8G/4l0Qo6t8rfAChaiPAejmuPSF4hVnlIyBunktrRWOlPhBiwoQC/9qTaGgVFjvcxK775pLCuAIvKI1DqdYDVIYSQhXWl9sJu4tnAGJy6xJYVPMveIsMEEHRbi3O12bmWjOilqs5rdrvWoH9a8mT09VLdni6drUq29iNQhQGP43YiWGowKuJolPlO7m04PBg2yR71OMvkevM6jsbe9dQxClblFWw5tna2C26+3B+KmBwG1mA7/ET+Zw55wfg1FvF2fsVRtx6Qwb3uFixTFGfSNUxXaCDtUQ+FL/omb4hwS2tUgcPNKEMfk/RHiebebfJ5hdAZga25J6NM8nk4E6jfPuXi/LsCNwtt0BxnXY+k+i7qaEx9dnQYNEnp1l0C7WlFB3pq69X3AoY+yNWXFiSd5qVVPQESMYmTgrIN7/s/CXcuQdqEQEYOxeQHxK4HLe8MXsgUog+5GSY50KLFhoLjtNoeO9wnKkhXI+Jz3Iac14Uk2jc26tsRIE8qWoXTkSdmp5E3F6cbEQFV2wsLse5lAwr5CM+rlHPY5aSecb0t2578Dxv8c8Un0Z1TbrOt86/HEvrhStK9U6gUvmFe/e8L8TuZ7KPAp+zKAzHGJoIKzkFSuQaPxRwPvY2vzY37WDQyQkxuhw8c6J+meyuBc1D1niRtKRIl2o5CnWod5fJQi8g114nIfDTcblHGii7m1YaJC+783+tk8jnjKNsE2hC9pMpFrjqG2TbCetfl/WZGr1rCQhH62ntpnNk5VR/ZhV8O38EkPSFzjmrxrt2GL7Zoi9vwkWeAL6LuDHr23bOWo7iNm4R5GKp5xev+C35dpOurHz4zxukNYA3IH+B0nQa6nCndrIP68t0WOC1mP9huQt7wETRMBtSwyv7Wi2uOuizM2RX8fwqr1PRYk/AO+Rl5IxN+8ED8GGu/Ui0PW1iLKOw1bRe/gAMGccouR/foAaqcEdh52m1he1FvhBOlR5Zxd3iYR61siEXBmeHNpvf7nMhXcdgSTQ3s0JK1o589WUNRfJ9DEWn6CAwDK8XuCN/jrOYS7s1idgirn5lZh9GBnC13NL/IHicAAlnvDWzbHPBduKMh9xcV2DI6HtFyRHIjubxWPfPB3gPgjhk6CJBFd/sF5hB9s1wKwcAtrv9flxnN2sISLKgtpTKaBdfq5Ud7NkW/2PqJVnnM6zIhAY4xEycm34tP8DaF9d7hfiKoACbHBIYcufwTtEBx1ppjcuoDXtAOcC8HiUbwm2m5bgmg7cZY+jFjiJYTOlVC6b+EZ0YGChT5nKoU04Jzp/a8KdvSIcoirX20NrAfYiSV6qWPg7+TXDcjDl2X2IiPbqVI9DY4x2gLoPGEV/3GX8bSFPyOfiKQ+NuA7lxjyK23In9xtOJ2J9dqxHmf5QlCxhIfOcOgK87/yWScI+IIuXRPaIA8yG1ionPD8uyA7sJMkr2qxPj+qixRiXrQSjhBUo/DQKmNrOp+PIHvnENn+KlqwdiuVI51DH1RlLoJcrZEom/7BkCVcVhgam0i6gGWcQoytgolkgtaYhpiYoj3oXA8TeuhqAAWlrwBPo37yAYtlxQd43TIkish45upJ+ZcgxqMHrVwB8Q/nDH8hWGrHBeNnfPn8qw2ZcMHq5LZ+e8U6IODBR0e+xxhcCv91Ys52ET4PWJnuVOsr9mDgdpLHScuN+gQftriLv306VlY8LWdXFU2TlSSQPCRomIdZSTfeMlegxUkzdShQAAAABAAAAFAAFABAVkky+qFMtEg==","contentid":"9IqdcBo9C0W0","providerid":"noorplay","drmscheme":"WIDEVINE","customdata":{"packageid":"uz9qgVbjki05MB6Q","drmtoken":"arkQfYUp"}}' \
  --compressed

**Comment by omarsoftbox** [comment]
i have this result
C:\...\widevine_keys-main>py l3.py

Input MPD URL: https://d31ib6xnmsvhmh.cloudfront.net/zXUH5MvB_uz9qgVbjki05MB6Q_enc.mpd
License URL: https://vdrm.mobiotics.com/prod/proxy/v1/license/widevine
Traceback (most recent call last):
  File "l3.py", line 25, in <module>
    pssh = get_pssh(MDP_URL)
  File "C:\...\widevine_keys-main\getPSSH.py", line 35, in get_pssh
    if ad_set['@mimeType'] == 'video/mp4':
KeyError: '@mimeType'

**Comment by omarsoftbox** [comment]
[EME] MediaKeySession::generateRequest
    Session ID: (not available)
    Init Data Type: cenc
    Init Data: AAAAXHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADwSED2rh/PLp7d/+6mxD2Yr+bASECwctu6KMcPkb6ODCtEUz2ESEJIg2+uLKbeuzebT9ahRBhZI49yVmwY=

[EME] MediaKeySession::keystatuseschange
    Session ID: 0F306EEDC93E6DE8A6C97BBC078D9C43
    [USABLE] LBy27ooxw+Rvo4MK0RTPYQ==    this Kid1
    [USABLE] PauH88unt3/7qbEPZiv5sA==    this Kid2
    [USABLE] kiDb64spt67N5tP1qFEGFg==    this Kid3

How to get key frome Kid

**Comment by medvm** [comment]
readme
