### ISSUE TITLE
Add bitmovin support

### ISSUE THREAD

**Issue by hmnytv** [medvm/widevine_keys#27]
**facing some problems with bitmovin**

Input MPD URL: https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd
License URL: https://widevine-proxy.appspot.com/proxy
Unable to find PSSH in mpd. Edit getPSSH.py or enter PSSH manually: AAAAW3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADsIARIQ62dqu8s0Xpa7z2FmMPGj2hoNd2lkZXZpbmVfdGVzdCIQZmtqM2xqYVNkZmFsa3IzaioCSEQyAA==

PSSH obtained.
AAAAW3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADsIARIQ62dqu8s0Xpa7z2FmMPGj2hoNd2lkZXZpbmVfdGVzdCIQZmtqM2xqYVNkZmFsa3IzaioCSEQyAA==
Traceback (most recent call last):
  File "D:\widevine\widevine_keys-main\widevine_keys-main\l3.py", line 130, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "D:\widevine\widevine_keys-main\widevine_keys-main\l3.py", line 52, in WV_Function
    data=f'token={headers.token}&provider={headers.provider}&payload={str(request, "utf-8" )}'
AttributeError: module 'headers' has no attribute 'token'

**Comment by hmnytv** [comment]
**this is the headers curl **

curl 'https://widevine-proxy.appspot.com/proxy' \
  -H 'authority: widevine-proxy.appspot.com' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Microsoft Edge";v="96"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 Edg/96.0.1054.53' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'accept: */*' \
  -H 'origin: https://bitmovin.com' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://bitmovin.com/' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-raw $'\u0008\u0001\u0012Æ\u001f\u0012S\nQ\n;\u0008\u0001\u0012\u0010ëgj»Ë4^\u0096»Ïaf0ñ£Ú\u001a\rwidevine_test"\u0010fkj3ljaSdfalkr3j*\u0002HD2\u0000\u0010\u0001\u001a\u0010_æ(v>Ì\u008a\u009d¨ÿa¶nOâf\u0018\u0001 ÷çá\u008d\u00060\u00158ÐÎâÍ\u000eBÞ\u001e\n\u0012staging.google.com\u0012\u0010(p4TÀ\u0008ö6\u0018­çD=¶ÄÈ\u001a \u001c\u0002äg\u0000ûR*\u0084\u0008k\u008b¶\\\u0086ùy)\u001de_\u000fd\u007fsL\u0016`\u007fSö\u009fXÉ\u0014\u0098\u0092\u0021_C±\u009bÖ\u00979~\u009buèF\u0001L5X\u0080ý\u0097\u00957¶ïæ\u0099\u000cTÕa\u000f\u000fV\u00044¼qÚ»¬/ª×»}v\u009cU¦D<ÎîÛ\u0016r\u0004Ý2(\u008el\u0003Ø\u0086\u0016c@¢é\u0096î\u0002\rçn\u0013êo\u0021J\u0081þ\u00123á8\u001b\u008a\u008apiK`Á \u000cJ\u0001µ¹]x\u0001\u0080K)¢2\u000eC·èïS\u0090RcÏ¶È\u0096å0\u0013@¤\u0018\\c\u0088rM\u0004\u0086lð|¸a\u0090\u0084°«\u0094\u000f¹<îP²ûw\u001fPG\u0010#\u0010]s\u0004ÃY~\u0010´\u0098-Õ±þ{iÂ"DRÞù\u009b.VgÂXZM\u001ba6oÀ8ò¯Æ\u0009qÚD¢\u00808P*ícÅ\u0083\u009d­2äþ\u008dçèÁmCÂ¾¾5 \u0088g\u009c¦Aý|5 @W;:f\u008cÙ\u0019PÆãùtx\u0098\u0010\u0086q\u0013NÿêÎN\u0013J:Wy«Ü\u0097?ÒP64Ûî\u001c¥\u0009\u008e\'\u001e\u009d\u0018P\u001b\u001b(m¡Úh\u0003¸\u0088ýc²ÎÙð¢ö\u001a\u0016r2\u0016ýJ½\u0085\u0011)W\u0099ù{¢)Yl\r\u0011©É,ô\u001fRÒ´£¦+qe\u0090V+L ðKÆ,é¿I\u000f\u0099ï\u0008^\u001e«\u0091\u0009<\u0015SØð\u0093\u0002¯\u0002\u0011|\u0011l£\u0008\u000f+\u001cW\u000e¡V\u008eÞ\u0021+em\u008fÛ5Æ*)\u000f±\u008ffJë$\u008b³³\u0006\u008f\u009b³\u0097v\u001f\u0014À\u0081z}\u008b\u0012\u000eÄ®Ó°çW:lD>ç\u008a=å¶\u009b^\u009b\u0009s@&2}Ú\u001c\u0014ù¹¥E\u0007$¬îòP.ü÷\\Q\u0013nqò6\u0010·¡kt\u001aÊñ3ê\u0093\u0005\u001eb\u000c³\u0084\u0006Ò\u0004\u0091Wñ\u008fÔ\u0009//æ\u0018â\u0090ðï\u0094SnùÐw­¡2¬»sèJ\u0007\u0009<nÁ^Bª¥®¤sàÏåz\u0087^¬Ì\u008eG\u009aWÁ@9ä\u0000Ô\u0010ð9Õ´ÝÀGë\u0095\u0090Õï5,*OM{Q2\u0095í\u001b\u0090î,ÃçÇÃ_\u0098PGuZOÂ³<v\u009eéÕý\u0009í\u009c×ã\u0012üb{T+»I*Êä\u0004\u0010+\rDÉ\u0009qH-ìO\u007fñ\\H;é\u0016C\u0097à\u0005ï\u009e\u00971\nj½x¼<oæö\ncëòIíc\u0017jÑI$Ó(ª\u001b+\u000fÉ¬³\u0098 K\u0098\u000f\u0089t,Ùôú~q[=¶wQÜ^òàe\u009eC@ú¿Ìv\u008fu\u001cØ­\u0086Í7=-\u007f\u0095à\u0081æv\u00807ä¾9={Ãü¢xþµò\u0092{¼®¨Ú/§¾>\u001c\u0094 y¸\u000bÊ¾g*úÛa¸Æ\u0086\u0001ºC\u009fÝ>[l\u009c¼Ce9»X§h¤¥#(óÏw6ewµâæ\u0013Þ\'ª¼ÐÉd9\u007fàÍO\u008e5pù\u008c\u009c\u0004÷\u0004}\u0087\u0006(Ïß(Åß\u0096U\u0009 \u001fx\u009c·¤ººÑ¶Ï\u0009b[÷^v\u0088qH{)îé%Hù tjëkÕÞc¤\u0099ÿÜ\u008dù\u0093\u008a2vT\u0096%Ûaÿ,Ìõ"8ð¿^u\u009f\u0090üÁ\u00963õÿËq`0W\u0017\u008dPó%\u0096\u008eäæÍxåüU\u0007ù¸n\u0086\\@)¢×Û\u0018\u0013\u0004\u0092\u0096UAh&\u009f\u0081\u009aI\u0083Ä*aÔÍÒÅ\u009f¥pAá\u009dí\u0002\u0016Ð\u0081ä°\u001dÜø\u0018\u001dEx\u0003ÿW\u009aÙ6Má$ÜIe Û¹\u0099êób\u00903è\u0097a°AâNp\u0019\u008d¼qÿ°¥¦]\u008b\u001cÈk:B8fÂóó\u0090\u0093\u0008\u009f¨\'\u0009sËÄ¡ùªßgÐ^Ý \u0021kj\u0013bP]ëÝèN\u0006Þz\u009b\n\u008do\u0016ó\u009be7ødèò©gÚÕ\u0095\u00002\u0091\u001d\u0097\u009cNËmiö¿öÔBÍ\u009e\u009fòÄF]w\u0007lÎ\u0099¹%Ìw\u0007£óçO©òL a\u0090Å;E\u0002¾óÊ9ÃÆäH\u0084Ô+¿ï\u001e\u009b½Èt¦×\u0093\u0091\u009aáªz\u008fùjg\u0089¼]\u000c\u0096É\u0083ëï®hy\u0012ãZ\u0017Q\u009c\u0004\u009e\u0000þ[3¬\u0016A¸ôKáäJ\u0099àö¬Õ\u0014HFáÈuCn\u0088\\êR\u008eô«Q\u0095\u009dß\u0001Ë\u0002ÿ\u0017Ö§\u00919«|Þ°\u0089¥ì}ã\u000f\u0004Q¯a:ñ¢.HÛ\u009eI\u001dµ÷\u0083\u0002\u000b¤j´Í¿\u0017·v°AìJ\u0014\u0081w¾u\rð\u001a\u008d«ÞñQÖ\u0087ÏDy\u0009#\u0015}\u0009%õ¯\u0005\u0084\u008cíÂ¡[\u0094¼~öë¨ë3\u0087¤a\u0017Z@Ì{+w@1yÔÊ=ò÷Ô{k\u0089]ÃÙ¡\u008eü|·jÂ\u0086\u0081\u0080\u009b\u0087\u0085â\u0098I96\u0084ûaÈÿ\u0092´y ªÞµ\u0005\n7\u0088\u007f\u001bW0P}ùròðm¥Dá\u0015\u0097AVwà¼Ö\u001bÔ\u000cã/\u0095ät¥éÑÏ\u0095j\u00156n;gC\u0003ÝVÅÅÔ\u0090BÊj{U¦nýmê.doÙÆ.â¸?\u0093ÄÄ rHq7¸d\u0017Ì~#{#Ä\u0087²·¨hS\u0015\u00134§"\u0002NÙ¿5\u000bÐ_I"í\u0092nk6S\u008fXX_6HX7ª_ÿ2¥aisìJ\u00137\u0017²G°q°Ðêv\u000eW¯\u009fdk3.¹\u001e#j\u0097\u0085bùÅÕ\u0085{±|:\u0098ÞIZ\u001f\u000fþZ\u0004\u008fo \u008d\u0005[\u0093jÕT/\u009bäh\u0015\u0018È\u009f.é)ç,)_\u0088]IHw­Y\u0091¿×\\´ÿ@ùk\u0082Ð0Ò\u008bà\u0092\u0080V\'ö\u00074qy\u001epÍ·µèñ\u0096Óì\'rÜ\u008a\u0087\u001a¦©±v²ÒV¨·\u001c:Oâ\nE¤\u0099r\u0007Zî\u00026}\u009a\u009f\rØ\\%\u0096öïÙ·\u0012EU"\u0000A*÷r¥|\u000cÑ\u0096²þ\u0006\u000c\u0081Û\u001a\u0011wÏ\u008eZ¬\u0002¸\u0018\u0080»UÄ\u000cÙZ\u0018\u009f\u0094uJÀp\u0010û9©"§\u0014\u001a²6A\u0085\u0085ëûoã)Zê7"\u0007\u0011¢|\u009cng$´~Ñ6»\u000c¦Â.G}öð\u001f/à@\u00929\u009c8/ÐëQ0vn(\u009aYe,\u0080\u000bß\u008ep\u009b\u0005\u0089\u008b\u0007a\u007f#°"èâç\u001c\u0021KÙË<\u008e¶<Ì\u0083\u0098Z\u0084w{\u0004ôÖGû\u0008\r,\u0096WÎþ<\u009eÜ\u0099´7\u000eº´ÜRýã\u0000\u0000PÝ\u0011\u009dìI5\u0080BEßO×_Æ\u0099ý²OluL½"¥2\u0007ÛM)Z¥Ê&­²\u0002ñöÇ\u0080´¥\u0082\u000b.\u0098\u0084®ÔkÿvÙÔ¢¯T3öj\u009eÂ«\u000eUÒÀ¢=å\u0004\u008e}ôW÷-EP\u000e\\"\u0021\u0019«µ*\u0090\u0015÷\u001eÓ];ÚE5\u0004\u001e\u0018Ü\u0087âd\u0017¶\u0018ÿþ8½lSÞiÛøé/\u008dà¾\u008fæm\u0012<ÖôÒæÐ\u000b\u000fW\u0084ZGÅ¬\u0014=nÈ:Û]wÓHèÓ-®ò\u001fQ)\u008f¿ê`xD:\u0094\u0084Ö®ðgs\nSG\u008fÎi¼äc¹Ü\u0003Ì\u009f*\u0098Ì¨*F\u000eÌÞ9±\u008c\u0012G1ÆÊð-Ü\u0015A\u0084QÒÕ\u009d\u009aJåëÐ\u001b\u007f¡\'×\u001cPP\u008a¢çie·\u0012\u001c6Â$\u0021ý^¨÷dFÙ*\\\u008d\\rÌÂVª\neÛ~ïdðME\u0084àÿ¸\u0087\u0088î\u0010\u0008lÝàá\u001b5«\u000fÉ2JÙ:ú³ÉÝ\u009d®v°c\u0092æÅd\u0097KÁ\'\u000f9.\u0009\u0089\u001cU\u009c_\u0001Gg\u0009\u0094<J|æE\u0080´p;.¡5\u009b\u00192ü\u0095`/XåüRÒ\u009c\u0089\u000f¤S"¬wXí\u0009ô¯]ýgMöxÅÉÌ%\\/ù"s\u009ciÍ\u001b\u000e¨\u009eÓ\u001e¥Âþ\u0014è$dwqÏ%Ñì]\u0005a\u000b\u009a\u001a\u00998òO\u0015¹ÖffTÒp\u0002vLÆhø¾QQéÿj\u0084\u0090´ö3¹dü?í-æ.\u0015\r\u001aÆÇäÔ7õ§\u0081±\u000c\'½Uä\u001díî\u0097\u0019v$/$\u0088ùëi\u000b\u0090ÛG,\u008eÍ\u0013¿0\u0082VSá\u001cb\u0088b\u008d½×EX¯Þª\u0092\u008fù\u0018Ýx\u0081Î\u0087rUý¿\nÚ`Þ\u0013Ûû¥£\u000b\u009cD&Õç(´\u009a\u0091$l\u001f\u0002\u0092â¸$Öå\n//<\u000f\u00843\u009dü15âê\u0086jCXÐ\u0018ÉË~\u0000+\u0091\u0084g·II\u0006\u0004Ò\u0010\u0009H:þ\u001cÁXó¤6Aª"\u008a\u0000¢\u0017ê\u0003l\u000f\u0091\u0011¡\u000caw[ÏÝ¤XCäëKð\u0098ß\u00901cw\u0000\u0017CÈó¼Kf:\u0004D4û"Ø\u0098\u0094\\l\u0093\u008dûY\u0013\u0004»T\u009d\u0006\u0010\u001de<Ä\u0006¸v`ö¬Ë.{\u001cºL\u0007\u0086ÝÀ#ã²N÷$JWÚ{\u0097ÒùEÒ\u001e\u0095ÂÕÍª¸G\u000bÊ\u0013*HXÿ\u0089ó½@´µXàóÝ\u0003?{¡\u0008Jd;¢Ó\u0091ówè2þ­-\u000c\u0012H[\u000cyêà}¬kdÑB\u0091\u0088öø(\u001a0iÐ%\u0002\u001f\u0001O\u0000\u0087üåD8µç_q\u0091Å\u0095~ð\u009f¬\u000f\u001f<ÇÃ©Ò\u0013¡¶8}>vØÅ:Í\u0002\u0094Cä\u001c\u0082Õ\u008e\u0092Â\u0090\u0082\u0085\u001c\u008aú,õ¾ÄwWh+Oqº\u009fyÄÊ¬¯z­y\u008a4lFØ\u001a[\u0089ALàë\u0011\u009a\u0003\u0004\u0014eÐQø¦ë\u0000\u0003+Ï\u0084óÐµ5c\u000ez¬¾+måøÊÛi\u0086¾ÚJ\u0009óÖ\u0096\u0019KÖ¥\u0080ÆÙ8\u0013v`9\u009d|ì\u001dZ\u000e±?F\u0087ßÈ\u0008À\u0088\u001b\u0095"zÊ¦n³mg]c$i#\u0087%þãt\u001eá\u000ctt¾jÄ\'¾Yf2\u0010ÝØ~Ñ\u0087<íèò\u0009Óýk\u0005}M\u0097\u00135Uç\u0021ý\u000fÈ\u007fÐo]Ï²ô\r\'P%Õ·~\u000e}p\u0008¼\u001d\u0005ÂÉÿOò_\u0097¡E\u0086\u0097/È¥Ç\u001dÎÙ\u0083ÇîÚç\u0006å©\u008cA\u009cM~2\u0098ß\u0082\u0086¾}úã¬\u0098Î\u0014\u0014vdn\u0005h¿\u000e+äH|ùByJ|Þ\u0098î$Íâë)\u0021| bG»¹þ|\u0099MGW\u0091LÝúcâ®Y\u008e\u009aLZ\u008eÄE\u0008\u009cïó\u001e\u0019©\u0091Uô¯\u0081ãßDu#ÉrÇµ¦Ê\u00079U9\u000cÚ\u0000\u0016\u008a7d\u0083\u0013~Z\u0089\u008d§/Áè\u0093¾3\u0019¢\u009b-½WQi¶Ì`ê¦u\u007f\u001f²m·¥J\n\u001a\u0090ñ¼Ü¡c²GGZh\u008fc\u001c&\u008f\u0005\u0083\u0007\u0080~\u009byIÚ8%@ë\u0099R \u0002*è0ä_ö\u0096«Îk~G £\u0092mCàzm¹æ~xÊñyp#\u0002t\u0019|KëØÀ#,gÐ£\u0083o\u0019³ä=\u0091u<î\u0018\u008a\u009cV\'RìÉáÉ°Oínd\u008d(;¸\u0007\u009b ×"\u0091\u0003z\u001b<ü\u009f6~¦_q\u0095m\u0093\u0091q0O§®\'Jí_«ª@\u0080\u008a7\u0018µ\u0021LÍ\u001c4\r\u009b\'Nö\u0021ÐLOÊ¹Êö*½ò\u008c\u0088dT\u009d\u008eh¿KÕ\u009cö\u0091ð_Yf\u0009*ó÷"C¸¯^$ñ\u0098Ó­\u0091\u00802þù³þ_Ef\u001f\u0091ûújâÑ\u001e\u00950ÄÚ¯òþ3=¼ïL±4Ò«L²Z]úOõÌ%YÌäI¸>óE.aÙþF÷@x;S;R\u001cíTµ\u0089Â,õ\u0082\u0001Y\u0097ö,ç8;\u009eñJ¸¯ë\u0097\u0004)HÙ\u0082%AcE\u0084\u0086?âx\u0092G\u0002¢@ñ\u0007¦\u0084\r¶:a\u009cð\u008dùTÝ*§è®2\u00980®Â"¢Í\u007fìvçªc\u0082¶ôs¼¾µÍUë\u0005¦°0\u0014\u008d×¯§úüMÙÑ\u0018k@QÒ\u0081öïTZQ-öJkþqDoíJ\u0012<\u008fæ-Kð\u008dØá\u0088\u0086\u0093+¾pý-Î\u0092Á\u001e9Mâ"\u0018·ÁÖ\u001a\u0094±\u000c#,\u0082Z¤\u009clw\u0088=T}µÕ\u000bF\u0018\u0021>a\u0006°\u0000Á_Ìue}ÖþX\u0004@Xý{þ4pé\u0092)ñ\u0096-\u0010\u0096,4¸âga0~ \u00916\u0016\u0006Ø*Rºnº\u008eÚ\u009d\u007fa\\\u008a®jÒÌ@ndÙ\u0001G¼H¥Ô¬S¿3\u0015\u008cétImé7}ï\u0002ê0/IêOxz¨â\u007fÖS÷\u001a·\u001eK\u0097{ûAd¦®tÿFë\u001c¤J»g3\u0092\u0085xåÐX¸_\u0087\u0099À¦"\u0092,6ÎévD\u0082v`\u0010´^ãÿì¹$GQ¤Ã¢;\u000eUÁñ=û6\u0003·³·)\u009f£ÍQÓ/Ä\u008d\u0018\u001aä\u0017\u008ab`&\u000f\u001d¹=KRã\u000céµ\u001cªÿþßgèçÄB\u0086êý¥\u0088\u0009Óâû\u008e\u0015ò§ª;³\u0096-\u008a¡¸H@\u0009\u008a\u008f"\u0010;az\u0014Õ\u0012s\u0082".\u0000Ô$/\u0013í*\u0080\u0002w}q\u0002\u0084öáX\u008eÊ[³\u0005ã\\\u008dQÍjº_º.Z8\u0000\u0007\u0009\u000c\u0008íM\u008dmN\u0002<aJþôl\u00897\u0011\u0021\u00001ÞíH¨¬j°ÍNë¶ã\u0083\u0012¯\u009f\nK¹3;F#¼«X3\u000f\u001b»Ê$HÖ¥¿\u0094aP\u0015{\u009e\r\u008aa\u0012Ù#8.Ñ\u007f[+»OU6\u009e\u0002Jg½;ôóÑÖ)n©ðÙ\u001e»Eâ\u008ce@*\u0011d\rÉ\u009aNÂ\\\u0080¥ó×Òx¶\u001eÖ\u0083öó)\u001b\u0099Tû\u0000\u008b\u0011æ¼¥2\u001ap\u009a\u009bÆUL\u0009¡\u0080Ü\u0092äÒ=m\u009d\u008e\u009a\\ç\u0099Cu\u007frC^â¼§\u0084Å\u0014¼\u0096\u00932\u000eo¤±9«EÒ9Éæ*ë{HxëøàÖV\u0084î¨§s«­¼\u0098\n¶èú\u009c=_Li\u000fë\u008dë\u0005Nõ\u0084\u000fà´zï\u0018,°a\u0081\u001a\u0080\u0001j\u001d¼#ë&Lï ®ä\u000f·è*o \u0096îÆ¢mìúv¨~ùMã^zµÈ9r<Dé\u0000\u0098\u0093 ú]\u008fÔI|\u008df^Ãó"Q\u0086+\u0093AÓ\u0010M¨S:ÒUu¢ßÁSí\u0001+Ò\u001dT«Wè |oö*r\u0084>¾\u0082þÐ\u0015róV\u001eÂñÑÍDFÎÏ2\u0081Åà\u000fgßJÂ\u0089?f\u009b>íùY\u0090¼éTJ\u0014\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0014\u0000\u0005\u0000\u0010é¸§Pù\u001a£µ' \
  --compressed

**Comment by deepblue2000** [comment]
the custom android cdm is revoked... this script does not work anymore

**Comment by medvm** [comment]
readme
