### ISSUE TITLE
unable to parse license - check protobufs

### ISSUE THREAD

**Issue by Mavrick007** [medvm/widevine_keys#3]
Input MPD URL: https://s3-iad-2.cf.dash.row.aiv-cdn.net/bd26/7388/7c7b/4ddd-bf00-61356e58f32f/d26cf947-5b9d-46c0-a5ad-deba66ce275d_corrected.mpd
License URL: https://fls-eu.amazon.com/1/action-impressions/1/OE/dv-xp-player/action/XpPlayer:.Media.SourceBuffer.Audio.SessionAppendTimeRatio.Average@v=0.0028257978723404257/XpPlayer:.Media.SourceBuffer.Audio.SessionAppendTimeRatio.StdDev@v=0.0016455277487718858/XpPlayer:.Media.SourceBuffer.Video.SessionAppendTimeRatio.Average@v=0.005661005661005662/XpPlayer:.Media.SourceBuffer.Video.SessionAppendTimeRatio.StdDev@v=0.00428394283392228/XpPlayer:.Media.TimeUpdateFrequency.Average@v=1947:u=ms/XpPlayer:.Media.TimeUpdateFrequency.StdDev@v=0:u=ms/XpPlayer:.Media.UnexpectedWaiting.Count@v=0/XpPlayer:.LoadCalled@v=1/XpPlayer:.LoadCalled.Feature@v=1/XpPlayer:.ServiceRequest.PRS.PrimaryResources.RequestLatencyTime@v=207.20000000298023:u=ms/XpPlayer:.Manifest.DASH.Download.TransferTime@v=0.29999999701976776:u=ms/XpPlayer:.Manifest.DASH.Download.Latency@v=5.399999998509884:u=ms/XpPlayer:.Manifest.DASH.Download.Throughput@v=4878596.495054215/XpPlayer:.Manifest.DASH.Parse.Time@v=6:u=ms/XpPlayer:.Filter.MediaCapabilities.Time@v=20:u=ms/XpPlayer:.ServiceRequest.PRS.License.RequestLatencyTime@v=116.89999999850988:u=ms/XpPlayer:.ServiceRequest.GetSections.RequestLatencyTime@v=783.1999999955297:u=ms/XpPlayer:.ServiceRequest.PRS.PrimaryResources.RequestLatencyTime@v=145.70000000298023:u=ms/XpPlayer:.Manifest.DASH.Download.TransferTime@v=0.5:u=ms/XpPlayer:.Manifest.DASH.Download.Latency@v=10.600000001490116:u=ms?marketplace=uk&marketplaceId=A1F83G8C2ARO7P&requestId=1&service=ATVXpPlayer&session=6898ed67-88d2-4844-a170-5db1e8248a06&host=XP

PSSH obtained.
CAESEPAV99rR/k0pkKjWQrzNxZsaBmFtYXpvbiI1Y2lkOnJPeDhMK09PUk9LR0MrY1FLWWVXY2c9PSw4QlgzMnRIK1RTbVFxTlpDdk0zRm13PT0qAlNEMgA=

license response status: <Response [403]>

server did not issue license, check json params in POST request.

unable to parse license - check protobufs

Input MPD URL: https://s3-iad-2.cf.dash.row.aiv-cdn.net/bd26/7388/7c7b/4ddd-bf00-61356e58f32f/d26cf947-5b9d-46c0-a5ad-deba66ce275d_corrected.mpd
License URL: https://atv-ps-eu.amazon.co.uk/cdp/catalog/GetPlaybackResources?deviceID=dd36a649c2e8285c83143a88b5d21e6d1d68eb86fedc5d57d9def97c&deviceTypeID=AOAGZA014O5RE&gascEnabled=false&marketplaceID=A1F83G8C2ARO7P&uxLocale=en_GB&firmware=1&clientId=f22dbddb-ef2c-48c5-8876-bed0d47594fd&deviceApplicationName=EdgeNext&playerType=xp&operatingSystemName=Windows&operatingSystemVersion=10.0&asin=amzn1.dv.gti.a857089e-cccd-4f32-8cd3-4b91fb587c48&consumptionType=Streaming&desiredResources=PlaybackUrls%2CCuepointPlaylist%2CCatalogMetadata%2CSubtitleUrls%2CForcedNarratives%2CTrickplayUrls%2CTransitionTimecodes%2CPlaybackSettings%2CXRayMetadata&resourceUsage=CacheResources&videoMaterialType=Feature&userWatchSessionId=afdf7538-0779-48b0-b2bf-41333dc36240&deviceProtocolOverride=Https&deviceStreamingTechnologyOverride=DASH&deviceDrmOverride=CENC&deviceBitrateAdaptationsOverride=CBR&deviceHdrFormatsOverride=None&deviceVideoCodecOverride=H264&deviceVideoQualityOverride=HD&audioTrackId=all&languageFeature=MLFv2&liveManifestType=patternTemplate%2Caccumulating%2Clive&supportedDRMKeyScheme=SINGLE_KEY&titleDecorationScheme=primary-content&subtitleFormat=TTMLv2&playbackSettingsFormatVersion=1.0.0&xrayToken=XRAY_WEB_2021_V1&xrayPlaybackMode=playback&xrayDeviceClass=normal&playerAttributes=%7B%22middlewareName%22%3A%22EdgeNext%22%2C%22middlewareVersion%22%3A%2296.0.1054.43%22%2C%22nativeApplicationName%22%3A%22EdgeNext%22%2C%22nativeApplicationVersion%22%3A%2296.0.1054.43%22%2C%22supportedAudioCodecs%22%3A%22AAC%2CAC3%2CEC3%22%2C%22frameRate%22%3A%22SFR%22%2C%22H264.codecLevel%22%3A%223.1%22%2C%22H265.codecLevel%22%3A%220.0%22%7D

PSSH obtained.
CAESEPAV99rR/k0pkKjWQrzNxZsaBmFtYXpvbiI1Y2lkOnJPeDhMK09PUk9LR0MrY1FLWWVXY2c9PSw4QlgzMnRIK1RTbVFxTlpDdk0zRm13PT0qAlNEMgA=

license response status: <Response [200]>

unable to parse license - check protobufs

**Comment by naim2007** [comment]
Enough of these stupid child pywidevine based tools.
We need Chrome CDM and extension.
We need another Satsuoni, another Tommer.
Ain't nobody got time to bother with Headers and License URL and PSSH and Python
scripts and EME Logger and JSON.DUMPS and shit...

**Comment by naim2007** [comment]
Enough of these stupid child pywidevine based tools.
We need Chrome CDM and extension.
We need another Satsuoni, another Tommer.
Ain't nobody got time to bother with Headers and License URL and PSSH and Python
scripts and EME Logger and JSON.DUMPS and shit...

**Comment by naim2007** [comment]
Enough of these stupid child pywidevine based tools.
We need Chrome CDM and extension.
We need another Satsuoni, another Tommer.
Ain't nobody got time to bother with Headers and License URL and PSSH and Python
scripts and EME Logger and JSON.DUMPS and shit...

**Comment by naim2007** [comment]
I'am sick of this shit...

**Comment by medvm** [comment]
@Mavrick007 this is a get request 'GetPlaybackResources', but a post request to obtain a license is needed. Use filter `method:POST` in devtools.
In addition, AnyStream is available for download from Amazon.

**Comment by arbarbosa1979** [comment]
> Enough of these stupid child pywidevine based tools. We need Chrome CDM and extension. We need another Satsuoni, another Tommer. Ain't nobody got time to bother with Headers and License URL and PSSH and Python scripts and EME Logger and JSON.DUMPS and shit...

You just want someone to do all the work for you, I suggest you study instead of criticising other people's work.

**Comment by 362227** [comment]
how to solve it? thanks
![QQ截图20211212112847](https://user-images.githubusercontent.com/91358231/145699106-388a426b-90b6-470e-9031-671a374cb28c.jpg)

**Comment by fx747** [comment]
Mikhail, could you eventually consider re-opening this issue and rename it to "Add [amzn] support"? In fact Anystream is not a real alternative, they have big trouble with the new DRM. And the most important - they don't give you the keys. 

Any chance to solve it? Or is it about AWS Signature?

In any case - thanks for your great work, you are our hero :)

> PSSH obtained.
> CAESEECzWPmhjEvAktSwgwupAoQaBmFtYXpvbiI1Y2lkOlFMTlkrYUdNUzhDUzFMQ0RDNmtDaEE9PSxOUG1BeUtrL1JqNnNqNVBIZGFlMXZnPT0qAlNEMgA=
> 
> license response status: <Response [500]>
> server reports:
> server did not issue license, make sure you have correctly pasted all the required headers in the headers.py. Also check json/raw params of POST request.
>
