### ISSUE TITLE
How to download vdocipher protected videos

### ISSUE THREAD

**Issue by wishwa2933** [medvm/widevine_keys#34]

**Comment by Palyer321** [comment]
It was the same question I asked in #21 

The solution I found was t.me/drm_downloader_robot . That bot is really amazing! You only have to enter the mpd link and it gives you the video!

**Comment by wishwa2933** [comment]
@Palyer321, 
Thank you very much for your response. 
I tried that bot. But It's not free. So, I'm finding another way to extract keys from vdocipher protected videos. 
If you found any method please tell me. 
E - mail :- wsaptharanga@gmail.com

**Comment by mmlgdcll** [comment]
> @Palyer321, Thank you very much for your response. I tried that bot. But It's not free. So, I'm finding another way to extract keys from vdocipher protected videos. If you found any method please tell me. E - mail :- [wsaptharanga@gmail.com](mailto:wsaptharanga@gmail.com)

Could you share the way to extract keys.
