### ISSUE TITLE
Add vdocipher support

### ISSUE THREAD

**Issue by wishwa2933** [medvm/widevine_keys#35]
Add **_vdocipher_** support

Input MPD URL: https://d1z78r8i505acl.cloudfront.net/media/ChIa1gxFQGBuI/7065244f/stream.mpd
License URL: https://license.vdocipher.com/auth
Unable to find PSSH in mpd. Edit getPSSH.py or enter PSSH manually: AAAAUnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADIiKnZkb2NpcGhlcjoyMjhlNWM4Y2JlMGE0NTA0ODE0MDBhZTVlODk3NGM5Y0jj3JWbBg==

PSSH obtained.
AAAAUnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADIiKnZkb2NpcGhlcjoyMjhlNWM4Y2JlMGE0NTA0ODE0MDBhZTVlODk3NGM5Y0jj3JWbBg==

license response status: <Response [403]>
server reports: {"code":2011,"message":"request unwrapping failed"}
server did not issue license, make sure you have correctly pasted all the required headers in the headers.py. Also check json/raw params of POST request.

This is the curl converter code :
headers = {
    'authority': 'license.vdocipher.com',
    'accept': '*/*',
    'access-control-request-method': 'POST',
    'access-control-request-headers': 'content-type',
    'origin': 'https://d1z78r8i505acl.cloudfront.net',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-dest': 'empty',
    'referer': 'https://d1z78r8i505acl.cloudfront.net/',
    'accept-language': 'en-US,en;q=0.9,si;q=0.8',
}
response = requests.options('https://license.vdocipher.com/auth', headers=headers)

![Screenshot (10)](https://user-images.githubusercontent.com/89116895/146635626-09973b63-7980-4d3a-bbdb-b4f25a248c6b.png)
![Screenshot (11)](https://user-images.githubusercontent.com/89116895/146635630-8ff7db52-5a2a-4b8c-82ef-0a08cee8a9a3.png)
![Screenshot (12)](https://user-images.githubusercontent.com/89116895/146635633-502dd6c4-e19e-415d-87d7-30d48b220ec5.png)
![Screenshot (13)](https://user-images.githubusercontent.com/89116895/146635636-1940e432-21a1-436f-810e-a9d0cb795b8b.png)
![Screenshot (14)](https://user-images.githubusercontent.com/89116895/146635638-e9a6936f-bc41-4815-995a-5673225b799a.png)
![Screenshot (15)](https://user-images.githubusercontent.com/89116895/146635641-8a93591a-285c-49b6-8021-166a9603a70d.png)

Please add vdocipher site............................

**Comment by medvm** [comment]
Did you dumped new non-leaked CDM from your android device? In case not use wvdumper, it requires rooted android phone with OS 6.0.1 < version <=9 and frida-server installed. Before that, you can check which version of wv your phone supports using drm-info app. The dumper only supports l3. Good luck)

**Comment by wishwa2933** [comment]
Thank you sir. I will try.....

**Comment by akkishay** [comment]
Heyy. Were you successful while getting license key from vdocipher? @wishwa2933
