### ISSUE TITLE
Response [415]

### ISSUE THREAD

**Issue by fpalacio78** [medvm/widevine_keys#5]
license response status: <Response [415]>

server did not issue license, check json params in POST request.

**Comment by medvm** [comment]
what are the inputs? Check headers.
Make screenshot of: devtools -> network + filter method:POST -> payload tab of one of the displayed entries.

**Comment by fpalacio78** [comment]
I send you in zip the information contained within header and mpd 
Headers
![Sifinaestamulo](https://user-images.githubusercontent.com/56003810/145666080-b34cf6ba-16cb-4a5e-bad2-b0933ca7a85a.png)
[headers.zip](https://github.com/medvm/widevine_keys/files/7696536/headers.zip)
mpd
![Simpdulo](https://user-images.githubusercontent.com/56003810/145666269-fd61ace3-8e8e-4115-920a-ea24dba18a31.png)
[mpd.zip](https://github.com/medvm/widevine_keys/files/7696542/mpd.zip)

**Comment by medvm** [comment]
wow, your site requires licenseRequest inside headers! I've never seen that before

**Comment by medvm** [comment]
copy all headers to headers.py except licenseRequest field and try again

**Comment by fpalacio78** [comment]
Removing licenseRequest should look like this:

`import requests

headers = {
    'authority': 'mds.ccp.xcal.tv',
    'accept': 'application/vnd.xcal.mds.licenseResponse+json; version=1',
    'x-moneytrace': 'trace-id=01f7de45-2d48-4271-9992-d41da2014af5;parent-id=2935409671029067201;span-id=4431246262513217380;',
    'user-agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
    'content-type': 'application/vnd.xcal.mds.licenseRequest+json; version=1',
    'sec-gpc': '1',
    'origin': 'https://www.xfinity.com',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://www.xfinity.com/',
    'accept-language': 'en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7',
}
response = requests.post('https://mds.ccp.xcal.tv/license', headers=headers, data=data)`

This is the error

![error](https://user-images.githubusercontent.com/56003810/145695769-02affa40-c028-4e8a-a66e-dd4a0cb848d2.png)

**Comment by medvm** [comment]
Delete line 'response=requests.post...' in file headers.py

**Comment by fpalacio78** [comment]
so I remain
![Spyulo](https://user-images.githubusercontent.com/56003810/145697186-481557ef-1fb9-4753-946e-0aa9543d1b9e.png)
This is the error
![powersell](https://user-images.githubusercontent.com/56003810/145697258-7b904363-f2e0-43bd-aa33-711fcbadb2f1.png)
AttributeError: module 'headers' has no attribute 'token'

**Comment by medvm** [comment]
you have an old version of the headers.py file, download the new one

**Comment by fpalacio78** [comment]
I give up

**Comment by medvm** [comment]
> I give up

Russians don't give up))

**Comment by whip28** [comment]
the same kind of protection on Videotron's Helix system. xfinity impossible to get the keys someone did you succeed?.
