### ISSUE TITLE
Vdocipher license issue

### ISSUE THREAD

**Issue by akkishay** [medvm/widevine_keys#51]
I do have CDM keys which I got from my mobile.
I had to add one line in l3.py file in WV_Function as following so my request will be made to vdocipher server - 

responses.append(requests.post(url=lic_url, headers=headers.headers, json=headers.data))

My header file looks like following - 

import requests

headers = {
    'authority': 'license.vdocipher.com',
    'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
    'sec-ch-ua-platform': '"Windows"',
    'content-type': 'application/json',
    'accept': '*/*',
    'origin': 'https://d1z78r8i505acl.cloudfront.net',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://d1z78r8i505acl.cloudfront.net/',
    'accept-language': 'en-US,en;q=0.9',
}

data = {
  "token":"TOKEN CODE': '"
}

// these 2 lines are commented
// response = requests.post('https://license.vdocipher.com/auth', headers=headers, json=data)
// params inserted below will be passed to data-raw 

token = ''
provider = ''
releasePid = ""

When I run l3 file, output comes as following - 
![image](https://user-images.githubusercontent.com/16587898/150176342-8b95fe10-3b4d-4a31-8e72-6253096ff92d.png)

My CDM key is L3 key

Anyone help me to solve this issue.

Thanks in advance

**Comment by BenQ21** [comment]
@akkishay i dumped cdm from my mobile ('client_id.bin' and 'private_key.pem')  i don't know how to replace in this code... guide me i'm noob

**Comment by stgmt** [comment]
> @akkishay i dumped cdm from my mobile ('client_id.bin' and 'private_key.pem') i don't know how to replace in this code... guide me i'm noob

u find solution? where to replace .bin and .pem

**Comment by wishwa2933** [comment]
> @akkishay i dumped cdm from my mobile ('client_id.bin' and 'private_key.pem') i don't know how to replace in this code... guide me i'm noob

Please tell me how to dump cdm from rooted phone. please give me detailed guide to dump cdm from my phone............... 
I know to replace client id and private key...............
I can tell you about it. 
So please be kind enough to tell me how to dump cdm. 
E mail - wsaptharanga@gmail.com

**Comment by wishwa2933** [comment]
> @akkishay i dumped cdm from my mobile ('client_id.bin' and 'private_key.pem') i don't know how to replace in this code... guide me i'm noob

@BenQ21   Please tell me how to dump cdm from rooted phone. please give me detailed guide to dump cdm from my phone............... 
I know to replace client id and private key...............
I can tell you about it. 
So please be kind enough to tell me how to dump cdm. 
E mail - wsaptharanga@gmail.com

**Comment by advikk** [comment]
> > @akkishay i dumped cdm from my mobile ('client_id.bin' and 'private_key.pem') i don't know how to replace in this code... guide me i'm noob
> 
> @BenQ21 Please tell me how to dump cdm from rooted phone. please give me detailed guide to dump cdm from my phone............... I know to replace client id and private key............... I can tell you about it. So please be kind enough to tell me how to dump cdm. E mail - [wsaptharanga@gmail.com](mailto:wsaptharanga@gmail.com)

mailed you.
check it

**Comment by aningxu** [comment]
> > @akkishay我从我的手机中转储了cdm（"client_id.bin"和"private_key.pem"），我不知道如何在此代码中替换...引导我我是菜鸟
> 
> @BenQ21请告诉我如何从root手机转储CDM。请给我详细的指南，从我的手机转储CDM...我知道要替换客户端ID和私钥...我可以告诉你。所以请好心地告诉我如何转储cdm。电子邮件 - [wsaptharanga@gmail.com](mailto:wsaptharanga@gmail.com)

can you tell me how to dump cdm?  mail:aning@aning.me

**Comment by medvm** [comment]
use notaghost's script for this site

**Comment by wilsonssss** [comment]
> use notaghost's script for this site

Could you pls share link?🙏

**Comment by medvm** [comment]
[scipts](http://getwvkeys.cc/scripts)

**Comment by wilsonssss** [comment]
> 
Hhh, I know him, from v d o help. May be better if del your comment

**Comment by medvm** [comment]
> > 
> 
> Hhh, I know him, from v d o help. May be better if del your comment

why would I delete it? getwvkeys is a public resource, anyone can google it
