### ISSUE TITLE
how to use it 

### ISSUE THREAD

**Issue by mahdisky** [medvm/widevine_keys#56]
how to use it?
i have some problem 
widevine_keys-main\cdm\formats\wv_proto2_pb2.py", line 20, in <module>
    _LICENSETYPE = DESCRIPTOR.enum_types_by_name['LicenseType']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'

**Comment by medvm** [comment]
wrong python version/missing dependencies
