### ISSUE TITLE
UnboundLocalError: local variable 'license_b64' referenced before assignment

### ISSUE THREAD

**Issue by joostshao** [medvm/widevine_keys#60]
Traceback (most recent call last):
  File "/root/drm/widevine_keys/l3.py", line 130, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "/root/drm/widevine_keys/l3.py", line 125, in WV_Function
    wvdecrypt.update_license(license_b64)
UnboundLocalError: local variable 'license_b64' referenced before assignment

https://d1gafjrnux9y1n.cloudfront.net/15875/EncodedVideo/uploads/movie_stream/full_movie/847702/stream.mpd
https://license.pallycon.com/ri/licenseManager.do?pallycon-customdata-v2=eyJkcm1fdHlwZSI6IldpZGV2aW5lIiwgInNpdGVfaWQiOiJYRlFJIiwgInVzZXJfaWQiOiJMSUNFTlNFVE9LRU4iLCAiY2lkIjoiNTE0OTI2NDcwNzQyMzUyOTE4MzM4MTA4MTc5NjQzMTciLCAicG9saWN5IjoiQ05ubGp4RnBkY3IvK0dHTjBKU1UrRU1sRGtPekpKc3FzSjgwcVM0YzhhR3E3YmJxVktqMjdQWVRCVytJVlVFZVJqOVdaTmtlOGd0ck1xblVVNDg4ZnMxY1hqOHNFNVZtbmdiNFRTV01ybXJCNnhNd2hFRzhGNVpja3JCQmVzMDhRaVAwdWQrT1RsbzgwT0lZK3lpWlZLZHhYSXRySlBNcWxTZVQ4QVJDMEN5RG9rWVM1Z3lqY2p4WFk1NUhjRlRwWG90UUh2bytySjZ4WjhyY2p1eGdTRitONnlYWnZvaDVkUHFSRW1LUk1pZmxRcCtYZGpTZ3dqOEk1MnppRkxkbXdEbFZwRFM2MC9KZzFQaVhCbUE1NVlKV1VQQW1HSE9jZzcwSGRpVHhuRTlIYmZjZ3ZTZE1kWW9adTk0WDlSSDhrREZTOER1azlMS3dQQVFabFJtckJJUHRsSnluRFVZTXZ3Q1BqWHlNNUx4aC8xNHZyTTBUUmN3MDhyZEpjeVFXMHBpb1lGWWZXeTVCV1JpK01EMnRDWFdjc1IzVTZ6SDNPOHh6bDFhT1p1MzQ0eW02cTRHQzVFcGErY0JvWEtWTjNaT3RKc2NsTGx2NmJuaFU5SURrUnMxOE12OUhjRksxRlRaTkMrcG9PMUs4RUI5WDhRc1BBQ2tlcndqVWIwSHNncmxQZkphQThxTkVoZURvN0h4czZYQ0dQQ2RvLytseVhvb3AyNEcvdGgvbHV0OFRPOUw4YnVsR2dualUvSGhrQVFWTnBCa3FyUTJkNzUvSmlpS0hCKzBkTHc2cWRnSXhSWFpZcTVLNmxGS25MSEFtaW5jL0graEl2c0UrWkVIY2tTdWN1VVRkam5OS3V6bktSTXN0K29yRUhTTnpoZlkwZ0tKSndBMHdkdHVESFp1ZkVUa2I3SW1Hdk05bzFTbUtZWUdHVVYzU2hrVW9xMGJTVXhrb0RBMWNYNC9TbW1MQSt1YVplcjF6UlV3PSIsICJ0aW1lc3RhbXAiOiIyMDIyLTAyLTIxVDA3OjE0OjM0KzAwOjAwIiwgImhhc2giOiJjUk4xbTN3Ym1iVlQ4VmRhd1NHWVZaa0tTRlhyM3h6WUJSSktFU2ZqdGhrPSJ9
AAAANHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABQIARIQEUYlVmV5KBdAIgRGEoUXgw==

**Comment by pythonkenyard** [comment]
Invalid cdm

**Comment by joostshao** [comment]
chrome ? or other sugguest ?

**Comment by pythonkenyard** [comment]
any working cdm.
I'm not aware of any available from chrome but I'm sure they exist.
Ideally dump your own from phone is easiest.

**Comment by medvm** [comment]
> Invalid cdm

absolutely correct
