### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Superbia000** [medvm/widevine_keys#63]
...

**Comment by iangaGMcomZ** [comment]
How to contact, want to buy, leave an email

**Comment by Superbia000** [comment]
> How to contact, want to buy, leave an email

Just create an account and pay with credit card.

**Comment by medvm** [comment]
@Superbia000 Since an "invalid token" error occurs, the tokens are either one-time use or you just copied it incorrectly. In the first case, you should trace the API request that generates this token and generate a new one by sending a curl request to the API.

**Comment by iangaGMcomZ** [comment]
Give me a contact information or a link, thank you

**Comment by Superbia000** [comment]
> @Superbia000 Since an "invalid token" error occurs, the tokens are either one-time use or you just copied it incorrectly. In the first case, you should trace the API request that generates this token and generate a new one by sending a curl request to the API.

How can I trace the API request that generates this token and generate a new one by sending a curl request to the API?
I am a newbie.

**Comment by Superbia000** [comment]
> Give me a contact information or a link, thank you

jimmy9093ac@gmail.com

**Comment by Superbia000** [comment]
> @Superbia000 Since an "invalid token" error occurs, the tokens are either one-time use or you just copied it incorrectly. In the first case, you should trace the API request that generates this token and generate a new one by sending a curl request to the API.

I found a JaveScript probably about this
![螢幕擷取畫面 2022-03-14 181818](https://user-images.githubusercontent.com/24918410/158152741-42e528ff-07e6-4d94-b7ad-8bcafe3dc8dd.png)
![螢幕擷取畫面 2022-03-14 181847](https://user-images.githubusercontent.com/24918410/158152759-555186df-6b1e-4589-88df-a87a3dd58f0c.png)

**Comment by Superbia000** [comment]
> @Superbia000 Since an "invalid token" error occurs, the tokens are either one-time use or you just copied it incorrectly. In the first case, you should trace the API request that generates this token and generate a new one by sending a curl request to the API.

I can get the key now. Thank you.
