### ISSUE TITLE
-

### ISSUE THREAD

**Issue by daliali2088** [medvm/widevine_keys#7]
-

**Comment by medvm** [comment]
@daliali2088 pssh in text please, 'Request URL' from headers tab?

**Comment by daliali2088** [comment]
> @daliali2088 pssh in text please (for test). In 'License URL:' paste full 'Request URL' from headers tab.

pssh ： AAAAQXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAACEiGXJ2OW9xOHE1OGdsYWRhZGRtd2VzYzZvdzVI49yVmwY=

license url ：https://drm-license.kakaopage.com/v1/license

**Comment by medvm** [comment]
This is just the case when the server requires additional data (token, etc), can you send the "copy as curl" output here?

**Comment by daliali2088** [comment]
> This is just the case when the server requires additional data (token, etc), can you send the "copy as curl" output here (pastebin burn after read better)?

curl 'https://drm-license.kakaopage.com/v1/license' \
  -H 'authority: drm-license.kakaopage.com' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Microsoft Edge";v="96"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'accept: */*' \
  -H 'origin: https://tv.kakao.com' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://tv.kakao.com/' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,zh-TW;q=0.5' \
  --data-raw 'token=PFYtFSqWMYIROJYywBp0rbKvpD3z6N6E6UezNrZmCeKHkcJ5BiH4J8qwO0kfWOmrSsyFJMg9OqKKEwvuQiXL4qdDTa6ZYplNV9IQt6eEuveglDxjVlYd0vAecS5TZKn5mIs01YxcYNlTC7tu3BIk63JhMykMWEMmj1oEqaLa7N3ZrfU2VTlEPaWXBQV6PxnFeD022Yi298GOX/lDik7sXt5u4duT0aKIYbz0HPmjoh8b9Uy8bvzJUa0/SlgRcsW8RNTNjRJHM6N7BESCBGFEZcWoSXeDLEblEfRoBKro2iDGB1neLfRdY1fj7tJX1Rn9lj+OJwRTrBV4XoTQFuSsFwvYCeQfkAoRHXnze9njI5pY7sYgIGxuM4Zh3Wqaps6kxdO53QMm0jJ/L41X6r5CikSGKQ3Rcps8eQccZb9svEuyXMof2nm+eYL+AVPPrfmAf/BrmUHfiuF9CmNsF9pI7PjJfLeASmh3KDI/5gUuC4uJB7rjTzHVWNRz8MSvYjJ37/5V9+FTihpu04+0jFZ1AlGRks2dzk2IGvm5WcwUhsW2l/oQXlh7AgsksIl2DT0wH11WeG+h1/ijymMcG9AZzsxtkC53eLJ8bl55/Aag0TJfX4N6KvV7UhglXxkLifb06bLK/wlcGCfb01b4cnngcjPJEMxh2+Q7sJSnbyrtsfodzNah8JXITmx5kTkFFZkdtga1ha9jAb+Z40VMQfbrCLgh0GEe2G3VczcIt8QHAWAeS91TkzLbMRAugbgLvdbI8yQXtM15uo+TXrV4PNFprug33AnvnQu7IpNxlmgPMZhEn4Qqc/V++OFIpz/JYEMnLFvjYcXE2+sPc4uKnoE0xk33+IgZKtWtDhxRg2SJKyKOYxXucXybUuqPP/d+Nq1VNhD84Of+EfVvBjs1u75pNz/kmu5ms9ppRMkafq0/2311hbYi6VXmp6AeJweGJWkGKEFxw7xADuC8iM7xWnXW5aiNvhbsXBOwuTK8b2ioxjrg6OFhiMck+z9M5FHg+ktY7YB8iY+0V6B/Op2cQGtLaZ2E9lsomlQpxL+LiPI7UWEqmALEGH/Pk5tdLnlFRjEk2PPc8YURw+/nkP9tqJ/AXQwaXc9iwC5yxlYPCsp/Tc4=&provider=kakaotv&payload=CAESrh8SOQo3CiEiGXJ2OW9xOHE1OGdsYWRhZGRtd2VzYzZvdzVI49yVmwYQARoQxsEOi2gPrHVFcDIAU/WDSxgBIMvL0I0GMBU46urz0QxC4B4KFGxpY2Vuc2Uud2lkZXZpbmUuY29tEhAXBbkXzBIEhosGMzovdyqMGqAcfcpbWzzLW3YyZAJkYhF29SgA+5Z7AngyFpzW8QbWN5BXzIpFxr8+JbvoaKZ+gLbbG3axSrPEVs4lTayuOkGNexogwb8EttI3MEBVav3l1Urx/X1A4tv+sJzOjEPwM/7sCaFJ59Du+Skmzq4xToN5JDoe5dJJFRTNICa4xESmey85N/XgxghQgJL8yMJAD7giQLhT4ndVQmec1F7auFXNHDV1cnNVviTDXRKkAltSbfgu4RH6ReK669XD9lSvOs+ALfTlDY9FIJnIub0KkKpaKnV128fd1vCd9lBiNLlY6hlJTnAmqxflzGLGVogTcHEZSGub1ZD2lnzLBuEcKlgwk+H2JEQyDTEds2EYSotzFD5Eo/hW6kIKYKKu70Buh2sxGR8xsPlRLYV6rxQsfKYRDRHDLJjq5L/V0jF7LhIRNEeZdIyaWGIXcsVQ1CzhWr8OjTnuKv7BPKr27MvhkEf0fYIqYZ+c9oLHdl8f4986VoF3vY0Bjn4z/XG4UKpA517dMSd75ty/92lhJlxhEpCB1OLNKo+9DD0oYyiCMidOMUHXX6BvKh+bTrPCE/l3G80q90D9sIs94MdLOxs4X/QimhqcuhimWOIw+ntjbFU+ta3V4Fn0esWmWE+5gGxxamQRw1l4TRz4+jPlzNkelyfG5lmYTDPP6mqIFmobmYQI8BcxyDpE+6RuliUVnxBHAOAFxA6G6pFzZmP4/qKxcZI/epVKb8s4iZTlV/UiJEbWYkX89/jlGfDvMwVWFaGTqeEX6buXOxIJ6oMz0782R8CM++Mujz/d50RszVeQWmgkPjbr/al+mfRSelTob4p7Mo3zYpsF1xJtaaTDu8vIVWHuQ1lPHVvG/2aP1CKrVvkdKfh4EgyY/Ci2YpO/uHDqhdGgw+9dDuTcA3U4agA713PjupKcqIFt3NPJI2grW+R2fWA+B+X6ppB4CQHE35Y74C5oANaSzXuFaimP7bC7R9B0bjkfF6Unbtn7ksjvsV5is7RuzQ643y918iBMo12CGZQ7RWLt2RmXQHdbCbaASS1sADIePTaLiUSXsjZn5T5GgYQitl49bOPQGHjvBXnb/1186doIeatCW35k6GdcMVfpItfV3ud3piUf1kCEb0bWQZFv3VLwUpGCAG05O+JY5nK95REsmNCM+QtlVRtAwwL8t+O9ic6/eD4i8PNUl9sOp8mf19VWCesyY9OjPcAVDBpUzoF1XZSo1ws8JoIOj9S5gb2pL6etMKpbyfIBA9dqh+9n7Q5hoQuhD4Ffkp8X1mTjmYdrij6TEBSqGbLlMprpYoj/2/yeYm0IL9ry973MAjDz6TyrXG3yS1d1ZicJ3+nA6frOvRF0Z1IECuuUzY/c4mBSnuG6KqyNxUvrxbWmr91DJZAC/I0/m/lEVYxmL7UR7P5N+INGmbfp855S/jR82fEo1IStbgqW8Uo7tbxgcL1GCiSabcEk/GTuF6+TnqqamTZSBzNMrFfyr1wUuNy2pCkYjqXhSPktQzUe29LeWRYbl1TBNxXLez9wSCzoBFdnqKBdMOUNszmDMbckGlucLOpoAw9KGYtiCV/MOOgIgLEIKQ3PyFSKQWNJiVa1s/TM71oO8RJHxiEHodTOKpgvaZqdhXidA1XEh9GGwUdN2lk1dkRCbJVpBf3BZkmt3Iz0zOOcIhjC9qYnHyOD/IHsoI6he30r2+9P5LZiV+SGxPmhBR73EAycVnn2ax72mWNvguep8nJnRDKqENd+zYSvZLPU3dCocr/gfDMkO5Ftg6/iItPMHjDBTlP6kDmrWyNDp9XhOncVZZHF2bkRUA179WjzHh+J+AqJ0qEep/ycIrZGN5nQQZsrqSBfSnO7VsdcrhJODR3EYKvtXbB3NUeLthBsE1aerpw6jQLrA4+4W+oGPGEybSPy5pl2t00n1kxHlawrgtTvu9sctbGj2Px3nYmelnAsK+9KGb5PbwhMNWUYSGlnKVgz9304LQHLV5SVzlhFpzThRbC5owE/f1R0qBFexQF7R/kyipFNpyq7yy/u/q2FY2wwhLsqopv8QSyBZxQ2w6suJ7vNoDTn/uRVv5t2nHqGuUqeBhXFkHCtFEB+qYu/pCXroDc+yaPrJiWI5w62IFVx8jkFrWk7b73zQ18Ocw9oaxqKG3znRaECwNQB23QkCfiDPrCot+FbLFB+am7vXkj5cc3XQbKN25x1rYvy1lROGX0DPVf+z1sumUsfzS4QxiY1x2ZZToVtECmBPIm+h99U0G3EdDRvtIm5RYGq3uIq0+jbG4TiJQff6jvrpUyDfZhvtJpbpGrmyTEakMnPW1HTgusDW60zB9cnXX6MFOTrwXCTdDCcaUiuLcbRxHZ9F0zJeTnh1ADHZwFZgJG4xCGS3Pm68QWiyvIH22m0gm6aNOON0+dI6QfmW1krEHTXSTHAC6zBNQd49bXfoWo+IF/HVyQnS5p2zjE5d9VmoofTkGWzaqGAkrdfVW68mttlxU+nb56fDGp3AvD5wH6KxH6D3xYZTwMlLoMzswFzmL7aWMqsbsshykSDf7pRTINpUcDjk9ujPwOBVxsa0YkKplx05CEU004bTxcnF0KxEAGYuxU4aDmaqSm6mIQcNN33LP5xIVsBIGfX1ZEfJLFD4w23P/HcVUKXsBkgqFM/IPsbOXTKs3dBlx2XxyrRt1LoUSWUnRLC7I7PXrJYgSHFArsz8ZIMviw8HCFWo56sDgCwp27Xsm/bbwK2fZ7VeiQccINDnu0Ve250VsavKUrogmsY/cnlDcz1UHRbTRXARwan3hDVxjK9t98s4/Qw+C/bj7g+7V0klat7+hyHqZ+9NgKf6WZ09bTeGykZp/BmTOMJVedhLZPQ2AljpiGgn6IYsM6Ly2zUYmcwwwduAIAAC2/AGi+9DoVzly6CoxVu1LyRzle0bU2HjVx3YQrWwREN2LiRSYPIkRZBoEKHcc4uaxClYpH1S7geKBRGnBkcKkF+8Tw6ZzyR3lQPhkiY9t898jfgXgr2hrrPniriPgmElZ7ZCcrbOL77WVZzZtuRyUBvtOwHC08gIzLpefqGpgNWXCHgMFUVSDECALpzpOOtS40HyOi2ptNOTo4S152jobygADGVCBWFtVeTMikzvwsftbO8x7thciOo+ADf9j9FLg5+nLA+CPRbBCiXU6/VX/woIQjPmYyZUfXr4DI9wN6ALajfglf9V+N8RDk7/siiXsGHfgnvnDSkNExTiT47q/FaZ4xtlbwCq/OB1cr+pQQAgy0JQKCZosZFCq6CHbcaaa5eSHsG8X7AVsWHQ/T3keB8eUAte3K8VV9UvlQZ0TOAKROuj281aeQmN9SB1ZOMyYoBoBB0okFR+Y5UgzOB1WvRutn+lfddwyKh5PJ3LN4l3JSVIcFKp/h5ESqvibbLEMvFRu3LArNhedi78N/RFYHubm+n6yciuTri0LnQAOOgMi/cxlkIeE0ACIIl8ketZu8A3J46Gb5laGBG0aih9kLFEc2Vl/RuSnBrHBfwaszQTge+BDTKj6gor1puiWFiLUfLQGGj/ORQeb5n/SSQGc2QJpbubKAly+1QC/cUP9GAycnMdiD4zXc6UgiEh7dhSBeQzlrVEgFqjGvXuqdxRlBgGvQeUj6wVB0crhZyLGGk3dLcaVCy21aWXwcOwG7pErWwJ5fQ/qOILWqOiHlp3iiMs7+tIvyIsglcDv32v6HDD0LaxUeBqk6DLOCveAJyiT90lZ+09qHPMqyPePrL4qCxOMO+uAT/4EOnBCEA4sVnSRguMsH/hMDSfJTzWBOX1+Z1d/pzu5UWFQe3M/kJCRmaet2ATVkn4tX0g1/EqlowpajQ3IBsHr2XL/Zlqx3iZI6ddAULu6fEQHwiBfheHqldT1YzTxIbxOWXME6SzHY9BM3wcegEWVAxuprI0F7LUoBrfB9l59sC5pOAqGpZTY+Y3Q3nbmtATbn2VSs9JeSzRwlkIUzzxY9L472AsoOT2ZBhZ4DumPL/E8ioDnH/FJhYfgRulQ2pmo4LFoEvVleti0Xf6oDg2fc+BxgklxsMs6Mh8CZBsBljxAAd4DueFx3Vtf1MuTuL4NQ06wItgxleD9nAEMG6bwtlDvsii+3OD13otWdTrTiwIv1Xj0G4SBiA92XBmUEEC8dR17AlVRqOMFfN0yRH5TsRUar8eglCD4U4HKZd3G0ZhdQgjGOEGu9j4iZje16ZdF5O7ORHz94+Zm/o1veVs3tPX4iCbispysKyrvHmyF0MEABWd0+Q9BNI7HtvO1sErYIEKKzrMMJ0XDYmY/OiGHaeAWSh9j+WcSdWfG1L65hQ+wIpkVuYpOI2db500zz5XA35IVcyJDE4WYHKqtvyKtDu/0uAc3QLobqK2AlvnFjVxeqQu27HuyRfjYKi/UdlNKFDbNPTI/dserqXjcr1jrloEuShilYaBG8vvej8Y4p5lykBnUs4QYjdls+m3lQaFP51e8ogjZu0Qk5StOaThuiAFw0/c+KoVBiov7ABcyLtprwMXeMnitBxZY01ZRKtn9TA5zFUvtE2Gf6/TOw2zsrp7Drx4ATqu8oIvPLgo7kznIAN28Wl/NUXG3nEoHkkwo+X5bfQCtSeKyVevxyaBOnsFvccoMraEY3hFsUQ60xJ+oO/gg+IhNWvHDBNNnAhMAITsiWDp+kOpxYc9vDKlW7XOSeWlOm78ojZHILpwTXR5B2Gi2zt63boSamSUwKReqyCsg7CXiffKFaxqEMOcscOqdyDh9M20BL1nSpOKobkhq6aepPnkMcgaJhAv8kqaoJrUCV/8S1dKRullVX6pICkLkGzHaTz5l2H5yJfJEj9899P+iIQSQWPQQqo03M30QNTAQ/15iqAAo4aoYL//WxAJ9FulsE4jxpGNRFUHBKSqjnGlz9B3VeIC5Sgh1lYlhe4BSPY7jgOqcnKeZMZmx5BeMayT09CpZygFvq0XjD9/l7q1hL8vvnZf3ZYBnrd70k29ZswLRSmo17ry6iNjcbcjV8aeH7w054LgL8naVWNjYRqq/Dv2DYMgukLl8Fyu9uaaAwcugp+zoxkY+q72VDnS0ARvf9lXyXbjTwWbJLfp6DfB2c1wRgyIi5ViY/OSbqoQAp6CZqDHsbo6KKwTihZ15BFtZEZ5fApYSOJzyY0Xq/ahvTVcv87OOYIFQMQ5SV67UQZP3QOyJ2E1hZgo1QBwSgrm4g9CfwagAF5nCz09KLEvX8urm837jTQUW4beItbQa39Iqcg22xhGhTKI9+UaHe6WtVIm9DT/de6bASU5mi9Kkcb/rUkEwNmdNgmuQiqo47OBfzZ8kqfpvoCAGOBut8nC1YRGAOaxbzXCBM8f2lt9t7oLKfxdkIIFJp5CXB+CtfQCmP4XZww70oUAAAAAQAAABQABQAQyjz1asx1lEs=' \
  --compressed

**Comment by medvm** [comment]
@daliali2088 check now, i don't have korean IP. Refresh page, paste new token to headers.py (replace old one).

**Comment by daliali2088** [comment]
> @daliali2088 check now, i don't have korean IP. Refresh page, paste new token to headers.py (replace old one).

Thank you, I tried it but got this error

![1111](https://user-images.githubusercontent.com/77323405/145664945-17a74fa3-b1fc-49e9-aef4-94485504dc85.png)

**Comment by medvm** [comment]
Apparently, your version of the headers.py is outdated, since it does not have a token variable. Replace it with the new version.

**Comment by daliali2088** [comment]
> Apparently, your version of the headers.py is outdated, since it does not have a token variable. Replace it with the new version. Then refresh page, paste new token to headers.py (replace old one) and run script.

I just tried refreshing the page and replacing the headers.py, but I still got this error, and then I tried several more times.
![12E309C6](https://user-images.githubusercontent.com/77323405/145665235-5631187a-d231-405b-90c1-4281e5754e11.png)

**Comment by medvm** [comment]
[Correct headers.py. Notice lines 27, 28.](https://user-images.githubusercontent.com/43696206/145665319-0ebfe24c-348f-4423-ba0f-8ecf8b1e2c66.png)
Does your file contain these lines?

**Comment by daliali2088** [comment]
> [Correct headers.py. Notice lines 27, 28.](https://user-images.githubusercontent.com/43696206/145665319-0ebfe24c-348f-4423-ba0f-8ecf8b1e2c66.png) Does your file contain these lines?

[headers.txt](https://github.com/medvm/widevine_keys/files/7696518/headers.txt)

![11111](https://user-images.githubusercontent.com/77323405/145665473-b0da23b8-a3d1-45c8-aabb-a790781a1902.png)

**Comment by medvm** [comment]
that's wrong, token and provider should be separate variables, as in my screenshot.

**Comment by daliali2088** [comment]
> that's wrong, token and provider should be separate variables, as in my screenshot.

I am using this URL to convert curl directly, do you have the correct template, let me try 
 [https://curlconverter.com/#](url)

**Comment by xiaoxiaoliya** [comment]
> 
Do you come from China? Can you give me your contact information? qq?

**Comment by xiaoxiaoliya** [comment]
> > 这是错误的，令牌和提供者应该是单独的发起者，如我的屏幕截图所示。
> 
> 我是用这个网址直接转换curl的，你有没有正确的模板，我好好利用 [https://curlconverter.com/#](url)

Do you come from China? Can you give me your contact information? qq?

**Comment by medvm** [comment]
> > that's wrong, token and provider should be separate variables, as in my screenshot.
> 
> I am using this URL to convert curl directly, do you have the correct template, let me try [https://curlconverter.com/#](url)

Copy token from [here](https://user-images.githubusercontent.com/43696206/145684044-8662f0dc-d3f9-48d3-ac43-15e8923a85c0.png), be careful, this "form data" after the token also contains the provider and the payload itself, you do not need to copy them into the token variable

**Comment by daliali2088** [comment]
> > > that's wrong, token and provider should be separate variables, as in my screenshot.
> > 
> > 
> > I am using this URL to convert curl directly, do you have the correct template, let me try [https://curlconverter.com/#](url)
> 
> Copy token from [here](https://user-images.githubusercontent.com/43696206/145684044-8662f0dc-d3f9-48d3-ac43-15e8923a85c0.png), be careful, this "form data" after the token also contains the provider and the payload itself, you do not need to copy them into the token variable

Is it like this I just copied the content of the token, if not how do I know where to copy it to?
![111](https://user-images.githubusercontent.com/77323405/145685134-5074bb4f-8a07-411b-b54c-4e8974353472.png)
![5555](https://user-images.githubusercontent.com/77323405/145685141-e36903e2-bc35-4e15-ab96-3ecd43ed8aa9.png)

I get this error with this headers.py

`license response status: <Response [400]>
server reports:
server did not issue license, make sure you have correctly pasted all the required headers in the headers.py. Also check json/raw params of POST request.`

**Comment by medvm** [comment]
Now you have done everything correctly, perhaps the server requires to specify the name of the provider inside the license request, I will check it

**Comment by daliali2088** [comment]
> Now you have done everything correctly, perhaps the server requires to specify the name of the provider inside the license request, I will check it

Ok, thank you
