### ISSUE TITLE
Unable to find PSSH in MPD: 403 Client Error

### ISSUE THREAD

**Issue by kevin4dhd** [medvm/widevine_keys#70]
how do i get the PSSH?

![image](https://user-images.githubusercontent.com/22886367/160326464-40b1c32b-3ac0-4918-8404-283358225dfd.png)

**Comment by thejackal2017** [comment]
I know this issue was a year ago , but the script asked you to input mpd link and you entered m3u8 link !

if the script can't detect the pssh from the mpd file , then there are many methods you can use to find the pssh , maybe eme logger is the easiest

**Comment by medvm** [comment]
@thejackal2017 better late than never ;) thanks for participating
