### ISSUE TITLE
Add [site_name] support Is this script work for Peacock.TV

### ISSUE THREAD

**Issue by furkyto** [medvm/widevine_keys#82]
**What additional fields does your site require?**
A clear and concise description or screenshot of payload tab of post-request in chrome devtools

**Describe algorithm for generating additional fields if they are not static**
[text]

**Comment by medvm** [comment]
If you interested in Peacock, write to my telegram @medvm. Peacock uses a quite sophisticated protection algorithm with hmac, but it can be defeated with intercepting POST and changing it's contents on fly.
