### ISSUE TITLE
Add kion.ru support

### ISSUE THREAD

**Issue by Parakovsky** [medvm/widevine_keys#83]
**What additional fields does your site require?**
https://i.imgur.com/giEzJkV.png (sorry don't know how to insert scrinshot)

**Describe algorithm for generating additional fields if they are not static**
seems to be nothing fancy i think it want to have a token and i wasn't able to solve how to give it :(

**Comment by medvm** [comment]
Там ничего сложного, насколько я помню. Однако, в паблике лучше не обсуждать работу с сервисами СНГ (во избежание юридических проблем). Руководствуясь той же логикой, скрипты на наши сервисы также не продаю.
