### ISSUE TITLE
AttributeError: module 'headers' has no attribute 'token'

### ISSUE THREAD

**Issue by realuali** [medvm/widevine_keys#84]
I am unable to execute l3.py.
Geting the issue: AttributeError: module 'headers' has no attribute 'token'
Can anyone help me to get the keys.
MPD: https://z2cltd.akamaized.net/mini01/vods/54/tanhaiyan-s1e1-4335/637d30a524335-948-mp4-cenc.mpd
License: https://mw.hivesys.net/widevine_proxy
KID: 3e1fd6ad-1a7e-8a8e-573b-0a01e9e31325
PSSH: https://mw.hivesys.net/widevine_proxy
Headers:
import requests

headers = {
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive',
    'Origin': 'https://ptvflix.org',
    'Referer': 'https://ptvflix.org/',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'cross-site',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
    'authorization': 'Bearer 8ek5t91bcd06txjunvf67o0cfwugkdkxcykv3pyg',
    'devicestype': 'd2ViIHBsYXllcg==',
    'profilesid': 'MTAxNDc4',
    'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'Content-Type': 'application/x-www-form-urlencoded',
}

data = '{"devices_hash":"2695673035","devices_identification":"Windows 10 Chrome 108","edges_id":2,"offset":0,"rawLicense":"CAQ","timestamp":1671273824.588,"version":"1.0.7","audioLanguage":"en","bitrate":2500000,"remoteChannelsUnicastId":null}'

response = requests.post('https://mw.hivesys.net/widevine_proxy', headers=headers, data=data)

**Comment by usmanali343** [comment]
@medvm Can you please delete this issue.
