### ISSUE TITLE
Mime type error

### ISSUE THREAD

**Issue by TiRajo** [medvm/widevine_keys#9]
Traceback (most recent call last):
  File "D:\Tools\widevine_keys-main\l3.py", line 24, in <module>
    pssh = get_pssh(MDP_URL)
  File "D:\Tools\widevine_keys-main\getPSSH.py", line 35, in get_pssh
    if ad_set['@mimeType'] == 'video/mp4':
KeyError: '@mimeType'

**Comment by IzukuDeku01** [comment]
I'm also getting this error. Any way to fix this !!! Site - www.voot.com

**Comment by medvm** [comment]
text here your mpd link if exception is still appears

**Comment by IzukuDeku01** [comment]
> text here your mpd link if exception is still appears

I'm getting on this MPD-https://jiostreamingdash.akamaized.net/content/entry/wvdata/45/32/7dfd8b004ce611eca861b750a043619d_voot_mobile_premium_1637818446079.mpd
Licence-https://prod.media.jio.com/wvproxy?videoid=2000474287&vootid=1237643&isVoot=true&voottoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJiU251eG12eTN4TktsV1A1NGpWYW5wUDBQYVQyIiwiZW1haWwiOiJzYW5rZWVydGhpQGdtYWlsLmNvbSIsImRldmljZUlkIjoiV2luZG93cyBOVCAxMC4wIiwia1VzZXJJZCI6IjM5NzQ0NDE4MiIsImlhdCI6MTYzOTIwNDEyNCwiZXhwIjoxNjQwMDY4MTI0LCJpc3MiOiJ2b290In0.kdZB2xBHriJcpMdREsUWW3mKC5ryTS1UidLRqqrCn_M

    if video_tracks['@mimeType'] == 'video/mp4':
KeyError: '@mimeType'

This is the i get any solution???

**Comment by medvm** [comment]
You have some old file get_PSH, I have set up exceptions...
then read the readme.
